// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package example

import (
	testgen "github.com/james-w/gomatchers"
)

func NewParentFactory(p testgen.Primitives) *testgen.SpecFactory[Parent, ParentSpec] {
	return testgen.NewSpecFactory[Parent, ParentSpec](p, NewParentSpec, BuildParent)
}

func WithChild(v UserView) testgen.Opt[ParentSpec] {
	return testgen.SetLit(func(s *ParentSpec, m testgen.Maybe[UserView]) { s.Child = m }, v)
}

// Below is the lower level API

type ParentSpec struct {
	Child testgen.Maybe[UserView]
}

func NewParentSpec() ParentSpec { return ParentSpec{} }

// Defaults (simple heuristics).
var ParentDefaultChild = func(p testgen.Primitives) UserView { var zero UserView; return zero }

func BuildParent(p testgen.Primitives, s ParentSpec) Parent {
	child := s.Child.Get(p, ParentDefaultChild)
	return Parent{
		Child: child,
	}
}
