// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewAccountSpec()
//	opts := []specta.Opt[AccountSpec]{
//
//
//		WithAccountUser(value),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildAccount(specta.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewAccountFactory(specta.New())
//
//
//	result := factory.Make(WithAccountUser(value))
package spec

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// AccountSpec is the low-level specification for building Account instances.
// Most users should use AccountRecipe from the parent factory package instead.
type AccountSpec struct {
	User   specta.Maybe[showcase.User]
	Status specta.Maybe[string]
}

// NewAccountSpec creates a new AccountSpec with all fields unset.
func NewAccountSpec() AccountSpec { return AccountSpec{} }

// NewAccountFactory creates a new SpecFactory for Account.
func NewAccountFactory(s specta.Source) *specta.SpecFactory[showcase.Account, AccountSpec] {
	return specta.NewSpecFactory(s, NewAccountSpec, BuildAccount)
}

// Default parameter generators.
var (
	AccountUserGenerator   = specta.FromSpecGen(BuildUser, NewUserSpec)
	AccountStatusGenerator = specta.String().ExampleHint("status_").NonEmpty()
)

// BuildAccount constructs a Account from a AccountSpec.
func BuildAccount(s specta.Source, spec AccountSpec) showcase.Account {
	user := spec.User.GetWithGenerator(s, "User", AccountUserGenerator)
	status := spec.Status.GetWithGenerator(s, "Status", AccountStatusGenerator)
	return showcase.NewAccount(user, status)
}

// WithAccountUser sets the User parameter to a literal value.
func WithAccountUser(v showcase.User) specta.Opt[AccountSpec] {
	return specta.SetLit(func(s *AccountSpec, m specta.Maybe[showcase.User]) { s.User = m }, v)
}

// WithAccountUserFromGenerator sets the User parameter using a Generator.
func WithAccountUserFromGenerator(gen specta.Generator[showcase.User]) specta.Opt[AccountSpec] {
	return func(s *AccountSpec) {
		s.User = specta.Some(gen)
	}
}

// WithAccountStatus sets the Status parameter to a literal value.
func WithAccountStatus(v string) specta.Opt[AccountSpec] {
	return specta.SetLit(func(s *AccountSpec, m specta.Maybe[string]) { s.Status = m }, v)
}

// WithAccountStatusFromGenerator sets the Status parameter using a Generator.
func WithAccountStatusFromGenerator(gen specta.Generator[string]) specta.Opt[AccountSpec] {
	return func(s *AccountSpec) {
		s.Status = specta.Some(gen)
	}
}
