// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
package spec

import (
	testgen "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// AccountSpec is the low-level specification for building Account instances.
// Most users should use AccountRecipe from the parent factory package instead.
type AccountSpec struct {
	User   testgen.Maybe[showcase.User]
	Status testgen.Maybe[string]
}

// NewAccountSpec creates a new AccountSpec with all fields unset.
func NewAccountSpec() AccountSpec { return AccountSpec{} }

// NewAccountFactory creates a new SpecFactory for Account.
func NewAccountFactory(p testgen.Primitives) *testgen.SpecFactory[showcase.Account, AccountSpec] {
	return testgen.NewSpecFactory(p, NewAccountSpec, BuildAccount)
}

// Default parameter providers.
var (
	AccountDefaultUser   = testgen.FromSpec(BuildUser, NewUserSpec)
	AccountDefaultStatus = func(p testgen.Primitives) string { return p.StringWith("status_") }
)

// BuildAccount constructs an Account from an AccountSpec.
func BuildAccount(p testgen.Primitives, s AccountSpec) showcase.Account {
	user := s.User.Get(p, AccountDefaultUser)
	status := s.Status.Get(p, AccountDefaultStatus)
	return showcase.NewAccount(user, status)
}

// WithAccountUser sets the User parameter to a literal value.
func WithAccountUser(v showcase.User) testgen.Opt[AccountSpec] {
	return testgen.SetLit(func(s *AccountSpec, m testgen.Maybe[showcase.User]) { s.User = m }, v)
}

// WithAccountUserFromProvider sets the User parameter using a Provider (evaluated lazily).
func WithAccountUserFromProvider(prov testgen.Provider[showcase.User]) testgen.Opt[AccountSpec] {
	return testgen.SetWith(
		func(s *AccountSpec, m testgen.Maybe[showcase.User]) { s.User = m },
		prov,
	)
}

// WithAccountStatus sets the Status parameter to a literal value.
func WithAccountStatus(v string) testgen.Opt[AccountSpec] {
	return testgen.SetLit(func(s *AccountSpec, m testgen.Maybe[string]) { s.Status = m }, v)
}
