// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewAddressSpec()
//	opts := []specta.Opt[AddressSpec]{
//
//
//		WithAddressStreet("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildAddress(specta.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewAddressFactory(specta.New())
//
//
//	result := factory.Make(WithAddressStreet("example"))
package spec

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// AddressSpec is the low-level specification for building Address instances.
// Most users should use AddressRecipe from the parent factory package instead.
type AddressSpec struct {
	Street  specta.Maybe[string]
	City    specta.Maybe[string]
	State   specta.Maybe[string]
	ZipCode specta.Maybe[string]
	Country specta.Maybe[string]
}

// NewAddressSpec creates a new AddressSpec with all fields unset.
func NewAddressSpec() AddressSpec { return AddressSpec{} }

// NewAddressFactory creates a new SpecFactory for Address.
func NewAddressFactory(p specta.Primitives) *specta.SpecFactory[showcase.Address, AddressSpec] {
	return specta.NewSpecFactory(p, NewAddressSpec, BuildAddress)
}

// Default field providers.
var (
	AddressDefaultStreet  = func(p specta.Primitives) string { return p.StringWith("street_") }
	AddressDefaultCity    = func(p specta.Primitives) string { return p.StringWith("city_") }
	AddressDefaultState   = func(p specta.Primitives) string { return p.StringWith("state_") }
	AddressDefaultZipCode = func(p specta.Primitives) string { return p.StringWith("zipcode_") }
	AddressDefaultCountry = func(p specta.Primitives) string { return p.StringWith("country_") }
)

// BuildAddress constructs a Address from a AddressSpec.
func BuildAddress(p specta.Primitives, s AddressSpec) showcase.Address {
	street := s.Street.Get(p, AddressDefaultStreet)
	city := s.City.Get(p, AddressDefaultCity)
	state := s.State.Get(p, AddressDefaultState)
	zipCode := s.ZipCode.Get(p, AddressDefaultZipCode)
	country := s.Country.Get(p, AddressDefaultCountry)
	return showcase.Address{
		Street:  street,
		City:    city,
		State:   state,
		ZipCode: zipCode,
		Country: country,
	}
}

// WithAddressStreet sets the Street field to a literal value.
func WithAddressStreet(v string) specta.Opt[AddressSpec] {
	return specta.SetLit(func(s *AddressSpec, m specta.Maybe[string]) { s.Street = m }, v)
}

// WithAddressCity sets the City field to a literal value.
func WithAddressCity(v string) specta.Opt[AddressSpec] {
	return specta.SetLit(func(s *AddressSpec, m specta.Maybe[string]) { s.City = m }, v)
}

// WithAddressState sets the State field to a literal value.
func WithAddressState(v string) specta.Opt[AddressSpec] {
	return specta.SetLit(func(s *AddressSpec, m specta.Maybe[string]) { s.State = m }, v)
}

// WithAddressZipCode sets the ZipCode field to a literal value.
func WithAddressZipCode(v string) specta.Opt[AddressSpec] {
	return specta.SetLit(func(s *AddressSpec, m specta.Maybe[string]) { s.ZipCode = m }, v)
}

// WithAddressCountry sets the Country field to a literal value.
func WithAddressCountry(v string) specta.Opt[AddressSpec] {
	return specta.SetLit(func(s *AddressSpec, m specta.Maybe[string]) { s.Country = m }, v)
}
