// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewBankAccountSpec()
//	opts := []specta.Opt[BankAccountSpec]{
//
//
//		WithBankAccountName("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildBankAccount(specta.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewBankAccountFactory(specta.New())
//
//
//	result := factory.Make(WithBankAccountName("example"))
package spec

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// BankAccountSpec is the low-level specification for building BankAccount instances.
// Most users should use BankAccountRecipe from the parent factory package instead.
type BankAccountSpec struct {
	Name    specta.Maybe[string]
	Balance specta.Maybe[int]
}

// NewBankAccountSpec creates a new BankAccountSpec with all fields unset.
func NewBankAccountSpec() BankAccountSpec { return BankAccountSpec{} }

// NewBankAccountFactory creates a new SpecFactory for BankAccount.
func NewBankAccountFactory(s specta.Source) *specta.SpecFactory[showcase.BankAccount, BankAccountSpec] {
	return specta.NewSpecFactory(s, NewBankAccountSpec, BuildBankAccount)
}

// Default parameter generators.
var (
	BankAccountNameGenerator    = specta.String().ExampleHint("name_").NonEmpty()
	BankAccountBalanceGenerator = specta.Map(specta.Int(), func(v int64) int { return int(v) })
)

// BuildBankAccount constructs a BankAccount from a BankAccountSpec.
func BuildBankAccount(s specta.Source, spec BankAccountSpec) showcase.BankAccount {
	name := spec.Name.GetWithGenerator(s, "Name", BankAccountNameGenerator)
	balance := spec.Balance.GetWithGenerator(s, "Balance", BankAccountBalanceGenerator)
	return showcase.NewBankAccount(name, balance)
}

// WithBankAccountName sets the Name parameter to a literal value.
func WithBankAccountName(v string) specta.Opt[BankAccountSpec] {
	return specta.SetLit(func(s *BankAccountSpec, m specta.Maybe[string]) { s.Name = m }, v)
}

// WithBankAccountNameFromGenerator sets the Name parameter using a Generator.
func WithBankAccountNameFromGenerator(gen specta.Generator[string]) specta.Opt[BankAccountSpec] {
	return func(s *BankAccountSpec) {
		s.Name = specta.Some(gen)
	}
}

// WithBankAccountBalance sets the Balance parameter to a literal value.
func WithBankAccountBalance(v int) specta.Opt[BankAccountSpec] {
	return specta.SetLit(func(s *BankAccountSpec, m specta.Maybe[int]) { s.Balance = m }, v)
}

// WithBankAccountBalanceFromGenerator sets the Balance parameter using a Generator.
func WithBankAccountBalanceFromGenerator(gen specta.Generator[int]) specta.Opt[BankAccountSpec] {
	return func(s *BankAccountSpec) {
		s.Balance = specta.Some(gen)
	}
}
