// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package spec

import (
	testgen "github.com/james-w/gomatchers"
	"github.com/james-w/gomatchers/showcase"
)

// BankAccountSpec is the low-level specification for building BankAccount instances.
// Most users should use BankAccountRecipe from the parent factory package instead.
type BankAccountSpec struct {
	Name    testgen.Maybe[string]
	Balance testgen.Maybe[int]
}

// NewBankAccountSpec creates a new BankAccountSpec with all fields unset.
func NewBankAccountSpec() BankAccountSpec { return BankAccountSpec{} }

// NewBankAccountFactory creates a new SpecFactory for BankAccount.
func NewBankAccountFactory(p testgen.Primitives) *testgen.SpecFactory[showcase.BankAccount, BankAccountSpec] {
	return testgen.NewSpecFactory(p, NewBankAccountSpec, BuildBankAccount)
}

// Default parameter providers.
var (
	BankAccountDefaultName    = func(p testgen.Primitives) string { return p.StringWith("name_") }
	BankAccountDefaultBalance = func(p testgen.Primitives) int { return int(p.Int()) }
)

// BuildBankAccount constructs a BankAccount from a BankAccountSpec.
func BuildBankAccount(p testgen.Primitives, s BankAccountSpec) showcase.BankAccount {
	name := s.Name.Get(p, BankAccountDefaultName)
	balance := s.Balance.Get(p, BankAccountDefaultBalance)
	return showcase.NewBankAccount(name, balance)
}

// WithBankAccountName sets the Name parameter to a literal value.
func WithBankAccountName(v string) testgen.Opt[BankAccountSpec] {
	return testgen.SetLit(func(s *BankAccountSpec, m testgen.Maybe[string]) { s.Name = m }, v)
}

// WithBankAccountBalance sets the Balance parameter to a literal value.
func WithBankAccountBalance(v int) testgen.Opt[BankAccountSpec] {
	return testgen.SetLit(func(s *BankAccountSpec, m testgen.Maybe[int]) { s.Balance = m }, v)
}
