// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewBlogPostSpec()
//	opts := []specta.Opt[BlogPostSpec]{
//
//
//		WithBlogPostID("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildBlogPost(specta.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewBlogPostFactory(specta.New())
//
//
//	result := factory.Make(WithBlogPostID("example"))
package spec

import (
	"time"

	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// BlogPostSpec is the low-level specification for building BlogPost instances.
// Most users should use BlogPostRecipe from the parent factory package instead.
type BlogPostSpec struct {
	ID          specta.Maybe[string]
	Title       specta.Maybe[string]
	Content     specta.Maybe[string]
	Author      specta.Maybe[showcase.User]
	Published   specta.Maybe[bool]
	PublishedAt specta.Maybe[time.Time]
	CreatedAt   specta.Maybe[time.Time]
	UpdatedAt   specta.Maybe[time.Time]
}

// NewBlogPostSpec creates a new BlogPostSpec with all fields unset.
func NewBlogPostSpec() BlogPostSpec { return BlogPostSpec{} }

// NewBlogPostFactory creates a new SpecFactory for BlogPost.
func NewBlogPostFactory(p specta.Primitives) *specta.SpecFactory[showcase.BlogPost, BlogPostSpec] {
	return specta.NewSpecFactory(p, NewBlogPostSpec, BuildBlogPost)
}

// Default field providers.
var (
	BlogPostDefaultID          = func(p specta.Primitives) string { return p.ID() }
	BlogPostDefaultTitle       = func(p specta.Primitives) string { return p.StringWith("title_") }
	BlogPostDefaultContent     = func(p specta.Primitives) string { return p.StringWith("content_") }
	BlogPostDefaultAuthor      = specta.FromSpec(BuildUser, NewUserSpec)
	BlogPostDefaultPublished   = func(p specta.Primitives) bool { return p.Bool() }
	BlogPostDefaultPublishedAt = func(p specta.Primitives) time.Time { return p.Time() }
	BlogPostDefaultCreatedAt   = func(p specta.Primitives) time.Time { return p.Time() }
	BlogPostDefaultUpdatedAt   = func(p specta.Primitives) time.Time { return p.Time() }
)

// BuildBlogPost constructs a BlogPost from a BlogPostSpec.
func BuildBlogPost(p specta.Primitives, s BlogPostSpec) showcase.BlogPost {
	iD := s.ID.Get(p, BlogPostDefaultID)
	title := s.Title.Get(p, BlogPostDefaultTitle)
	content := s.Content.Get(p, BlogPostDefaultContent)
	author := s.Author.Get(p, BlogPostDefaultAuthor)
	published := s.Published.Get(p, BlogPostDefaultPublished)
	publishedAt := s.PublishedAt.Get(p, BlogPostDefaultPublishedAt)
	createdAt := s.CreatedAt.Get(p, BlogPostDefaultCreatedAt)
	updatedAt := s.UpdatedAt.Get(p, BlogPostDefaultUpdatedAt)
	return showcase.BlogPost{
		ID:          iD,
		Title:       title,
		Content:     content,
		Author:      author,
		Published:   published,
		PublishedAt: publishedAt,
		CreatedAt:   createdAt,
		UpdatedAt:   updatedAt,
	}
}

// WithBlogPostID sets the ID field to a literal value.
func WithBlogPostID(v string) specta.Opt[BlogPostSpec] {
	return specta.SetLit(func(s *BlogPostSpec, m specta.Maybe[string]) { s.ID = m }, v)
}

// WithBlogPostTitle sets the Title field to a literal value.
func WithBlogPostTitle(v string) specta.Opt[BlogPostSpec] {
	return specta.SetLit(func(s *BlogPostSpec, m specta.Maybe[string]) { s.Title = m }, v)
}

// WithBlogPostContent sets the Content field to a literal value.
func WithBlogPostContent(v string) specta.Opt[BlogPostSpec] {
	return specta.SetLit(func(s *BlogPostSpec, m specta.Maybe[string]) { s.Content = m }, v)
}

// WithBlogPostAuthor sets the Author field to a literal value.
func WithBlogPostAuthor(v showcase.User) specta.Opt[BlogPostSpec] {
	return specta.SetLit(func(s *BlogPostSpec, m specta.Maybe[showcase.User]) { s.Author = m }, v)
}

// WithBlogPostAuthorFromProvider sets the Author field using a Provider (evaluated lazily).
func WithBlogPostAuthorFromProvider(prov specta.Provider[showcase.User]) specta.Opt[BlogPostSpec] {
	return specta.SetWith(
		func(s *BlogPostSpec, m specta.Maybe[showcase.User]) { s.Author = m },
		prov,
	)
}

// WithBlogPostPublished sets the Published field to a literal value.
func WithBlogPostPublished(v bool) specta.Opt[BlogPostSpec] {
	return specta.SetLit(func(s *BlogPostSpec, m specta.Maybe[bool]) { s.Published = m }, v)
}

// WithBlogPostPublishedAt sets the PublishedAt field to a literal value.
func WithBlogPostPublishedAt(v time.Time) specta.Opt[BlogPostSpec] {
	return specta.SetLit(func(s *BlogPostSpec, m specta.Maybe[time.Time]) { s.PublishedAt = m }, v)
}

// WithBlogPostCreatedAt sets the CreatedAt field to a literal value.
func WithBlogPostCreatedAt(v time.Time) specta.Opt[BlogPostSpec] {
	return specta.SetLit(func(s *BlogPostSpec, m specta.Maybe[time.Time]) { s.CreatedAt = m }, v)
}

// WithBlogPostUpdatedAt sets the UpdatedAt field to a literal value.
func WithBlogPostUpdatedAt(v time.Time) specta.Opt[BlogPostSpec] {
	return specta.SetLit(func(s *BlogPostSpec, m specta.Maybe[time.Time]) { s.UpdatedAt = m }, v)
}
