// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewBlogPostSpec()
//	opts := []specta.Opt[BlogPostSpec]{
//
//
//		WithBlogPostID("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildBlogPost(specta.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewBlogPostFactory(specta.New())
//
//
//	result := factory.Make(WithBlogPostID("example"))
package spec

import (
	"time"

	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// BlogPostSpec is the low-level specification for building BlogPost instances.
// Most users should use BlogPostRecipe from the parent factory package instead.
type BlogPostSpec struct {
	ID          specta.Maybe[string]
	Title       specta.Maybe[string]
	Content     specta.Maybe[string]
	Author      specta.Maybe[showcase.User]
	Published   specta.Maybe[bool]
	PublishedAt specta.Maybe[time.Time]
	CreatedAt   specta.Maybe[time.Time]
	UpdatedAt   specta.Maybe[time.Time]
}

// NewBlogPostSpec creates a new BlogPostSpec with all fields unset.
func NewBlogPostSpec() BlogPostSpec { return BlogPostSpec{} }

// NewBlogPostFactory creates a new SpecFactory for BlogPost.
func NewBlogPostFactory(s specta.Source) *specta.SpecFactory[showcase.BlogPost, BlogPostSpec] {
	return specta.NewSpecFactory(s, NewBlogPostSpec, BuildBlogPost)
}

// Default field generators.
var (
	BlogPostIDGenerator          specta.Generator[string]        = specta.String().ExampleHint("id_")
	BlogPostTitleGenerator       specta.Generator[string]        = specta.String().ExampleHint("title_")
	BlogPostContentGenerator     specta.Generator[string]        = specta.String().ExampleHint("content_")
	BlogPostAuthorGenerator      specta.Generator[showcase.User] = specta.GeneratorFromProvider(specta.FromSpec(BuildUser, NewUserSpec))
	BlogPostPublishedGenerator   specta.Generator[bool]          = specta.Bool()
	BlogPostPublishedAtGenerator specta.Generator[time.Time]     = specta.Time()
	BlogPostCreatedAtGenerator   specta.Generator[time.Time]     = specta.Time()
	BlogPostUpdatedAtGenerator   specta.Generator[time.Time]     = specta.Time()
)

// BuildBlogPost constructs a BlogPost from a BlogPostSpec.
func BuildBlogPost(s specta.Source, spec BlogPostSpec) showcase.BlogPost {
	iD := spec.ID.GetWithGenerator(s, "ID", BlogPostIDGenerator)
	title := spec.Title.GetWithGenerator(s, "Title", BlogPostTitleGenerator)
	content := spec.Content.GetWithGenerator(s, "Content", BlogPostContentGenerator)
	author := spec.Author.GetWithGenerator(s, "Author", BlogPostAuthorGenerator)
	published := spec.Published.GetWithGenerator(s, "Published", BlogPostPublishedGenerator)
	publishedAt := spec.PublishedAt.GetWithGenerator(s, "PublishedAt", BlogPostPublishedAtGenerator)
	createdAt := spec.CreatedAt.GetWithGenerator(s, "CreatedAt", BlogPostCreatedAtGenerator)
	updatedAt := spec.UpdatedAt.GetWithGenerator(s, "UpdatedAt", BlogPostUpdatedAtGenerator)
	return showcase.BlogPost{
		ID:          iD,
		Title:       title,
		Content:     content,
		Author:      author,
		Published:   published,
		PublishedAt: publishedAt,
		CreatedAt:   createdAt,
		UpdatedAt:   updatedAt,
	}
}

// WithBlogPostID sets the ID field to a literal value.
func WithBlogPostID(v string) specta.Opt[BlogPostSpec] {
	return specta.SetLit(func(s *BlogPostSpec, m specta.Maybe[string]) { s.ID = m }, v)
}

// WithBlogPostIDFromGenerator sets the ID field using a Generator.
func WithBlogPostIDFromGenerator(gen specta.Generator[string]) specta.Opt[BlogPostSpec] {
	prov := specta.ProviderFromGenerator(gen, "ID")
	return specta.SetWith(
		func(s *BlogPostSpec, m specta.Maybe[string]) { s.ID = m },
		prov,
	)
}

// WithBlogPostTitle sets the Title field to a literal value.
func WithBlogPostTitle(v string) specta.Opt[BlogPostSpec] {
	return specta.SetLit(func(s *BlogPostSpec, m specta.Maybe[string]) { s.Title = m }, v)
}

// WithBlogPostTitleFromGenerator sets the Title field using a Generator.
func WithBlogPostTitleFromGenerator(gen specta.Generator[string]) specta.Opt[BlogPostSpec] {
	prov := specta.ProviderFromGenerator(gen, "Title")
	return specta.SetWith(
		func(s *BlogPostSpec, m specta.Maybe[string]) { s.Title = m },
		prov,
	)
}

// WithBlogPostContent sets the Content field to a literal value.
func WithBlogPostContent(v string) specta.Opt[BlogPostSpec] {
	return specta.SetLit(func(s *BlogPostSpec, m specta.Maybe[string]) { s.Content = m }, v)
}

// WithBlogPostContentFromGenerator sets the Content field using a Generator.
func WithBlogPostContentFromGenerator(gen specta.Generator[string]) specta.Opt[BlogPostSpec] {
	prov := specta.ProviderFromGenerator(gen, "Content")
	return specta.SetWith(
		func(s *BlogPostSpec, m specta.Maybe[string]) { s.Content = m },
		prov,
	)
}

// WithBlogPostAuthor sets the Author field to a literal value.
func WithBlogPostAuthor(v showcase.User) specta.Opt[BlogPostSpec] {
	return specta.SetLit(func(s *BlogPostSpec, m specta.Maybe[showcase.User]) { s.Author = m }, v)
}

// WithBlogPostAuthorFromGenerator sets the Author field using a Generator.
func WithBlogPostAuthorFromGenerator(gen specta.Generator[showcase.User]) specta.Opt[BlogPostSpec] {
	prov := specta.ProviderFromGenerator(gen, "Author")
	return specta.SetWith(
		func(s *BlogPostSpec, m specta.Maybe[showcase.User]) { s.Author = m },
		prov,
	)
}

// WithBlogPostAuthorFromProvider sets the Author field using a Provider (evaluated lazily).
func WithBlogPostAuthorFromProvider(prov specta.Provider[showcase.User]) specta.Opt[BlogPostSpec] {
	return specta.SetWith(
		func(s *BlogPostSpec, m specta.Maybe[showcase.User]) { s.Author = m },
		prov,
	)
}

// WithBlogPostPublished sets the Published field to a literal value.
func WithBlogPostPublished(v bool) specta.Opt[BlogPostSpec] {
	return specta.SetLit(func(s *BlogPostSpec, m specta.Maybe[bool]) { s.Published = m }, v)
}

// WithBlogPostPublishedFromGenerator sets the Published field using a Generator.
func WithBlogPostPublishedFromGenerator(gen specta.Generator[bool]) specta.Opt[BlogPostSpec] {
	prov := specta.ProviderFromGenerator(gen, "Published")
	return specta.SetWith(
		func(s *BlogPostSpec, m specta.Maybe[bool]) { s.Published = m },
		prov,
	)
}

// WithBlogPostPublishedAt sets the PublishedAt field to a literal value.
func WithBlogPostPublishedAt(v time.Time) specta.Opt[BlogPostSpec] {
	return specta.SetLit(func(s *BlogPostSpec, m specta.Maybe[time.Time]) { s.PublishedAt = m }, v)
}

// WithBlogPostPublishedAtFromGenerator sets the PublishedAt field using a Generator.
func WithBlogPostPublishedAtFromGenerator(gen specta.Generator[time.Time]) specta.Opt[BlogPostSpec] {
	prov := specta.ProviderFromGenerator(gen, "PublishedAt")
	return specta.SetWith(
		func(s *BlogPostSpec, m specta.Maybe[time.Time]) { s.PublishedAt = m },
		prov,
	)
}

// WithBlogPostCreatedAt sets the CreatedAt field to a literal value.
func WithBlogPostCreatedAt(v time.Time) specta.Opt[BlogPostSpec] {
	return specta.SetLit(func(s *BlogPostSpec, m specta.Maybe[time.Time]) { s.CreatedAt = m }, v)
}

// WithBlogPostCreatedAtFromGenerator sets the CreatedAt field using a Generator.
func WithBlogPostCreatedAtFromGenerator(gen specta.Generator[time.Time]) specta.Opt[BlogPostSpec] {
	prov := specta.ProviderFromGenerator(gen, "CreatedAt")
	return specta.SetWith(
		func(s *BlogPostSpec, m specta.Maybe[time.Time]) { s.CreatedAt = m },
		prov,
	)
}

// WithBlogPostUpdatedAt sets the UpdatedAt field to a literal value.
func WithBlogPostUpdatedAt(v time.Time) specta.Opt[BlogPostSpec] {
	return specta.SetLit(func(s *BlogPostSpec, m specta.Maybe[time.Time]) { s.UpdatedAt = m }, v)
}

// WithBlogPostUpdatedAtFromGenerator sets the UpdatedAt field using a Generator.
func WithBlogPostUpdatedAtFromGenerator(gen specta.Generator[time.Time]) specta.Opt[BlogPostSpec] {
	prov := specta.ProviderFromGenerator(gen, "UpdatedAt")
	return specta.SetWith(
		func(s *BlogPostSpec, m specta.Maybe[time.Time]) { s.UpdatedAt = m },
		prov,
	)
}
