// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package spec

import (
	"time"

	testgen "github.com/james-w/gomatchers"
	"github.com/james-w/gomatchers/showcase"
)

// BlogPostSpec is the low-level specification for building BlogPost instances.
// Most users should use BlogPostRecipe from the parent factory package instead.
type BlogPostSpec struct {
	ID          testgen.Maybe[string]
	Title       testgen.Maybe[string]
	Content     testgen.Maybe[string]
	Author      testgen.Maybe[showcase.User]
	Published   testgen.Maybe[bool]
	PublishedAt testgen.Maybe[time.Time]
	CreatedAt   testgen.Maybe[time.Time]
	UpdatedAt   testgen.Maybe[time.Time]
}

// NewBlogPostSpec creates a new BlogPostSpec with all fields unset.
func NewBlogPostSpec() BlogPostSpec { return BlogPostSpec{} }

// NewBlogPostFactory creates a new SpecFactory for BlogPost.
func NewBlogPostFactory(p testgen.Primitives) *testgen.SpecFactory[showcase.BlogPost, BlogPostSpec] {
	return testgen.NewSpecFactory(p, NewBlogPostSpec, BuildBlogPost)
}

// Default field providers.
var (
	BlogPostDefaultID          = func(p testgen.Primitives) string { return p.ID() }
	BlogPostDefaultTitle       = func(p testgen.Primitives) string { return p.StringWith("title_") }
	BlogPostDefaultContent     = func(p testgen.Primitives) string { return p.StringWith("content_") }
	BlogPostDefaultAuthor      = testgen.FromSpec(BuildUser, NewUserSpec)
	BlogPostDefaultPublished   = func(p testgen.Primitives) bool { return p.Bool() }
	BlogPostDefaultPublishedAt = func(p testgen.Primitives) time.Time { return p.Time() }
	BlogPostDefaultCreatedAt   = func(p testgen.Primitives) time.Time { return p.Time() }
	BlogPostDefaultUpdatedAt   = func(p testgen.Primitives) time.Time { return p.Time() }
)

// BuildBlogPost constructs a BlogPost from a BlogPostSpec.
func BuildBlogPost(p testgen.Primitives, s BlogPostSpec) showcase.BlogPost {
	iD := s.ID.Get(p, BlogPostDefaultID)
	title := s.Title.Get(p, BlogPostDefaultTitle)
	content := s.Content.Get(p, BlogPostDefaultContent)
	author := s.Author.Get(p, BlogPostDefaultAuthor)
	published := s.Published.Get(p, BlogPostDefaultPublished)
	publishedAt := s.PublishedAt.Get(p, BlogPostDefaultPublishedAt)
	createdAt := s.CreatedAt.Get(p, BlogPostDefaultCreatedAt)
	updatedAt := s.UpdatedAt.Get(p, BlogPostDefaultUpdatedAt)
	return showcase.BlogPost{
		ID:          iD,
		Title:       title,
		Content:     content,
		Author:      author,
		Published:   published,
		PublishedAt: publishedAt,
		CreatedAt:   createdAt,
		UpdatedAt:   updatedAt,
	}
}

// WithBlogPostID sets the ID field to a literal value.
func WithBlogPostID(v string) testgen.Opt[BlogPostSpec] {
	return testgen.SetLit(func(s *BlogPostSpec, m testgen.Maybe[string]) { s.ID = m }, v)
}

// WithBlogPostTitle sets the Title field to a literal value.
func WithBlogPostTitle(v string) testgen.Opt[BlogPostSpec] {
	return testgen.SetLit(func(s *BlogPostSpec, m testgen.Maybe[string]) { s.Title = m }, v)
}

// WithBlogPostContent sets the Content field to a literal value.
func WithBlogPostContent(v string) testgen.Opt[BlogPostSpec] {
	return testgen.SetLit(func(s *BlogPostSpec, m testgen.Maybe[string]) { s.Content = m }, v)
}

// WithBlogPostAuthor sets the Author field to a literal value.
func WithBlogPostAuthor(v showcase.User) testgen.Opt[BlogPostSpec] {
	return testgen.SetLit(func(s *BlogPostSpec, m testgen.Maybe[showcase.User]) { s.Author = m }, v)
}

// WithBlogPostAuthorFromProvider sets the Author field using a Provider (evaluated lazily).
func WithBlogPostAuthorFromProvider(prov testgen.Provider[showcase.User]) testgen.Opt[BlogPostSpec] {
	return testgen.SetWith(
		func(s *BlogPostSpec, m testgen.Maybe[showcase.User]) { s.Author = m },
		prov,
	)
}

// WithBlogPostPublished sets the Published field to a literal value.
func WithBlogPostPublished(v bool) testgen.Opt[BlogPostSpec] {
	return testgen.SetLit(func(s *BlogPostSpec, m testgen.Maybe[bool]) { s.Published = m }, v)
}

// WithBlogPostPublishedAt sets the PublishedAt field to a literal value.
func WithBlogPostPublishedAt(v time.Time) testgen.Opt[BlogPostSpec] {
	return testgen.SetLit(func(s *BlogPostSpec, m testgen.Maybe[time.Time]) { s.PublishedAt = m }, v)
}

// WithBlogPostCreatedAt sets the CreatedAt field to a literal value.
func WithBlogPostCreatedAt(v time.Time) testgen.Opt[BlogPostSpec] {
	return testgen.SetLit(func(s *BlogPostSpec, m testgen.Maybe[time.Time]) { s.CreatedAt = m }, v)
}

// WithBlogPostUpdatedAt sets the UpdatedAt field to a literal value.
func WithBlogPostUpdatedAt(v time.Time) testgen.Opt[BlogPostSpec] {
	return testgen.SetLit(func(s *BlogPostSpec, m testgen.Maybe[time.Time]) { s.UpdatedAt = m }, v)
}
