// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewCommentSpec()
//	opts := []specta.Opt[CommentSpec]{
//
//
//		WithCommentID("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildComment(specta.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewCommentFactory(specta.New())
//
//
//	result := factory.Make(WithCommentID("example"))
package spec

import (
	"time"

	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// CommentSpec is the low-level specification for building Comment instances.
// Most users should use CommentRecipe from the parent factory package instead.
type CommentSpec struct {
	ID        specta.Maybe[string]
	Post      specta.Maybe[showcase.BlogPost]
	Author    specta.Maybe[showcase.User]
	Content   specta.Maybe[string]
	CreatedAt specta.Maybe[time.Time]
}

// NewCommentSpec creates a new CommentSpec with all fields unset.
func NewCommentSpec() CommentSpec { return CommentSpec{} }

// NewCommentFactory creates a new SpecFactory for Comment.
func NewCommentFactory(s specta.Source) *specta.SpecFactory[showcase.Comment, CommentSpec] {
	return specta.NewSpecFactory(s, NewCommentSpec, BuildComment)
}

// Default field providers.
var (
	CommentDefaultID        = func(s specta.Source) string { return specta.String().ExampleHint("id_").Draw(s, "ID") }
	CommentDefaultPost      = specta.FromSpec(BuildBlogPost, NewBlogPostSpec)
	CommentDefaultAuthor    = specta.FromSpec(BuildUser, NewUserSpec)
	CommentDefaultContent   = func(s specta.Source) string { return specta.String().ExampleHint("content_").Draw(s, "Content") }
	CommentDefaultCreatedAt = func(s specta.Source) time.Time { return specta.Time().Draw(s, "CreatedAt") }
)

// BuildComment constructs a Comment from a CommentSpec.
func BuildComment(s specta.Source, spec CommentSpec) showcase.Comment {
	iD := spec.ID.Get(s, CommentDefaultID)
	post := spec.Post.Get(s, CommentDefaultPost)
	author := spec.Author.Get(s, CommentDefaultAuthor)
	content := spec.Content.Get(s, CommentDefaultContent)
	createdAt := spec.CreatedAt.Get(s, CommentDefaultCreatedAt)
	return showcase.Comment{
		ID:        iD,
		Post:      post,
		Author:    author,
		Content:   content,
		CreatedAt: createdAt,
	}
}

// WithCommentID sets the ID field to a literal value.
func WithCommentID(v string) specta.Opt[CommentSpec] {
	return specta.SetLit(func(s *CommentSpec, m specta.Maybe[string]) { s.ID = m }, v)
}

// WithCommentPost sets the Post field to a literal value.
func WithCommentPost(v showcase.BlogPost) specta.Opt[CommentSpec] {
	return specta.SetLit(func(s *CommentSpec, m specta.Maybe[showcase.BlogPost]) { s.Post = m }, v)
}

// WithCommentPostFromProvider sets the Post field using a Provider (evaluated lazily).
func WithCommentPostFromProvider(prov specta.Provider[showcase.BlogPost]) specta.Opt[CommentSpec] {
	return specta.SetWith(
		func(s *CommentSpec, m specta.Maybe[showcase.BlogPost]) { s.Post = m },
		prov,
	)
}

// WithCommentAuthor sets the Author field to a literal value.
func WithCommentAuthor(v showcase.User) specta.Opt[CommentSpec] {
	return specta.SetLit(func(s *CommentSpec, m specta.Maybe[showcase.User]) { s.Author = m }, v)
}

// WithCommentAuthorFromProvider sets the Author field using a Provider (evaluated lazily).
func WithCommentAuthorFromProvider(prov specta.Provider[showcase.User]) specta.Opt[CommentSpec] {
	return specta.SetWith(
		func(s *CommentSpec, m specta.Maybe[showcase.User]) { s.Author = m },
		prov,
	)
}

// WithCommentContent sets the Content field to a literal value.
func WithCommentContent(v string) specta.Opt[CommentSpec] {
	return specta.SetLit(func(s *CommentSpec, m specta.Maybe[string]) { s.Content = m }, v)
}

// WithCommentCreatedAt sets the CreatedAt field to a literal value.
func WithCommentCreatedAt(v time.Time) specta.Opt[CommentSpec] {
	return specta.SetLit(func(s *CommentSpec, m specta.Maybe[time.Time]) { s.CreatedAt = m }, v)
}
