// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewEmailSpec()
//	opts := []specta.Opt[EmailSpec]{
//
//
//		WithEmailAddress("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildEmail(specta.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewEmailFactory(specta.New())
//
//
//	result := factory.Make(WithEmailAddress("example"))
package spec

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// EmailSpec is the low-level specification for building Email instances.
// Most users should use EmailRecipe from the parent factory package instead.
type EmailSpec struct {
	Address specta.Maybe[string]
}

// NewEmailSpec creates a new EmailSpec with all fields unset.
func NewEmailSpec() EmailSpec { return EmailSpec{} }

// NewEmailFactory creates a new SpecFactory for Email.
func NewEmailFactory(s specta.Source) *specta.SpecFactory[showcase.Email, EmailSpec] {
	// Wrap error-returning constructor - panic on error for test factories
	wrappedBuild := func(s specta.Source, spec EmailSpec) showcase.Email {
		result, err := BuildEmail(s, spec)
		if err != nil {
			panic("BuildEmail failed: " + err.Error())
		}
		return result
	}
	return specta.NewSpecFactory(s, NewEmailSpec, wrappedBuild)
}

// Default parameter providers.
var (
	EmailDefaultAddress = func(s specta.Source) string {
		return specta.String().ExampleHint("user_").Draw(s, "user") + "@example.com"
	}
)

// BuildEmail constructs a Email from a EmailSpec.
func BuildEmail(s specta.Source, spec EmailSpec) (showcase.Email, error) {
	address := spec.Address.Get(s, EmailDefaultAddress)
	return showcase.NewEmail(address)
}

// WithEmailAddress sets the Address parameter to a literal value.
func WithEmailAddress(v string) specta.Opt[EmailSpec] {
	return specta.SetLit(func(s *EmailSpec, m specta.Maybe[string]) { s.Address = m }, v)
}
