// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewMemberSpec()
//	opts := []testgen.Opt[MemberSpec]{
//
//
//		WithMemberID("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildMember(testgen.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewMemberFactory(testgen.New())
//
//
//	result := factory.Make(WithMemberID("example"))
package spec

import (
	testgen "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// MemberSpec is the low-level specification for building Member instances.
// Most users should use MemberRecipe from the parent factory package instead.
type MemberSpec struct {
	ID     testgen.Maybe[string]
	Name   testgen.Maybe[string]
	TeamID testgen.Maybe[string]
	Team   testgen.Maybe[*showcase.Team]
}

// NewMemberSpec creates a new MemberSpec with all fields unset.
func NewMemberSpec() MemberSpec { return MemberSpec{} }

// NewMemberFactory creates a new SpecFactory for Member.
func NewMemberFactory(p testgen.Primitives) *testgen.SpecFactory[showcase.Member, MemberSpec] {
	return testgen.NewSpecFactory(p, NewMemberSpec, BuildMember)
}

// Default field providers.
var (
	MemberDefaultID     = func(p testgen.Primitives) string { return p.ID() }
	MemberDefaultName   = func(p testgen.Primitives) string { return p.StringWith("name_") }
	MemberDefaultTeamID = func(p testgen.Primitives) string { return p.ID() }
	MemberDefaultTeam   = testgen.PtrOf(testgen.FromSpec(BuildTeam, NewTeamSpec))
)

// BuildMember constructs a Member from a MemberSpec.
func BuildMember(p testgen.Primitives, s MemberSpec) showcase.Member {
	iD := s.ID.Get(p, MemberDefaultID)
	name := s.Name.Get(p, MemberDefaultName)
	teamID := s.TeamID.Get(p, MemberDefaultTeamID)
	team := s.Team.Get(p, MemberDefaultTeam)
	return showcase.Member{
		ID:     iD,
		Name:   name,
		TeamID: teamID,
		Team:   team,
	}
}

// WithMemberID sets the ID field to a literal value.
func WithMemberID(v string) testgen.Opt[MemberSpec] {
	return testgen.SetLit(func(s *MemberSpec, m testgen.Maybe[string]) { s.ID = m }, v)
}

// WithMemberName sets the Name field to a literal value.
func WithMemberName(v string) testgen.Opt[MemberSpec] {
	return testgen.SetLit(func(s *MemberSpec, m testgen.Maybe[string]) { s.Name = m }, v)
}

// WithMemberTeamID sets the TeamID field to a literal value.
func WithMemberTeamID(v string) testgen.Opt[MemberSpec] {
	return testgen.SetLit(func(s *MemberSpec, m testgen.Maybe[string]) { s.TeamID = m }, v)
}

// WithMemberTeam sets the Team field to a literal value.
func WithMemberTeam(v *showcase.Team) testgen.Opt[MemberSpec] {
	return testgen.SetLit(func(s *MemberSpec, m testgen.Maybe[*showcase.Team]) { s.Team = m }, v)
}

// WithMemberTeamFromProvider sets the Team field using a Provider (evaluated lazily).
func WithMemberTeamFromProvider(prov testgen.Provider[*showcase.Team]) testgen.Opt[MemberSpec] {
	return testgen.SetWith(
		func(s *MemberSpec, m testgen.Maybe[*showcase.Team]) { s.Team = m },
		prov,
	)
}
