// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewMemberSpec()
//	opts := []specta.Opt[MemberSpec]{
//
//
//		WithMemberID("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildMember(specta.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewMemberFactory(specta.New())
//
//
//	result := factory.Make(WithMemberID("example"))
package spec

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// MemberSpec is the low-level specification for building Member instances.
// Most users should use MemberRecipe from the parent factory package instead.
type MemberSpec struct {
	ID     specta.Maybe[string]
	Name   specta.Maybe[string]
	TeamID specta.Maybe[string]
	Team   specta.Maybe[*showcase.Team]
}

// NewMemberSpec creates a new MemberSpec with all fields unset.
func NewMemberSpec() MemberSpec { return MemberSpec{} }

// NewMemberFactory creates a new SpecFactory for Member.
func NewMemberFactory(s specta.Source) *specta.SpecFactory[showcase.Member, MemberSpec] {
	return specta.NewSpecFactory(s, NewMemberSpec, BuildMember)
}

// Default field generators.
var (
	MemberIDGenerator     specta.Generator[string]         = specta.String().ExampleHint("id_")
	MemberNameGenerator   specta.Generator[string]         = specta.String().ExampleHint("name_")
	MemberTeamIDGenerator specta.Generator[string]         = specta.String().ExampleHint("id_")
	MemberTeamGenerator   specta.Generator[*showcase.Team] = specta.GeneratorFromProvider(specta.PtrOf(specta.FromSpec(BuildTeam, NewTeamSpec)))
)

// BuildMember constructs a Member from a MemberSpec.
func BuildMember(s specta.Source, spec MemberSpec) showcase.Member {
	iD := spec.ID.GetWithGenerator(s, "ID", MemberIDGenerator)
	name := spec.Name.GetWithGenerator(s, "Name", MemberNameGenerator)
	teamID := spec.TeamID.GetWithGenerator(s, "TeamID", MemberTeamIDGenerator)
	team := spec.Team.GetWithGenerator(s, "Team", MemberTeamGenerator)
	return showcase.Member{
		ID:     iD,
		Name:   name,
		TeamID: teamID,
		Team:   team,
	}
}

// WithMemberID sets the ID field to a literal value.
func WithMemberID(v string) specta.Opt[MemberSpec] {
	return specta.SetLit(func(s *MemberSpec, m specta.Maybe[string]) { s.ID = m }, v)
}

// WithMemberIDFromGenerator sets the ID field using a Generator.
func WithMemberIDFromGenerator(gen specta.Generator[string]) specta.Opt[MemberSpec] {
	prov := specta.ProviderFromGenerator(gen, "ID")
	return specta.SetWith(
		func(s *MemberSpec, m specta.Maybe[string]) { s.ID = m },
		prov,
	)
}

// WithMemberName sets the Name field to a literal value.
func WithMemberName(v string) specta.Opt[MemberSpec] {
	return specta.SetLit(func(s *MemberSpec, m specta.Maybe[string]) { s.Name = m }, v)
}

// WithMemberNameFromGenerator sets the Name field using a Generator.
func WithMemberNameFromGenerator(gen specta.Generator[string]) specta.Opt[MemberSpec] {
	prov := specta.ProviderFromGenerator(gen, "Name")
	return specta.SetWith(
		func(s *MemberSpec, m specta.Maybe[string]) { s.Name = m },
		prov,
	)
}

// WithMemberTeamID sets the TeamID field to a literal value.
func WithMemberTeamID(v string) specta.Opt[MemberSpec] {
	return specta.SetLit(func(s *MemberSpec, m specta.Maybe[string]) { s.TeamID = m }, v)
}

// WithMemberTeamIDFromGenerator sets the TeamID field using a Generator.
func WithMemberTeamIDFromGenerator(gen specta.Generator[string]) specta.Opt[MemberSpec] {
	prov := specta.ProviderFromGenerator(gen, "TeamID")
	return specta.SetWith(
		func(s *MemberSpec, m specta.Maybe[string]) { s.TeamID = m },
		prov,
	)
}

// WithMemberTeam sets the Team field to a literal value.
func WithMemberTeam(v *showcase.Team) specta.Opt[MemberSpec] {
	return specta.SetLit(func(s *MemberSpec, m specta.Maybe[*showcase.Team]) { s.Team = m }, v)
}

// WithMemberTeamFromGenerator sets the Team field using a Generator.
func WithMemberTeamFromGenerator(gen specta.Generator[*showcase.Team]) specta.Opt[MemberSpec] {
	prov := specta.ProviderFromGenerator(gen, "Team")
	return specta.SetWith(
		func(s *MemberSpec, m specta.Maybe[*showcase.Team]) { s.Team = m },
		prov,
	)
}

// WithMemberTeamFromProvider sets the Team field using a Provider (evaluated lazily).
func WithMemberTeamFromProvider(prov specta.Provider[*showcase.Team]) specta.Opt[MemberSpec] {
	return specta.SetWith(
		func(s *MemberSpec, m specta.Maybe[*showcase.Team]) { s.Team = m },
		prov,
	)
}
