// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewOrderItemSpec()
//	opts := []specta.Opt[OrderItemSpec]{
//
//
//		WithOrderItemProduct(value),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildOrderItem(specta.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewOrderItemFactory(specta.New())
//
//
//	result := factory.Make(WithOrderItemProduct(value))
package spec

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// OrderItemSpec is the low-level specification for building OrderItem instances.
// Most users should use OrderItemRecipe from the parent factory package instead.
type OrderItemSpec struct {
	Product  specta.Maybe[showcase.Product]
	Quantity specta.Maybe[int]
	Price    specta.Maybe[float64]
}

// NewOrderItemSpec creates a new OrderItemSpec with all fields unset.
func NewOrderItemSpec() OrderItemSpec { return OrderItemSpec{} }

// NewOrderItemFactory creates a new SpecFactory for OrderItem.
func NewOrderItemFactory(p specta.Primitives) *specta.SpecFactory[showcase.OrderItem, OrderItemSpec] {
	return specta.NewSpecFactory(p, NewOrderItemSpec, BuildOrderItem)
}

// Default field providers.
var (
	OrderItemDefaultProduct  = specta.FromSpec(BuildProduct, NewProductSpec)
	OrderItemDefaultQuantity = func(p specta.Primitives) int { return p.Int() }
	OrderItemDefaultPrice    = func(p specta.Primitives) float64 { return p.Float64() }
)

// BuildOrderItem constructs a OrderItem from a OrderItemSpec.
func BuildOrderItem(p specta.Primitives, s OrderItemSpec) showcase.OrderItem {
	product := s.Product.Get(p, OrderItemDefaultProduct)
	quantity := s.Quantity.Get(p, OrderItemDefaultQuantity)
	price := s.Price.Get(p, OrderItemDefaultPrice)
	return showcase.OrderItem{
		Product:  product,
		Quantity: quantity,
		Price:    price,
	}
}

// WithOrderItemProduct sets the Product field to a literal value.
func WithOrderItemProduct(v showcase.Product) specta.Opt[OrderItemSpec] {
	return specta.SetLit(func(s *OrderItemSpec, m specta.Maybe[showcase.Product]) { s.Product = m }, v)
}

// WithOrderItemProductFromProvider sets the Product field using a Provider (evaluated lazily).
func WithOrderItemProductFromProvider(prov specta.Provider[showcase.Product]) specta.Opt[OrderItemSpec] {
	return specta.SetWith(
		func(s *OrderItemSpec, m specta.Maybe[showcase.Product]) { s.Product = m },
		prov,
	)
}

// WithOrderItemQuantity sets the Quantity field to a literal value.
func WithOrderItemQuantity(v int) specta.Opt[OrderItemSpec] {
	return specta.SetLit(func(s *OrderItemSpec, m specta.Maybe[int]) { s.Quantity = m }, v)
}

// WithOrderItemPrice sets the Price field to a literal value.
func WithOrderItemPrice(v float64) specta.Opt[OrderItemSpec] {
	return specta.SetLit(func(s *OrderItemSpec, m specta.Maybe[float64]) { s.Price = m }, v)
}
