// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewOrderSpec()
//	opts := []testgen.Opt[OrderSpec]{
//
//
//		WithOrderID("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildOrder(testgen.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewOrderFactory(testgen.New())
//
//
//	result := factory.Make(WithOrderID("example"))
package spec

import (
	"time"

	testgen "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// OrderSpec is the low-level specification for building Order instances.
// Most users should use OrderRecipe from the parent factory package instead.
type OrderSpec struct {
	ID        testgen.Maybe[string]
	User      testgen.Maybe[showcase.User]
	Items     testgen.Maybe[[]showcase.OrderItem]
	Total     testgen.Maybe[float64]
	Status    testgen.Maybe[string]
	CreatedAt testgen.Maybe[time.Time]
	UpdatedAt testgen.Maybe[time.Time]
}

// NewOrderSpec creates a new OrderSpec with all fields unset.
func NewOrderSpec() OrderSpec { return OrderSpec{} }

// NewOrderFactory creates a new SpecFactory for Order.
func NewOrderFactory(p testgen.Primitives) *testgen.SpecFactory[showcase.Order, OrderSpec] {
	return testgen.NewSpecFactory(p, NewOrderSpec, BuildOrder)
}

// Default field providers.
var (
	OrderDefaultID        = func(p testgen.Primitives) string { return p.ID() }
	OrderDefaultUser      = testgen.FromSpec(BuildUser, NewUserSpec)
	OrderDefaultItems     = func(p testgen.Primitives) []showcase.OrderItem { var zero []showcase.OrderItem; return zero }
	OrderDefaultTotal     = func(p testgen.Primitives) float64 { return p.Float64() }
	OrderDefaultStatus    = func(p testgen.Primitives) string { return p.StringWith("status_") }
	OrderDefaultCreatedAt = func(p testgen.Primitives) time.Time { return p.Time() }
	OrderDefaultUpdatedAt = func(p testgen.Primitives) time.Time { return p.Time() }
)

// BuildOrder constructs a Order from a OrderSpec.
func BuildOrder(p testgen.Primitives, s OrderSpec) showcase.Order {
	iD := s.ID.Get(p, OrderDefaultID)
	user := s.User.Get(p, OrderDefaultUser)
	items := s.Items.Get(p, OrderDefaultItems)
	total := s.Total.Get(p, OrderDefaultTotal)
	status := s.Status.Get(p, OrderDefaultStatus)
	createdAt := s.CreatedAt.Get(p, OrderDefaultCreatedAt)
	updatedAt := s.UpdatedAt.Get(p, OrderDefaultUpdatedAt)
	return showcase.Order{
		ID:        iD,
		User:      user,
		Items:     items,
		Total:     total,
		Status:    status,
		CreatedAt: createdAt,
		UpdatedAt: updatedAt,
	}
}

// WithOrderID sets the ID field to a literal value.
func WithOrderID(v string) testgen.Opt[OrderSpec] {
	return testgen.SetLit(func(s *OrderSpec, m testgen.Maybe[string]) { s.ID = m }, v)
}

// WithOrderUser sets the User field to a literal value.
func WithOrderUser(v showcase.User) testgen.Opt[OrderSpec] {
	return testgen.SetLit(func(s *OrderSpec, m testgen.Maybe[showcase.User]) { s.User = m }, v)
}

// WithOrderUserFromProvider sets the User field using a Provider (evaluated lazily).
func WithOrderUserFromProvider(prov testgen.Provider[showcase.User]) testgen.Opt[OrderSpec] {
	return testgen.SetWith(
		func(s *OrderSpec, m testgen.Maybe[showcase.User]) { s.User = m },
		prov,
	)
}

// WithOrderItems sets the Items field to a literal value.
func WithOrderItems(v []showcase.OrderItem) testgen.Opt[OrderSpec] {
	return testgen.SetLit(func(s *OrderSpec, m testgen.Maybe[[]showcase.OrderItem]) { s.Items = m }, v)
}

// WithOrderItemsFromProvider sets the Items field using a Provider (evaluated lazily).
func WithOrderItemsFromProvider(prov testgen.Provider[[]showcase.OrderItem]) testgen.Opt[OrderSpec] {
	return testgen.SetWith(
		func(s *OrderSpec, m testgen.Maybe[[]showcase.OrderItem]) { s.Items = m },
		prov,
	)
}

// WithOrderTotal sets the Total field to a literal value.
func WithOrderTotal(v float64) testgen.Opt[OrderSpec] {
	return testgen.SetLit(func(s *OrderSpec, m testgen.Maybe[float64]) { s.Total = m }, v)
}

// WithOrderStatus sets the Status field to a literal value.
func WithOrderStatus(v string) testgen.Opt[OrderSpec] {
	return testgen.SetLit(func(s *OrderSpec, m testgen.Maybe[string]) { s.Status = m }, v)
}

// WithOrderCreatedAt sets the CreatedAt field to a literal value.
func WithOrderCreatedAt(v time.Time) testgen.Opt[OrderSpec] {
	return testgen.SetLit(func(s *OrderSpec, m testgen.Maybe[time.Time]) { s.CreatedAt = m }, v)
}

// WithOrderUpdatedAt sets the UpdatedAt field to a literal value.
func WithOrderUpdatedAt(v time.Time) testgen.Opt[OrderSpec] {
	return testgen.SetLit(func(s *OrderSpec, m testgen.Maybe[time.Time]) { s.UpdatedAt = m }, v)
}
