// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewOrderSpec()
//	opts := []specta.Opt[OrderSpec]{
//
//
//		WithOrderID("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildOrder(specta.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewOrderFactory(specta.New())
//
//
//	result := factory.Make(WithOrderID("example"))
package spec

import (
	"time"

	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// OrderSpec is the low-level specification for building Order instances.
// Most users should use OrderRecipe from the parent factory package instead.
type OrderSpec struct {
	ID        specta.Maybe[string]
	User      specta.Maybe[showcase.User]
	Items     specta.Maybe[[]showcase.OrderItem]
	Total     specta.Maybe[float64]
	Status    specta.Maybe[string]
	CreatedAt specta.Maybe[time.Time]
	UpdatedAt specta.Maybe[time.Time]
}

// NewOrderSpec creates a new OrderSpec with all fields unset.
func NewOrderSpec() OrderSpec { return OrderSpec{} }

// NewOrderFactory creates a new SpecFactory for Order.
func NewOrderFactory(s specta.Source) *specta.SpecFactory[showcase.Order, OrderSpec] {
	return specta.NewSpecFactory(s, NewOrderSpec, BuildOrder)
}

// Default field providers.
var (
	OrderDefaultID        = func(s specta.Source) string { return specta.String().ExampleHint("id_").Draw(s, "ID") }
	OrderDefaultUser      = specta.FromSpec(BuildUser, NewUserSpec)
	OrderDefaultItems     = func(s specta.Source) []showcase.OrderItem { var zero []showcase.OrderItem; return zero }
	OrderDefaultTotal     = func(s specta.Source) float64 { return specta.Float64().Draw(s, "Total") }
	OrderDefaultStatus    = func(s specta.Source) string { return specta.String().ExampleHint("status_").Draw(s, "Status") }
	OrderDefaultCreatedAt = func(s specta.Source) time.Time { return specta.Time().Draw(s, "CreatedAt") }
	OrderDefaultUpdatedAt = func(s specta.Source) time.Time { return specta.Time().Draw(s, "UpdatedAt") }
)

// BuildOrder constructs a Order from a OrderSpec.
func BuildOrder(s specta.Source, spec OrderSpec) showcase.Order {
	iD := spec.ID.Get(s, OrderDefaultID)
	user := spec.User.Get(s, OrderDefaultUser)
	items := spec.Items.Get(s, OrderDefaultItems)
	total := spec.Total.Get(s, OrderDefaultTotal)
	status := spec.Status.Get(s, OrderDefaultStatus)
	createdAt := spec.CreatedAt.Get(s, OrderDefaultCreatedAt)
	updatedAt := spec.UpdatedAt.Get(s, OrderDefaultUpdatedAt)
	return showcase.Order{
		ID:        iD,
		User:      user,
		Items:     items,
		Total:     total,
		Status:    status,
		CreatedAt: createdAt,
		UpdatedAt: updatedAt,
	}
}

// WithOrderID sets the ID field to a literal value.
func WithOrderID(v string) specta.Opt[OrderSpec] {
	return specta.SetLit(func(s *OrderSpec, m specta.Maybe[string]) { s.ID = m }, v)
}

// WithOrderUser sets the User field to a literal value.
func WithOrderUser(v showcase.User) specta.Opt[OrderSpec] {
	return specta.SetLit(func(s *OrderSpec, m specta.Maybe[showcase.User]) { s.User = m }, v)
}

// WithOrderUserFromProvider sets the User field using a Provider (evaluated lazily).
func WithOrderUserFromProvider(prov specta.Provider[showcase.User]) specta.Opt[OrderSpec] {
	return specta.SetWith(
		func(s *OrderSpec, m specta.Maybe[showcase.User]) { s.User = m },
		prov,
	)
}

// WithOrderItems sets the Items field to a literal value.
func WithOrderItems(v []showcase.OrderItem) specta.Opt[OrderSpec] {
	return specta.SetLit(func(s *OrderSpec, m specta.Maybe[[]showcase.OrderItem]) { s.Items = m }, v)
}

// WithOrderItemsFromProvider sets the Items field using a Provider (evaluated lazily).
func WithOrderItemsFromProvider(prov specta.Provider[[]showcase.OrderItem]) specta.Opt[OrderSpec] {
	return specta.SetWith(
		func(s *OrderSpec, m specta.Maybe[[]showcase.OrderItem]) { s.Items = m },
		prov,
	)
}

// WithOrderTotal sets the Total field to a literal value.
func WithOrderTotal(v float64) specta.Opt[OrderSpec] {
	return specta.SetLit(func(s *OrderSpec, m specta.Maybe[float64]) { s.Total = m }, v)
}

// WithOrderStatus sets the Status field to a literal value.
func WithOrderStatus(v string) specta.Opt[OrderSpec] {
	return specta.SetLit(func(s *OrderSpec, m specta.Maybe[string]) { s.Status = m }, v)
}

// WithOrderCreatedAt sets the CreatedAt field to a literal value.
func WithOrderCreatedAt(v time.Time) specta.Opt[OrderSpec] {
	return specta.SetLit(func(s *OrderSpec, m specta.Maybe[time.Time]) { s.CreatedAt = m }, v)
}

// WithOrderUpdatedAt sets the UpdatedAt field to a literal value.
func WithOrderUpdatedAt(v time.Time) specta.Opt[OrderSpec] {
	return specta.SetLit(func(s *OrderSpec, m specta.Maybe[time.Time]) { s.UpdatedAt = m }, v)
}
