// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewOrganizationSpec()
//	opts := []testgen.Opt[OrganizationSpec]{
//
//
//		WithOrganizationID("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildOrganization(testgen.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewOrganizationFactory(testgen.New())
//
//
//	result := factory.Make(WithOrganizationID("example"))
package spec

import (
	testgen "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// OrganizationSpec is the low-level specification for building Organization instances.
// Most users should use OrganizationRecipe from the parent factory package instead.
type OrganizationSpec struct {
	ID       testgen.Maybe[string]
	Name     testgen.Maybe[string]
	CEO      testgen.Maybe[*showcase.User]
	Teams    testgen.Maybe[[]showcase.Team]
	Members  testgen.Maybe[[]showcase.Member]
	Metadata testgen.Maybe[map[string]string]
}

// NewOrganizationSpec creates a new OrganizationSpec with all fields unset.
func NewOrganizationSpec() OrganizationSpec { return OrganizationSpec{} }

// NewOrganizationFactory creates a new SpecFactory for Organization.
func NewOrganizationFactory(p testgen.Primitives) *testgen.SpecFactory[showcase.Organization, OrganizationSpec] {
	return testgen.NewSpecFactory(p, NewOrganizationSpec, BuildOrganization)
}

// Default field providers.
var (
	OrganizationDefaultID       = func(p testgen.Primitives) string { return p.ID() }
	OrganizationDefaultName     = func(p testgen.Primitives) string { return p.StringWith("name_") }
	OrganizationDefaultCEO      = testgen.PtrOf(testgen.FromSpec(BuildUser, NewUserSpec))
	OrganizationDefaultTeams    = func(p testgen.Primitives) []showcase.Team { var zero []showcase.Team; return zero }
	OrganizationDefaultMembers  = func(p testgen.Primitives) []showcase.Member { var zero []showcase.Member; return zero }
	OrganizationDefaultMetadata = func(p testgen.Primitives) map[string]string { var zero map[string]string; return zero }
)

// BuildOrganization constructs a Organization from a OrganizationSpec.
func BuildOrganization(p testgen.Primitives, s OrganizationSpec) showcase.Organization {
	iD := s.ID.Get(p, OrganizationDefaultID)
	name := s.Name.Get(p, OrganizationDefaultName)
	cEO := s.CEO.Get(p, OrganizationDefaultCEO)
	teams := s.Teams.Get(p, OrganizationDefaultTeams)
	members := s.Members.Get(p, OrganizationDefaultMembers)
	metadata := s.Metadata.Get(p, OrganizationDefaultMetadata)
	return showcase.Organization{
		ID:       iD,
		Name:     name,
		CEO:      cEO,
		Teams:    teams,
		Members:  members,
		Metadata: metadata,
	}
}

// WithOrganizationID sets the ID field to a literal value.
func WithOrganizationID(v string) testgen.Opt[OrganizationSpec] {
	return testgen.SetLit(func(s *OrganizationSpec, m testgen.Maybe[string]) { s.ID = m }, v)
}

// WithOrganizationName sets the Name field to a literal value.
func WithOrganizationName(v string) testgen.Opt[OrganizationSpec] {
	return testgen.SetLit(func(s *OrganizationSpec, m testgen.Maybe[string]) { s.Name = m }, v)
}

// WithOrganizationCEO sets the CEO field to a literal value.
func WithOrganizationCEO(v *showcase.User) testgen.Opt[OrganizationSpec] {
	return testgen.SetLit(func(s *OrganizationSpec, m testgen.Maybe[*showcase.User]) { s.CEO = m }, v)
}

// WithOrganizationCEOFromProvider sets the CEO field using a Provider (evaluated lazily).
func WithOrganizationCEOFromProvider(prov testgen.Provider[*showcase.User]) testgen.Opt[OrganizationSpec] {
	return testgen.SetWith(
		func(s *OrganizationSpec, m testgen.Maybe[*showcase.User]) { s.CEO = m },
		prov,
	)
}

// WithOrganizationTeams sets the Teams field to a literal value.
func WithOrganizationTeams(v []showcase.Team) testgen.Opt[OrganizationSpec] {
	return testgen.SetLit(func(s *OrganizationSpec, m testgen.Maybe[[]showcase.Team]) { s.Teams = m }, v)
}

// WithOrganizationTeamsFromProvider sets the Teams field using a Provider (evaluated lazily).
func WithOrganizationTeamsFromProvider(prov testgen.Provider[[]showcase.Team]) testgen.Opt[OrganizationSpec] {
	return testgen.SetWith(
		func(s *OrganizationSpec, m testgen.Maybe[[]showcase.Team]) { s.Teams = m },
		prov,
	)
}

// WithOrganizationMembers sets the Members field to a literal value.
func WithOrganizationMembers(v []showcase.Member) testgen.Opt[OrganizationSpec] {
	return testgen.SetLit(func(s *OrganizationSpec, m testgen.Maybe[[]showcase.Member]) { s.Members = m }, v)
}

// WithOrganizationMembersFromProvider sets the Members field using a Provider (evaluated lazily).
func WithOrganizationMembersFromProvider(prov testgen.Provider[[]showcase.Member]) testgen.Opt[OrganizationSpec] {
	return testgen.SetWith(
		func(s *OrganizationSpec, m testgen.Maybe[[]showcase.Member]) { s.Members = m },
		prov,
	)
}

// WithOrganizationMetadata sets the Metadata field to a literal value.
func WithOrganizationMetadata(v map[string]string) testgen.Opt[OrganizationSpec] {
	return testgen.SetLit(func(s *OrganizationSpec, m testgen.Maybe[map[string]string]) { s.Metadata = m }, v)
}
