// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewOrganizationSpec()
//	opts := []specta.Opt[OrganizationSpec]{
//
//
//		WithOrganizationID("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildOrganization(specta.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewOrganizationFactory(specta.New())
//
//
//	result := factory.Make(WithOrganizationID("example"))
package spec

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// OrganizationSpec is the low-level specification for building Organization instances.
// Most users should use OrganizationRecipe from the parent factory package instead.
type OrganizationSpec struct {
	ID       specta.Maybe[string]
	Name     specta.Maybe[string]
	CEO      specta.Maybe[*showcase.User]
	Teams    specta.Maybe[[]showcase.Team]
	Members  specta.Maybe[[]showcase.Member]
	Metadata specta.Maybe[map[string]string]
}

// NewOrganizationSpec creates a new OrganizationSpec with all fields unset.
func NewOrganizationSpec() OrganizationSpec { return OrganizationSpec{} }

// NewOrganizationFactory creates a new SpecFactory for Organization.
func NewOrganizationFactory(s specta.Source) *specta.SpecFactory[showcase.Organization, OrganizationSpec] {
	return specta.NewSpecFactory(s, NewOrganizationSpec, BuildOrganization)
}

// Default field generators.
var (
	OrganizationIDGenerator       specta.Generator[string]            = specta.String().ExampleHint("id_")
	OrganizationNameGenerator     specta.Generator[string]            = specta.String().ExampleHint("name_")
	OrganizationCEOGenerator      specta.Generator[*showcase.User]    = specta.GeneratorFromProvider(specta.PtrOf(specta.FromSpec(BuildUser, NewUserSpec)))
	OrganizationTeamsGenerator    specta.Generator[[]showcase.Team]   = specta.GeneratorFromProvider(func(s specta.Source) []showcase.Team { var zero []showcase.Team; return zero })
	OrganizationMembersGenerator  specta.Generator[[]showcase.Member] = specta.GeneratorFromProvider(func(s specta.Source) []showcase.Member { var zero []showcase.Member; return zero })
	OrganizationMetadataGenerator specta.Generator[map[string]string] = specta.Map(specta.String(), specta.String()).MaxLen(5)
)

// BuildOrganization constructs a Organization from a OrganizationSpec.
func BuildOrganization(s specta.Source, spec OrganizationSpec) showcase.Organization {
	iD := spec.ID.GetWithGenerator(s, "ID", OrganizationIDGenerator)
	name := spec.Name.GetWithGenerator(s, "Name", OrganizationNameGenerator)
	cEO := spec.CEO.GetWithGenerator(s, "CEO", OrganizationCEOGenerator)
	teams := spec.Teams.GetWithGenerator(s, "Teams", OrganizationTeamsGenerator)
	members := spec.Members.GetWithGenerator(s, "Members", OrganizationMembersGenerator)
	metadata := spec.Metadata.GetWithGenerator(s, "Metadata", OrganizationMetadataGenerator)
	return showcase.Organization{
		ID:       iD,
		Name:     name,
		CEO:      cEO,
		Teams:    teams,
		Members:  members,
		Metadata: metadata,
	}
}

// WithOrganizationID sets the ID field to a literal value.
func WithOrganizationID(v string) specta.Opt[OrganizationSpec] {
	return specta.SetLit(func(s *OrganizationSpec, m specta.Maybe[string]) { s.ID = m }, v)
}

// WithOrganizationIDFromGenerator sets the ID field using a Generator.
func WithOrganizationIDFromGenerator(gen specta.Generator[string]) specta.Opt[OrganizationSpec] {
	prov := specta.ProviderFromGenerator(gen, "ID")
	return specta.SetWith(
		func(s *OrganizationSpec, m specta.Maybe[string]) { s.ID = m },
		prov,
	)
}

// WithOrganizationName sets the Name field to a literal value.
func WithOrganizationName(v string) specta.Opt[OrganizationSpec] {
	return specta.SetLit(func(s *OrganizationSpec, m specta.Maybe[string]) { s.Name = m }, v)
}

// WithOrganizationNameFromGenerator sets the Name field using a Generator.
func WithOrganizationNameFromGenerator(gen specta.Generator[string]) specta.Opt[OrganizationSpec] {
	prov := specta.ProviderFromGenerator(gen, "Name")
	return specta.SetWith(
		func(s *OrganizationSpec, m specta.Maybe[string]) { s.Name = m },
		prov,
	)
}

// WithOrganizationCEO sets the CEO field to a literal value.
func WithOrganizationCEO(v *showcase.User) specta.Opt[OrganizationSpec] {
	return specta.SetLit(func(s *OrganizationSpec, m specta.Maybe[*showcase.User]) { s.CEO = m }, v)
}

// WithOrganizationCEOFromGenerator sets the CEO field using a Generator.
func WithOrganizationCEOFromGenerator(gen specta.Generator[*showcase.User]) specta.Opt[OrganizationSpec] {
	prov := specta.ProviderFromGenerator(gen, "CEO")
	return specta.SetWith(
		func(s *OrganizationSpec, m specta.Maybe[*showcase.User]) { s.CEO = m },
		prov,
	)
}

// WithOrganizationCEOFromProvider sets the CEO field using a Provider (evaluated lazily).
func WithOrganizationCEOFromProvider(prov specta.Provider[*showcase.User]) specta.Opt[OrganizationSpec] {
	return specta.SetWith(
		func(s *OrganizationSpec, m specta.Maybe[*showcase.User]) { s.CEO = m },
		prov,
	)
}

// WithOrganizationTeams sets the Teams field to a literal value.
func WithOrganizationTeams(v []showcase.Team) specta.Opt[OrganizationSpec] {
	return specta.SetLit(func(s *OrganizationSpec, m specta.Maybe[[]showcase.Team]) { s.Teams = m }, v)
}

// WithOrganizationTeamsFromGenerator sets the Teams field using a Generator.
func WithOrganizationTeamsFromGenerator(gen specta.Generator[[]showcase.Team]) specta.Opt[OrganizationSpec] {
	prov := specta.ProviderFromGenerator(gen, "Teams")
	return specta.SetWith(
		func(s *OrganizationSpec, m specta.Maybe[[]showcase.Team]) { s.Teams = m },
		prov,
	)
}

// WithOrganizationTeamsFromProvider sets the Teams field using a Provider (evaluated lazily).
func WithOrganizationTeamsFromProvider(prov specta.Provider[[]showcase.Team]) specta.Opt[OrganizationSpec] {
	return specta.SetWith(
		func(s *OrganizationSpec, m specta.Maybe[[]showcase.Team]) { s.Teams = m },
		prov,
	)
}

// WithOrganizationMembers sets the Members field to a literal value.
func WithOrganizationMembers(v []showcase.Member) specta.Opt[OrganizationSpec] {
	return specta.SetLit(func(s *OrganizationSpec, m specta.Maybe[[]showcase.Member]) { s.Members = m }, v)
}

// WithOrganizationMembersFromGenerator sets the Members field using a Generator.
func WithOrganizationMembersFromGenerator(gen specta.Generator[[]showcase.Member]) specta.Opt[OrganizationSpec] {
	prov := specta.ProviderFromGenerator(gen, "Members")
	return specta.SetWith(
		func(s *OrganizationSpec, m specta.Maybe[[]showcase.Member]) { s.Members = m },
		prov,
	)
}

// WithOrganizationMembersFromProvider sets the Members field using a Provider (evaluated lazily).
func WithOrganizationMembersFromProvider(prov specta.Provider[[]showcase.Member]) specta.Opt[OrganizationSpec] {
	return specta.SetWith(
		func(s *OrganizationSpec, m specta.Maybe[[]showcase.Member]) { s.Members = m },
		prov,
	)
}

// WithOrganizationMetadata sets the Metadata field to a literal value.
func WithOrganizationMetadata(v map[string]string) specta.Opt[OrganizationSpec] {
	return specta.SetLit(func(s *OrganizationSpec, m specta.Maybe[map[string]string]) { s.Metadata = m }, v)
}

// WithOrganizationMetadataFromGenerator sets the Metadata field using a Generator.
func WithOrganizationMetadataFromGenerator(gen specta.Generator[map[string]string]) specta.Opt[OrganizationSpec] {
	prov := specta.ProviderFromGenerator(gen, "Metadata")
	return specta.SetWith(
		func(s *OrganizationSpec, m specta.Maybe[map[string]string]) { s.Metadata = m },
		prov,
	)
}
