// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewProductSpec()
//	opts := []specta.Opt[ProductSpec]{
//
//
//		WithProductID("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildProduct(specta.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewProductFactory(specta.New())
//
//
//	result := factory.Make(WithProductID("example"))
package spec

import (
	"time"

	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// ProductSpec is the low-level specification for building Product instances.
// Most users should use ProductRecipe from the parent factory package instead.
type ProductSpec struct {
	ID          specta.Maybe[string]
	Name        specta.Maybe[string]
	Description specta.Maybe[string]
	Price       specta.Maybe[float64]
	InStock     specta.Maybe[bool]
	CreatedAt   specta.Maybe[time.Time]
}

// NewProductSpec creates a new ProductSpec with all fields unset.
func NewProductSpec() ProductSpec { return ProductSpec{} }

// NewProductFactory creates a new SpecFactory for Product.
func NewProductFactory(s specta.Source) *specta.SpecFactory[showcase.Product, ProductSpec] {
	return specta.NewSpecFactory(s, NewProductSpec, BuildProduct)
}

// Default field providers.
var (
	ProductDefaultID          = func(s specta.Source) string { return specta.String().ExampleHint("id_").Draw(s, "ID") }
	ProductDefaultName        = func(s specta.Source) string { return specta.String().ExampleHint("name_").Draw(s, "Name") }
	ProductDefaultDescription = func(s specta.Source) string {
		return specta.String().ExampleHint("description_").Draw(s, "Description")
	}
	ProductDefaultPrice     = func(s specta.Source) float64 { return specta.Float64().Draw(s, "Price") }
	ProductDefaultInStock   = func(s specta.Source) bool { return specta.Bool().Draw(s, "InStock") }
	ProductDefaultCreatedAt = func(s specta.Source) time.Time { return specta.Time().Draw(s, "CreatedAt") }
)

// BuildProduct constructs a Product from a ProductSpec.
func BuildProduct(s specta.Source, spec ProductSpec) showcase.Product {
	iD := spec.ID.Get(s, ProductDefaultID)
	name := spec.Name.Get(s, ProductDefaultName)
	description := spec.Description.Get(s, ProductDefaultDescription)
	price := spec.Price.Get(s, ProductDefaultPrice)
	inStock := spec.InStock.Get(s, ProductDefaultInStock)
	createdAt := spec.CreatedAt.Get(s, ProductDefaultCreatedAt)
	return showcase.Product{
		ID:          iD,
		Name:        name,
		Description: description,
		Price:       price,
		InStock:     inStock,
		CreatedAt:   createdAt,
	}
}

// WithProductID sets the ID field to a literal value.
func WithProductID(v string) specta.Opt[ProductSpec] {
	return specta.SetLit(func(s *ProductSpec, m specta.Maybe[string]) { s.ID = m }, v)
}

// WithProductName sets the Name field to a literal value.
func WithProductName(v string) specta.Opt[ProductSpec] {
	return specta.SetLit(func(s *ProductSpec, m specta.Maybe[string]) { s.Name = m }, v)
}

// WithProductDescription sets the Description field to a literal value.
func WithProductDescription(v string) specta.Opt[ProductSpec] {
	return specta.SetLit(func(s *ProductSpec, m specta.Maybe[string]) { s.Description = m }, v)
}

// WithProductPrice sets the Price field to a literal value.
func WithProductPrice(v float64) specta.Opt[ProductSpec] {
	return specta.SetLit(func(s *ProductSpec, m specta.Maybe[float64]) { s.Price = m }, v)
}

// WithProductInStock sets the InStock field to a literal value.
func WithProductInStock(v bool) specta.Opt[ProductSpec] {
	return specta.SetLit(func(s *ProductSpec, m specta.Maybe[bool]) { s.InStock = m }, v)
}

// WithProductCreatedAt sets the CreatedAt field to a literal value.
func WithProductCreatedAt(v time.Time) specta.Opt[ProductSpec] {
	return specta.SetLit(func(s *ProductSpec, m specta.Maybe[time.Time]) { s.CreatedAt = m }, v)
}
