// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewProductSpec()
//	opts := []testgen.Opt[ProductSpec]{
//
//
//		WithProductID("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildProduct(testgen.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewProductFactory(testgen.New())
//
//
//	result := factory.Make(WithProductID("example"))
package spec

import (
	"time"

	testgen "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// ProductSpec is the low-level specification for building Product instances.
// Most users should use ProductRecipe from the parent factory package instead.
type ProductSpec struct {
	ID          testgen.Maybe[string]
	Name        testgen.Maybe[string]
	Description testgen.Maybe[string]
	Price       testgen.Maybe[float64]
	InStock     testgen.Maybe[bool]
	CreatedAt   testgen.Maybe[time.Time]
}

// NewProductSpec creates a new ProductSpec with all fields unset.
func NewProductSpec() ProductSpec { return ProductSpec{} }

// NewProductFactory creates a new SpecFactory for Product.
func NewProductFactory(p testgen.Primitives) *testgen.SpecFactory[showcase.Product, ProductSpec] {
	return testgen.NewSpecFactory(p, NewProductSpec, BuildProduct)
}

// Default field providers.
var (
	ProductDefaultID          = func(p testgen.Primitives) string { return p.ID() }
	ProductDefaultName        = func(p testgen.Primitives) string { return p.StringWith("name_") }
	ProductDefaultDescription = func(p testgen.Primitives) string { return p.StringWith("description_") }
	ProductDefaultPrice       = func(p testgen.Primitives) float64 { return p.Float64() }
	ProductDefaultInStock     = func(p testgen.Primitives) bool { return p.Bool() }
	ProductDefaultCreatedAt   = func(p testgen.Primitives) time.Time { return p.Time() }
)

// BuildProduct constructs a Product from a ProductSpec.
func BuildProduct(p testgen.Primitives, s ProductSpec) showcase.Product {
	iD := s.ID.Get(p, ProductDefaultID)
	name := s.Name.Get(p, ProductDefaultName)
	description := s.Description.Get(p, ProductDefaultDescription)
	price := s.Price.Get(p, ProductDefaultPrice)
	inStock := s.InStock.Get(p, ProductDefaultInStock)
	createdAt := s.CreatedAt.Get(p, ProductDefaultCreatedAt)
	return showcase.Product{
		ID:          iD,
		Name:        name,
		Description: description,
		Price:       price,
		InStock:     inStock,
		CreatedAt:   createdAt,
	}
}

// WithProductID sets the ID field to a literal value.
func WithProductID(v string) testgen.Opt[ProductSpec] {
	return testgen.SetLit(func(s *ProductSpec, m testgen.Maybe[string]) { s.ID = m }, v)
}

// WithProductName sets the Name field to a literal value.
func WithProductName(v string) testgen.Opt[ProductSpec] {
	return testgen.SetLit(func(s *ProductSpec, m testgen.Maybe[string]) { s.Name = m }, v)
}

// WithProductDescription sets the Description field to a literal value.
func WithProductDescription(v string) testgen.Opt[ProductSpec] {
	return testgen.SetLit(func(s *ProductSpec, m testgen.Maybe[string]) { s.Description = m }, v)
}

// WithProductPrice sets the Price field to a literal value.
func WithProductPrice(v float64) testgen.Opt[ProductSpec] {
	return testgen.SetLit(func(s *ProductSpec, m testgen.Maybe[float64]) { s.Price = m }, v)
}

// WithProductInStock sets the InStock field to a literal value.
func WithProductInStock(v bool) testgen.Opt[ProductSpec] {
	return testgen.SetLit(func(s *ProductSpec, m testgen.Maybe[bool]) { s.InStock = m }, v)
}

// WithProductCreatedAt sets the CreatedAt field to a literal value.
func WithProductCreatedAt(v time.Time) testgen.Opt[ProductSpec] {
	return testgen.SetLit(func(s *ProductSpec, m testgen.Maybe[time.Time]) { s.CreatedAt = m }, v)
}
