// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewProfileSpec()
//	opts := []testgen.Opt[ProfileSpec]{
//
//
//		WithProfileID("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildProfile(testgen.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewProfileFactory(testgen.New())
//
//
//	result := factory.Make(WithProfileID("example"))
package spec

import (
	testgen "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// ProfileSpec is the low-level specification for building Profile instances.
// Most users should use ProfileRecipe from the parent factory package instead.
type ProfileSpec struct {
	ID          testgen.Maybe[string]
	Name        testgen.Maybe[string]
	Description testgen.Maybe[string]
	Manager     testgen.Maybe[*showcase.User]
	IsPublic    testgen.Maybe[bool]
}

// NewProfileSpec creates a new ProfileSpec with all fields unset.
func NewProfileSpec() ProfileSpec { return ProfileSpec{} }

// NewProfileFactory creates a new SpecFactory for Profile.
func NewProfileFactory(p testgen.Primitives) *testgen.SpecFactory[showcase.Profile, ProfileSpec] {
	return testgen.NewSpecFactory(p, NewProfileSpec, BuildProfile)
}

// Default field providers.
var (
	ProfileDefaultID          = func(p testgen.Primitives) string { return p.ID() }
	ProfileDefaultName        = func(p testgen.Primitives) string { return p.StringWith("name_") }
	ProfileDefaultDescription = func(p testgen.Primitives) string { return p.StringWith("description_") }
	ProfileDefaultManager     = testgen.PtrOf(testgen.FromSpec(BuildUser, NewUserSpec))
	ProfileDefaultIsPublic    = func(p testgen.Primitives) bool { return p.Bool() }
)

// BuildProfile constructs a Profile from a ProfileSpec.
func BuildProfile(p testgen.Primitives, s ProfileSpec) showcase.Profile {
	iD := s.ID.Get(p, ProfileDefaultID)
	name := s.Name.Get(p, ProfileDefaultName)
	description := s.Description.Get(p, ProfileDefaultDescription)
	manager := s.Manager.Get(p, ProfileDefaultManager)
	isPublic := s.IsPublic.Get(p, ProfileDefaultIsPublic)
	return showcase.Profile{
		ID:          iD,
		Name:        name,
		Description: description,
		Manager:     manager,
		IsPublic:    isPublic,
	}
}

// WithProfileID sets the ID field to a literal value.
func WithProfileID(v string) testgen.Opt[ProfileSpec] {
	return testgen.SetLit(func(s *ProfileSpec, m testgen.Maybe[string]) { s.ID = m }, v)
}

// WithProfileName sets the Name field to a literal value.
func WithProfileName(v string) testgen.Opt[ProfileSpec] {
	return testgen.SetLit(func(s *ProfileSpec, m testgen.Maybe[string]) { s.Name = m }, v)
}

// WithProfileDescription sets the Description field to a literal value.
func WithProfileDescription(v string) testgen.Opt[ProfileSpec] {
	return testgen.SetLit(func(s *ProfileSpec, m testgen.Maybe[string]) { s.Description = m }, v)
}

// WithProfileManager sets the Manager field to a literal value.
func WithProfileManager(v *showcase.User) testgen.Opt[ProfileSpec] {
	return testgen.SetLit(func(s *ProfileSpec, m testgen.Maybe[*showcase.User]) { s.Manager = m }, v)
}

// WithProfileManagerFromProvider sets the Manager field using a Provider (evaluated lazily).
func WithProfileManagerFromProvider(prov testgen.Provider[*showcase.User]) testgen.Opt[ProfileSpec] {
	return testgen.SetWith(
		func(s *ProfileSpec, m testgen.Maybe[*showcase.User]) { s.Manager = m },
		prov,
	)
}

// WithProfileIsPublic sets the IsPublic field to a literal value.
func WithProfileIsPublic(v bool) testgen.Opt[ProfileSpec] {
	return testgen.SetLit(func(s *ProfileSpec, m testgen.Maybe[bool]) { s.IsPublic = m }, v)
}
