// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewProfileSpec()
//	opts := []specta.Opt[ProfileSpec]{
//
//
//		WithProfileID("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildProfile(specta.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewProfileFactory(specta.New())
//
//
//	result := factory.Make(WithProfileID("example"))
package spec

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// ProfileSpec is the low-level specification for building Profile instances.
// Most users should use ProfileRecipe from the parent factory package instead.
type ProfileSpec struct {
	ID          specta.Maybe[string]
	Name        specta.Maybe[string]
	Description specta.Maybe[string]
	Manager     specta.Maybe[*showcase.User]
	IsPublic    specta.Maybe[bool]
}

// NewProfileSpec creates a new ProfileSpec with all fields unset.
func NewProfileSpec() ProfileSpec { return ProfileSpec{} }

// NewProfileFactory creates a new SpecFactory for Profile.
func NewProfileFactory(s specta.Source) *specta.SpecFactory[showcase.Profile, ProfileSpec] {
	return specta.NewSpecFactory(s, NewProfileSpec, BuildProfile)
}

// Default field generators.
var (
	ProfileIDGenerator          specta.Generator[string]         = specta.String().ExampleHint("id_")
	ProfileNameGenerator        specta.Generator[string]         = specta.String().ExampleHint("name_")
	ProfileDescriptionGenerator specta.Generator[string]         = specta.String().ExampleHint("description_")
	ProfileManagerGenerator     specta.Generator[*showcase.User] = specta.GeneratorFromProvider(specta.PtrOf(specta.FromSpec(BuildUser, NewUserSpec)))
	ProfileIsPublicGenerator    specta.Generator[bool]           = specta.Bool()
)

// BuildProfile constructs a Profile from a ProfileSpec.
func BuildProfile(s specta.Source, spec ProfileSpec) showcase.Profile {
	iD := spec.ID.GetWithGenerator(s, "ID", ProfileIDGenerator)
	name := spec.Name.GetWithGenerator(s, "Name", ProfileNameGenerator)
	description := spec.Description.GetWithGenerator(s, "Description", ProfileDescriptionGenerator)
	manager := spec.Manager.GetWithGenerator(s, "Manager", ProfileManagerGenerator)
	isPublic := spec.IsPublic.GetWithGenerator(s, "IsPublic", ProfileIsPublicGenerator)
	return showcase.Profile{
		ID:          iD,
		Name:        name,
		Description: description,
		Manager:     manager,
		IsPublic:    isPublic,
	}
}

// WithProfileID sets the ID field to a literal value.
func WithProfileID(v string) specta.Opt[ProfileSpec] {
	return specta.SetLit(func(s *ProfileSpec, m specta.Maybe[string]) { s.ID = m }, v)
}

// WithProfileIDFromGenerator sets the ID field using a Generator.
func WithProfileIDFromGenerator(gen specta.Generator[string]) specta.Opt[ProfileSpec] {
	prov := specta.ProviderFromGenerator(gen, "ID")
	return specta.SetWith(
		func(s *ProfileSpec, m specta.Maybe[string]) { s.ID = m },
		prov,
	)
}

// WithProfileName sets the Name field to a literal value.
func WithProfileName(v string) specta.Opt[ProfileSpec] {
	return specta.SetLit(func(s *ProfileSpec, m specta.Maybe[string]) { s.Name = m }, v)
}

// WithProfileNameFromGenerator sets the Name field using a Generator.
func WithProfileNameFromGenerator(gen specta.Generator[string]) specta.Opt[ProfileSpec] {
	prov := specta.ProviderFromGenerator(gen, "Name")
	return specta.SetWith(
		func(s *ProfileSpec, m specta.Maybe[string]) { s.Name = m },
		prov,
	)
}

// WithProfileDescription sets the Description field to a literal value.
func WithProfileDescription(v string) specta.Opt[ProfileSpec] {
	return specta.SetLit(func(s *ProfileSpec, m specta.Maybe[string]) { s.Description = m }, v)
}

// WithProfileDescriptionFromGenerator sets the Description field using a Generator.
func WithProfileDescriptionFromGenerator(gen specta.Generator[string]) specta.Opt[ProfileSpec] {
	prov := specta.ProviderFromGenerator(gen, "Description")
	return specta.SetWith(
		func(s *ProfileSpec, m specta.Maybe[string]) { s.Description = m },
		prov,
	)
}

// WithProfileManager sets the Manager field to a literal value.
func WithProfileManager(v *showcase.User) specta.Opt[ProfileSpec] {
	return specta.SetLit(func(s *ProfileSpec, m specta.Maybe[*showcase.User]) { s.Manager = m }, v)
}

// WithProfileManagerFromGenerator sets the Manager field using a Generator.
func WithProfileManagerFromGenerator(gen specta.Generator[*showcase.User]) specta.Opt[ProfileSpec] {
	prov := specta.ProviderFromGenerator(gen, "Manager")
	return specta.SetWith(
		func(s *ProfileSpec, m specta.Maybe[*showcase.User]) { s.Manager = m },
		prov,
	)
}

// WithProfileManagerFromProvider sets the Manager field using a Provider (evaluated lazily).
func WithProfileManagerFromProvider(prov specta.Provider[*showcase.User]) specta.Opt[ProfileSpec] {
	return specta.SetWith(
		func(s *ProfileSpec, m specta.Maybe[*showcase.User]) { s.Manager = m },
		prov,
	)
}

// WithProfileIsPublic sets the IsPublic field to a literal value.
func WithProfileIsPublic(v bool) specta.Opt[ProfileSpec] {
	return specta.SetLit(func(s *ProfileSpec, m specta.Maybe[bool]) { s.IsPublic = m }, v)
}

// WithProfileIsPublicFromGenerator sets the IsPublic field using a Generator.
func WithProfileIsPublicFromGenerator(gen specta.Generator[bool]) specta.Opt[ProfileSpec] {
	prov := specta.ProviderFromGenerator(gen, "IsPublic")
	return specta.SetWith(
		func(s *ProfileSpec, m specta.Maybe[bool]) { s.IsPublic = m },
		prov,
	)
}
