// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewProfileSpec()
//	opts := []specta.Opt[ProfileSpec]{
//
//
//		WithProfileID("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildProfile(specta.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewProfileFactory(specta.New())
//
//
//	result := factory.Make(WithProfileID("example"))
package spec

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// ProfileSpec is the low-level specification for building Profile instances.
// Most users should use ProfileRecipe from the parent factory package instead.
type ProfileSpec struct {
	ID          specta.Maybe[string]
	Name        specta.Maybe[string]
	Description specta.Maybe[string]
	Manager     specta.Maybe[*showcase.User]
	IsPublic    specta.Maybe[bool]
}

// NewProfileSpec creates a new ProfileSpec with all fields unset.
func NewProfileSpec() ProfileSpec { return ProfileSpec{} }

// NewProfileFactory creates a new SpecFactory for Profile.
func NewProfileFactory(s specta.Source) *specta.SpecFactory[showcase.Profile, ProfileSpec] {
	return specta.NewSpecFactory(s, NewProfileSpec, BuildProfile)
}

// Default field providers.
var (
	ProfileDefaultID          = func(s specta.Source) string { return specta.String().ExampleHint("id_").Draw(s, "ID") }
	ProfileDefaultName        = func(s specta.Source) string { return specta.String().ExampleHint("name_").Draw(s, "Name") }
	ProfileDefaultDescription = func(s specta.Source) string {
		return specta.String().ExampleHint("description_").Draw(s, "Description")
	}
	ProfileDefaultManager  = specta.PtrOf(specta.FromSpec(BuildUser, NewUserSpec))
	ProfileDefaultIsPublic = func(s specta.Source) bool { return specta.Bool().Draw(s, "IsPublic") }
)

// BuildProfile constructs a Profile from a ProfileSpec.
func BuildProfile(s specta.Source, spec ProfileSpec) showcase.Profile {
	iD := spec.ID.Get(s, ProfileDefaultID)
	name := spec.Name.Get(s, ProfileDefaultName)
	description := spec.Description.Get(s, ProfileDefaultDescription)
	manager := spec.Manager.Get(s, ProfileDefaultManager)
	isPublic := spec.IsPublic.Get(s, ProfileDefaultIsPublic)
	return showcase.Profile{
		ID:          iD,
		Name:        name,
		Description: description,
		Manager:     manager,
		IsPublic:    isPublic,
	}
}

// WithProfileID sets the ID field to a literal value.
func WithProfileID(v string) specta.Opt[ProfileSpec] {
	return specta.SetLit(func(s *ProfileSpec, m specta.Maybe[string]) { s.ID = m }, v)
}

// WithProfileName sets the Name field to a literal value.
func WithProfileName(v string) specta.Opt[ProfileSpec] {
	return specta.SetLit(func(s *ProfileSpec, m specta.Maybe[string]) { s.Name = m }, v)
}

// WithProfileDescription sets the Description field to a literal value.
func WithProfileDescription(v string) specta.Opt[ProfileSpec] {
	return specta.SetLit(func(s *ProfileSpec, m specta.Maybe[string]) { s.Description = m }, v)
}

// WithProfileManager sets the Manager field to a literal value.
func WithProfileManager(v *showcase.User) specta.Opt[ProfileSpec] {
	return specta.SetLit(func(s *ProfileSpec, m specta.Maybe[*showcase.User]) { s.Manager = m }, v)
}

// WithProfileManagerFromProvider sets the Manager field using a Provider (evaluated lazily).
func WithProfileManagerFromProvider(prov specta.Provider[*showcase.User]) specta.Opt[ProfileSpec] {
	return specta.SetWith(
		func(s *ProfileSpec, m specta.Maybe[*showcase.User]) { s.Manager = m },
		prov,
	)
}

// WithProfileIsPublic sets the IsPublic field to a literal value.
func WithProfileIsPublic(v bool) specta.Opt[ProfileSpec] {
	return specta.SetLit(func(s *ProfileSpec, m specta.Maybe[bool]) { s.IsPublic = m }, v)
}
