// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewTeamSpec()
//	opts := []testgen.Opt[TeamSpec]{
//
//
//		WithTeamID("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildTeam(testgen.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewTeamFactory(testgen.New())
//
//
//	result := factory.Make(WithTeamID("example"))
package spec

import (
	testgen "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// TeamSpec is the low-level specification for building Team instances.
// Most users should use TeamRecipe from the parent factory package instead.
type TeamSpec struct {
	ID      testgen.Maybe[string]
	Name    testgen.Maybe[string]
	Members testgen.Maybe[[]showcase.Member]
}

// NewTeamSpec creates a new TeamSpec with all fields unset.
func NewTeamSpec() TeamSpec { return TeamSpec{} }

// NewTeamFactory creates a new SpecFactory for Team.
func NewTeamFactory(p testgen.Primitives) *testgen.SpecFactory[showcase.Team, TeamSpec] {
	return testgen.NewSpecFactory(p, NewTeamSpec, BuildTeam)
}

// Default field providers.
var (
	TeamDefaultID      = func(p testgen.Primitives) string { return p.ID() }
	TeamDefaultName    = func(p testgen.Primitives) string { return p.StringWith("name_") }
	TeamDefaultMembers = func(p testgen.Primitives) []showcase.Member { var zero []showcase.Member; return zero }
)

// BuildTeam constructs a Team from a TeamSpec.
func BuildTeam(p testgen.Primitives, s TeamSpec) showcase.Team {
	iD := s.ID.Get(p, TeamDefaultID)
	name := s.Name.Get(p, TeamDefaultName)
	members := s.Members.Get(p, TeamDefaultMembers)
	return showcase.Team{
		ID:      iD,
		Name:    name,
		Members: members,
	}
}

// WithTeamID sets the ID field to a literal value.
func WithTeamID(v string) testgen.Opt[TeamSpec] {
	return testgen.SetLit(func(s *TeamSpec, m testgen.Maybe[string]) { s.ID = m }, v)
}

// WithTeamName sets the Name field to a literal value.
func WithTeamName(v string) testgen.Opt[TeamSpec] {
	return testgen.SetLit(func(s *TeamSpec, m testgen.Maybe[string]) { s.Name = m }, v)
}

// WithTeamMembers sets the Members field to a literal value.
func WithTeamMembers(v []showcase.Member) testgen.Opt[TeamSpec] {
	return testgen.SetLit(func(s *TeamSpec, m testgen.Maybe[[]showcase.Member]) { s.Members = m }, v)
}

// WithTeamMembersFromProvider sets the Members field using a Provider (evaluated lazily).
func WithTeamMembersFromProvider(prov testgen.Provider[[]showcase.Member]) testgen.Opt[TeamSpec] {
	return testgen.SetWith(
		func(s *TeamSpec, m testgen.Maybe[[]showcase.Member]) { s.Members = m },
		prov,
	)
}
