// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewTeamSpec()
//	opts := []specta.Opt[TeamSpec]{
//
//
//		WithTeamID("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildTeam(specta.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewTeamFactory(specta.New())
//
//
//	result := factory.Make(WithTeamID("example"))
package spec

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// TeamSpec is the low-level specification for building Team instances.
// Most users should use TeamRecipe from the parent factory package instead.
type TeamSpec struct {
	ID      specta.Maybe[string]
	Name    specta.Maybe[string]
	Members specta.Maybe[[]showcase.Member]
}

// NewTeamSpec creates a new TeamSpec with all fields unset.
func NewTeamSpec() TeamSpec { return TeamSpec{} }

// NewTeamFactory creates a new SpecFactory for Team.
func NewTeamFactory(s specta.Source) *specta.SpecFactory[showcase.Team, TeamSpec] {
	return specta.NewSpecFactory(s, NewTeamSpec, BuildTeam)
}

// Default field providers.
var (
	TeamDefaultID      = func(s specta.Source) string { return specta.String().ExampleHint("id_").Draw(s, "ID") }
	TeamDefaultName    = func(s specta.Source) string { return specta.String().ExampleHint("name_").Draw(s, "Name") }
	TeamDefaultMembers = func(s specta.Source) []showcase.Member { var zero []showcase.Member; return zero }
)

// BuildTeam constructs a Team from a TeamSpec.
func BuildTeam(s specta.Source, spec TeamSpec) showcase.Team {
	iD := spec.ID.Get(s, TeamDefaultID)
	name := spec.Name.Get(s, TeamDefaultName)
	members := spec.Members.Get(s, TeamDefaultMembers)
	return showcase.Team{
		ID:      iD,
		Name:    name,
		Members: members,
	}
}

// WithTeamID sets the ID field to a literal value.
func WithTeamID(v string) specta.Opt[TeamSpec] {
	return specta.SetLit(func(s *TeamSpec, m specta.Maybe[string]) { s.ID = m }, v)
}

// WithTeamName sets the Name field to a literal value.
func WithTeamName(v string) specta.Opt[TeamSpec] {
	return specta.SetLit(func(s *TeamSpec, m specta.Maybe[string]) { s.Name = m }, v)
}

// WithTeamMembers sets the Members field to a literal value.
func WithTeamMembers(v []showcase.Member) specta.Opt[TeamSpec] {
	return specta.SetLit(func(s *TeamSpec, m specta.Maybe[[]showcase.Member]) { s.Members = m }, v)
}

// WithTeamMembersFromProvider sets the Members field using a Provider (evaluated lazily).
func WithTeamMembersFromProvider(prov specta.Provider[[]showcase.Member]) specta.Opt[TeamSpec] {
	return specta.SetWith(
		func(s *TeamSpec, m specta.Maybe[[]showcase.Member]) { s.Members = m },
		prov,
	)
}
