// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewUserSpec()
//	opts := []specta.Opt[UserSpec]{
//
//
//		WithUserID("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildUser(specta.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewUserFactory(specta.New())
//
//
//	result := factory.Make(WithUserID("example"))
package spec

import (
	"time"

	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// UserSpec is the low-level specification for building User instances.
// Most users should use UserRecipe from the parent factory package instead.
type UserSpec struct {
	ID        specta.Maybe[string]
	Email     specta.Maybe[string]
	FirstName specta.Maybe[string]
	LastName  specta.Maybe[string]
	Active    specta.Maybe[bool]
	Address   specta.Maybe[showcase.Address]
	CreatedAt specta.Maybe[time.Time]
	UpdatedAt specta.Maybe[time.Time]
}

// NewUserSpec creates a new UserSpec with all fields unset.
func NewUserSpec() UserSpec { return UserSpec{} }

// NewUserFactory creates a new SpecFactory for User.
func NewUserFactory(p specta.Primitives) *specta.SpecFactory[showcase.User, UserSpec] {
	return specta.NewSpecFactory(p, NewUserSpec, BuildUser)
}

// Default field providers.
var (
	UserDefaultID        = func(p specta.Primitives) string { return p.ID() }
	UserDefaultEmail     = func(p specta.Primitives) string { return p.StringWith("email_") }
	UserDefaultFirstName = func(p specta.Primitives) string { return p.StringWith("firstname_") }
	UserDefaultLastName  = func(p specta.Primitives) string { return p.StringWith("lastname_") }
	UserDefaultActive    = func(p specta.Primitives) bool { return p.Bool() }
	UserDefaultAddress   = specta.FromSpec(BuildAddress, NewAddressSpec)
	UserDefaultCreatedAt = func(p specta.Primitives) time.Time { return p.Time() }
	UserDefaultUpdatedAt = func(p specta.Primitives) time.Time { return p.Time() }
)

// BuildUser constructs a User from a UserSpec.
func BuildUser(p specta.Primitives, s UserSpec) showcase.User {
	iD := s.ID.Get(p, UserDefaultID)
	email := s.Email.Get(p, UserDefaultEmail)
	firstName := s.FirstName.Get(p, UserDefaultFirstName)
	lastName := s.LastName.Get(p, UserDefaultLastName)
	active := s.Active.Get(p, UserDefaultActive)
	address := s.Address.Get(p, UserDefaultAddress)
	createdAt := s.CreatedAt.Get(p, UserDefaultCreatedAt)
	updatedAt := s.UpdatedAt.Get(p, UserDefaultUpdatedAt)
	return showcase.User{
		ID:        iD,
		Email:     email,
		FirstName: firstName,
		LastName:  lastName,
		Active:    active,
		Address:   address,
		CreatedAt: createdAt,
		UpdatedAt: updatedAt,
	}
}

// WithUserID sets the ID field to a literal value.
func WithUserID(v string) specta.Opt[UserSpec] {
	return specta.SetLit(func(s *UserSpec, m specta.Maybe[string]) { s.ID = m }, v)
}

// WithUserEmail sets the Email field to a literal value.
func WithUserEmail(v string) specta.Opt[UserSpec] {
	return specta.SetLit(func(s *UserSpec, m specta.Maybe[string]) { s.Email = m }, v)
}

// WithUserFirstName sets the FirstName field to a literal value.
func WithUserFirstName(v string) specta.Opt[UserSpec] {
	return specta.SetLit(func(s *UserSpec, m specta.Maybe[string]) { s.FirstName = m }, v)
}

// WithUserLastName sets the LastName field to a literal value.
func WithUserLastName(v string) specta.Opt[UserSpec] {
	return specta.SetLit(func(s *UserSpec, m specta.Maybe[string]) { s.LastName = m }, v)
}

// WithUserActive sets the Active field to a literal value.
func WithUserActive(v bool) specta.Opt[UserSpec] {
	return specta.SetLit(func(s *UserSpec, m specta.Maybe[bool]) { s.Active = m }, v)
}

// WithUserAddress sets the Address field to a literal value.
func WithUserAddress(v showcase.Address) specta.Opt[UserSpec] {
	return specta.SetLit(func(s *UserSpec, m specta.Maybe[showcase.Address]) { s.Address = m }, v)
}

// WithUserAddressFromProvider sets the Address field using a Provider (evaluated lazily).
func WithUserAddressFromProvider(prov specta.Provider[showcase.Address]) specta.Opt[UserSpec] {
	return specta.SetWith(
		func(s *UserSpec, m specta.Maybe[showcase.Address]) { s.Address = m },
		prov,
	)
}

// WithUserCreatedAt sets the CreatedAt field to a literal value.
func WithUserCreatedAt(v time.Time) specta.Opt[UserSpec] {
	return specta.SetLit(func(s *UserSpec, m specta.Maybe[time.Time]) { s.CreatedAt = m }, v)
}

// WithUserUpdatedAt sets the UpdatedAt field to a literal value.
func WithUserUpdatedAt(v time.Time) specta.Opt[UserSpec] {
	return specta.SetLit(func(s *UserSpec, m specta.Maybe[time.Time]) { s.UpdatedAt = m }, v)
}
