// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package spec

import (
	"time"

	testgen "github.com/james-w/gomatchers"
	"github.com/james-w/gomatchers/showcase"
)

// UserSpec is the low-level specification for building User instances.
// Most users should use UserRecipe from the parent factory package instead.
type UserSpec struct {
	ID        testgen.Maybe[string]
	Email     testgen.Maybe[string]
	FirstName testgen.Maybe[string]
	LastName  testgen.Maybe[string]
	Active    testgen.Maybe[bool]
	Address   testgen.Maybe[showcase.Address]
	CreatedAt testgen.Maybe[time.Time]
	UpdatedAt testgen.Maybe[time.Time]
}

// NewUserSpec creates a new UserSpec with all fields unset.
func NewUserSpec() UserSpec { return UserSpec{} }

// NewUserFactory creates a new SpecFactory for User.
func NewUserFactory(p testgen.Primitives) *testgen.SpecFactory[showcase.User, UserSpec] {
	return testgen.NewSpecFactory(p, NewUserSpec, BuildUser)
}

// Default field providers.
var (
	UserDefaultID        = func(p testgen.Primitives) string { return p.ID() }
	UserDefaultEmail     = func(p testgen.Primitives) string { return p.StringWith("email_") }
	UserDefaultFirstName = func(p testgen.Primitives) string { return p.StringWith("firstname_") }
	UserDefaultLastName  = func(p testgen.Primitives) string { return p.StringWith("lastname_") }
	UserDefaultActive    = func(p testgen.Primitives) bool { return p.Bool() }
	UserDefaultAddress   = testgen.FromSpec(BuildAddress, NewAddressSpec)
	UserDefaultCreatedAt = func(p testgen.Primitives) time.Time { return p.Time() }
	UserDefaultUpdatedAt = func(p testgen.Primitives) time.Time { return p.Time() }
)

// BuildUser constructs a User from a UserSpec.
func BuildUser(p testgen.Primitives, s UserSpec) showcase.User {
	iD := s.ID.Get(p, UserDefaultID)
	email := s.Email.Get(p, UserDefaultEmail)
	firstName := s.FirstName.Get(p, UserDefaultFirstName)
	lastName := s.LastName.Get(p, UserDefaultLastName)
	active := s.Active.Get(p, UserDefaultActive)
	address := s.Address.Get(p, UserDefaultAddress)
	createdAt := s.CreatedAt.Get(p, UserDefaultCreatedAt)
	updatedAt := s.UpdatedAt.Get(p, UserDefaultUpdatedAt)
	return showcase.User{
		ID:        iD,
		Email:     email,
		FirstName: firstName,
		LastName:  lastName,
		Active:    active,
		Address:   address,
		CreatedAt: createdAt,
		UpdatedAt: updatedAt,
	}
}

// WithUserID sets the ID field to a literal value.
func WithUserID(v string) testgen.Opt[UserSpec] {
	return testgen.SetLit(func(s *UserSpec, m testgen.Maybe[string]) { s.ID = m }, v)
}

// WithUserEmail sets the Email field to a literal value.
func WithUserEmail(v string) testgen.Opt[UserSpec] {
	return testgen.SetLit(func(s *UserSpec, m testgen.Maybe[string]) { s.Email = m }, v)
}

// WithUserFirstName sets the FirstName field to a literal value.
func WithUserFirstName(v string) testgen.Opt[UserSpec] {
	return testgen.SetLit(func(s *UserSpec, m testgen.Maybe[string]) { s.FirstName = m }, v)
}

// WithUserLastName sets the LastName field to a literal value.
func WithUserLastName(v string) testgen.Opt[UserSpec] {
	return testgen.SetLit(func(s *UserSpec, m testgen.Maybe[string]) { s.LastName = m }, v)
}

// WithUserActive sets the Active field to a literal value.
func WithUserActive(v bool) testgen.Opt[UserSpec] {
	return testgen.SetLit(func(s *UserSpec, m testgen.Maybe[bool]) { s.Active = m }, v)
}

// WithUserAddress sets the Address field to a literal value.
func WithUserAddress(v showcase.Address) testgen.Opt[UserSpec] {
	return testgen.SetLit(func(s *UserSpec, m testgen.Maybe[showcase.Address]) { s.Address = m }, v)
}

// WithUserAddressFromProvider sets the Address field using a Provider (evaluated lazily).
func WithUserAddressFromProvider(prov testgen.Provider[showcase.Address]) testgen.Opt[UserSpec] {
	return testgen.SetWith(
		func(s *UserSpec, m testgen.Maybe[showcase.Address]) { s.Address = m },
		prov,
	)
}

// WithUserCreatedAt sets the CreatedAt field to a literal value.
func WithUserCreatedAt(v time.Time) testgen.Opt[UserSpec] {
	return testgen.SetLit(func(s *UserSpec, m testgen.Maybe[time.Time]) { s.CreatedAt = m }, v)
}

// WithUserUpdatedAt sets the UpdatedAt field to a literal value.
func WithUserUpdatedAt(v time.Time) testgen.Opt[UserSpec] {
	return testgen.SetLit(func(s *UserSpec, m testgen.Maybe[time.Time]) { s.UpdatedAt = m }, v)
}
