// Package factory provides test data factories and type-safe matchers.
//
// # Overview
//
// This package is generated by specta and provides two main APIs:
//
//  1. Recipes - Fluent builders for creating test data with sensible defaults
//  2. Matchers - Type-safe assertions for validating test results
//
// # Quick Start
//
// Build test data with recipes:
//
//	p := specta.New()
//	view := UserView().Name("Alice").Active(true).Build(p)
//	views := UserView().Many(10, p)  // Create 10 unique instances
//
// Assert with matchers:
//
//	matcher := UserViewMatches().Name(specta.Equal("Alice"))
//	specta.AssertThat(t, actualView, matcher.Matcher())
//
// Combine both with partial matching:
//
//	partial := UserView().Name("Alice").AsEqualMatcher()
//	specta.AssertThat(t, actualView, partial)  // Only checks Name field
//
// # Key Concepts
//
// Recipes use value semantics and deterministic generation via specta.Primitives.
// Matchers provide structured diffs on failure. Partial matching only validates
// fields you explicitly set, making tests resilient to type changes.
//
// # Learn More
//
// See the specta package documentation for details on:
//   - Composition patterns for complex test data
//   - Matcher combinators (AllOf, AnyOf, Not)
//   - Custom matchers and recipe extensions
//   - Primitives for deterministic test data generation
package factory
