// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	testgen "github.com/james-w/gomatchers"
	"github.com/james-w/gomatchers/example"
)

// ============================================================================
// Low-level API: Spec, Build, and Options
// ============================================================================

type ParentSpec struct {
	Child testgen.Maybe[example.UserView]
}

func NewParentSpec() ParentSpec { return ParentSpec{} }

func NewParentFactory(p testgen.Primitives) *testgen.SpecFactory[example.Parent, ParentSpec] {
	return testgen.NewSpecFactory(p, NewParentSpec, BuildParent)
}

// Defaults (simple heuristics).
var (
	ParentDefaultChild = testgen.FromSpec(BuildUserView, NewUserViewSpec)
)

func BuildParent(p testgen.Primitives, s ParentSpec) example.Parent {
	child := s.Child.Get(p, ParentDefaultChild)
	return example.Parent{
		Child: child,
	}
}

func WithParentChild(v example.UserView) testgen.Opt[ParentSpec] {
	return testgen.SetLit(func(s *ParentSpec, m testgen.Maybe[example.UserView]) { s.Child = m }, v)
}

func WithParentChildFromRecipe(rec UserViewRecipe) testgen.Opt[ParentSpec] {
	return testgen.SetWith(
		func(s *ParentSpec, m testgen.Maybe[example.UserView]) { s.Child = m },
		rec.Provider(),
	)
}

// ============================================================================
// High-level Recipe API
// ============================================================================

type ParentRecipe struct{ opts []testgen.Opt[ParentSpec] }

func Parent() ParentRecipe { return ParentRecipe{} }

func (r ParentRecipe) Child(v example.UserView) ParentRecipe {
	r.opts = append(r.opts, WithParentChild(v))
	return r
}

func (r ParentRecipe) ChildFromRecipe(v UserViewRecipe) ParentRecipe {
	r.opts = append(r.opts, WithParentChildFromRecipe(v))
	return r
}

// Provider for nesting into parents (defers evaluation; consumes Primitives later)
func (r ParentRecipe) Provider() testgen.Provider[example.Parent] {
	return testgen.FromSpec(BuildParent, NewParentSpec, r.opts...)
}

// Build now if you need a concrete value (rare in composing tests)
func (r ParentRecipe) Build(p testgen.Primitives) example.Parent {
	return NewParentFactory(p).Make(r.opts...)
}

func (r ParentRecipe) Many(n int, p testgen.Primitives) []example.Parent {
	return NewParentFactory(p).Many(n, r.opts...)
}
