// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	testgen "github.com/james-w/gomatchers"
	"github.com/james-w/gomatchers/example"
)

// ParentMatcher provides a fluent API for matching Parent instances.
type ParentMatcher struct {
	childMatcher testgen.Matcher[example.UserView]
}

// ParentMatches creates a new ParentMatcher for matching Parent instances.
func ParentMatches() ParentMatcher {
	return ParentMatcher{}
}

// Child adds a matcher for the Child field.
func (m ParentMatcher) Child(matcher testgen.Matcher[example.UserView]) ParentMatcher {
	m.childMatcher = matcher
	return m
}

// ChildMatches is a convenience method that accepts a UserViewMatcher.
func (m ParentMatcher) ChildMatches(matcher UserViewMatcher) ParentMatcher {
	m.childMatcher = matcher.Matcher()
	return m
}

// Matcher returns the composed matcher for Parent.
func (m ParentMatcher) Matcher() testgen.Matcher[example.Parent] {
	return testgen.MatcherFunc[example.Parent](func(actual example.Parent) testgen.MatchResult {
		// Extract all field values upfront (call each getter exactly once)
		childValue := actual.Child

		// Build fieldValues map for structured diff
		fieldValues := map[string]any{
			"Child": childValue,
		}

		// Check matchers using cached values and store results
		fieldResults := make(map[string]*testgen.MatchResult)
		hasFailures := false
		if m.childMatcher != nil {
			result := m.childMatcher.Matches(childValue)
			fieldResults["Child"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if hasFailures {
			// Use structured diff for struct types
			structDiff := testgen.BuildMatcherStructDiff("Parent", fieldValues, fieldResults)
			return testgen.MatchResult{
				Matched: false,
				Message: structDiff,
			}
		}
		return testgen.MatchResult{Matched: true}
	})
}
