// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package factory provides a fluent Recipe API for building test data and matchers.
//
// This file contains generated matchers for type-safe assertions.
//
// Example usage:
//
//	// Create a matcher for specific fields
//	matcher := factory.ParentMatches().
//	    Child(specta.Equal(value)).
//	    Matcher()
//	specta.AssertThat(t, actual, matcher)
//
//	// For partial matching, use Recipe.AsEqualMatcher():
//	partial := factory.Parent().Child(value).AsEqualMatcher()
//	specta.AssertThat(t, actual, partial)
package factory

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/example"
)

// ParentMatcher provides a fluent API for matching Parent instances.
type ParentMatcher struct {
	childMatcher specta.Matcher[example.UserView]
}

// ParentMatches creates a new ParentMatcher for matching Parent instances.
//
// This matcher provides methods for the following fields:
//   - Child (example.UserView)
//
// Example:
//
//	matcher := factory.ParentMatches().
//	    Child(specta.Equal(expectedValue)).
//	    Matcher()
//
//	specta.AssertThat(t, actualParent, matcher)
func ParentMatches() ParentMatcher {
	return ParentMatcher{}
}

// Child adds a matcher for the Child field.
func (m ParentMatcher) Child(matcher specta.Matcher[example.UserView]) ParentMatcher {
	m.childMatcher = matcher
	return m
}

// ChildMatches is a convenience method that accepts a UserViewMatcher.
func (m ParentMatcher) ChildMatches(matcher UserViewMatcher) ParentMatcher {
	m.childMatcher = matcher.Matcher()
	return m
}

// Matcher returns the composed matcher for Parent.
func (m ParentMatcher) Matcher() specta.Matcher[example.Parent] {
	return specta.MatcherFunc[example.Parent](func(actual example.Parent) specta.MatchResult {
		// Extract all field values upfront (call each getter exactly once)
		childValue := actual.Child

		// Build fieldValues map for structured diff
		fieldValues := map[string]any{
			"Child": childValue,
		}

		// Check matchers using cached values and store results
		fieldResults := make(map[string]*specta.MatchResult)
		hasFailures := false

		if m.childMatcher != nil {
			result := m.childMatcher.Matches(childValue)
			fieldResults["Child"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if hasFailures {
			// Use structured diff for struct types
			structDiff := specta.BuildMatcherStructDiff("Parent", fieldValues, fieldResults)
			return specta.MatchResult{
				Matched: false,
				Message: structDiff,
			}
		}
		return specta.MatchResult{Matched: true}
	})
}
