// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package factory provides test data factories and type-safe matchers.
//
// # Overview
//
// This package is generated by specta and provides two main APIs:
//
//  1. Recipes - Fluent builders for creating test data with sensible defaults
//  2. Matchers - Type-safe assertions for validating test results
//
// # Quick Start
//
// Build test data with recipes:
//
//	p := specta.New()
//	parent := Parent().Child(value).Build(p)
//	results := Parent().Many(10, p)  // Create 10 unique instances
//
// Assert with matchers:
//
//	matcher := ParentMatches().Child(specta.Equal(value))
//	specta.AssertThat(t, actual, matcher.Matcher())
//
// Combine both with partial matching:
//
//	partial := Parent().Child(value).AsEqualMatcher()
//	specta.AssertThat(t, actual, partial)  // Only checks set fields
//
// # Key Concepts
//
// Recipes use value semantics and deterministic generation via specta.Primitives.
// Matchers provide structured diffs on failure. Partial matching only validates
// fields you explicitly set, making tests resilient to type changes.
//
// # Learn More
//
// See the specta package documentation for details on:
//   - Composition patterns for complex test data
//   - Matcher combinators (AllOf, AnyOf, Not)
//   - Custom matchers and recipe extensions
//   - Primitives for deterministic test data generation
package factory

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/example"
	"github.com/james-w/specta/example/factory/spec"
)

// ParentRecipe provides a fluent API for building Parent instances.
type ParentRecipe struct {
	opts        []specta.Opt[spec.ParentSpec]
	childRecipe *UserViewRecipe
}

// Parent creates a new ParentRecipe for building Parent instances.
//
// This is a struct-based type with the following fields:
//   - Child (example.UserView)
//
// Example:
//
//	p := specta.New()
//	parent := factory.Parent().
//	    Child(value).
//	    Build(p)
func Parent() ParentRecipe { return ParentRecipe{} }

// Child sets the Child field.
func (r ParentRecipe) Child(v example.UserView) ParentRecipe {
	r.opts = append(r.opts, spec.WithParentChild(v))
	r.childRecipe = nil
	return r
}

// ChildFromRecipe sets the Child field using another Recipe (creates unique instances).
// The recipe is captured at call time (value semantics) - subsequent changes to v won't affect this recipe.
// The nested recipe is used for partial matching in AsEqualMatcher.
func (r ParentRecipe) ChildFromRecipe(v UserViewRecipe) ParentRecipe {
	r.opts = append(r.opts, spec.WithParentChildFromProvider(v.Provider()))
	r.childRecipe = &v
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r ParentRecipe) Provider() specta.Provider[example.Parent] {
	return specta.FromSpec(spec.BuildParent, spec.NewParentSpec, r.opts...)
}

// Build creates a single Parent instance.
func (r ParentRecipe) Build(p specta.Primitives) example.Parent {
	return spec.NewParentFactory(p).Make(r.opts...)
}

// Many creates multiple Parent instances with unique generated values.
func (r ParentRecipe) Many(n int, p specta.Primitives) []example.Parent {
	return spec.NewParentFactory(p).Many(n, r.opts...)
}

// AsEqualMatcher converts this Recipe into a Matcher that checks for equality on all set fields.
// Only fields that were explicitly set in the Recipe will be checked - unset fields are ignored.
// This enables partial matching where you only verify specific fields.
// For nested types set via FromRecipe, partial matching is applied recursively.
func (r ParentRecipe) AsEqualMatcher() specta.Matcher[example.Parent] {
	// Apply opts to a spec to see what was set
	s := spec.NewParentSpec()
	for _, opt := range r.opts {
		opt(&s)
	}

	// Use a dummy Primitives to evaluate literal values
	// This works for SetLit values; SetWith/Provider values will be evaluated too
	p := specta.New()

	// Build matcher only for set fields
	m := ParentMatches()
	if s.Child.IsSet() {
		// Check if we have a nested recipe for partial matching
		if r.childRecipe != nil {
			m = m.Child(r.childRecipe.AsEqualMatcher())
		} else {
			m = m.Child(specta.DeepEqual(s.Child.Value(p)))
		}
	}

	return m.Matcher()
}
