// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package factory provides a fluent Recipe API for building test data and matchers.
//
// Example usage:
//
//	// Build a single instance with custom fields
//
//
//	result := UserView().ID("example").Build(specta.New())
//
//
//
//	// Build many instances with unique values
//	results := UserView().Many(5, specta.New())
//
//	// Build a matcher to verify specific fields
//
//
//	matcher := UserViewMatches().ID(specta.DeepEqual("expected"))
//
//
//	specta.AssertThat(t, actual, matcher.Matcher())
//
//	// Convert a recipe to a matcher for partial matching
//
//
//	partialMatcher := UserView().ID("expected").AsEqualMatcher()
//
//
//	specta.AssertThat(t, actual, partialMatcher)
package factory

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/example"
	"github.com/james-w/specta/example/factory/spec"
)

// UserViewRecipe provides a fluent API for building UserView instances.
type UserViewRecipe struct {
	opts []specta.Opt[spec.UserViewSpec]
}

// UserView creates a new UserViewRecipe for building UserView instances.
//
// This is a struct-based type with the following fields:
//   - ID (string)
//   - Name (string)
//   - Active (bool)
//   - Score (int)
//
// Example:
//
//	p := specta.New()
//	userView := factory.UserView().
//	    ID("custom_value").
//	    Name("another").
//	    Build(p)
func UserView() UserViewRecipe { return UserViewRecipe{} }

// ID sets the ID field.
func (r UserViewRecipe) ID(v string) UserViewRecipe {
	r.opts = append(r.opts, spec.WithUserViewID(v))
	return r
}

// Name sets the Name field.
func (r UserViewRecipe) Name(v string) UserViewRecipe {
	r.opts = append(r.opts, spec.WithUserViewName(v))
	return r
}

// Active sets the Active field.
func (r UserViewRecipe) Active(v bool) UserViewRecipe {
	r.opts = append(r.opts, spec.WithUserViewActive(v))
	return r
}

// Score sets the Score field.
func (r UserViewRecipe) Score(v int) UserViewRecipe {
	r.opts = append(r.opts, spec.WithUserViewScore(v))
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r UserViewRecipe) Provider() specta.Provider[example.UserView] {
	return specta.FromSpec(spec.BuildUserView, spec.NewUserViewSpec, r.opts...)
}

// Build creates a single UserView instance.
func (r UserViewRecipe) Build(s specta.Source) example.UserView {
	return spec.NewUserViewFactory(s).Make(r.opts...)
}

// Many creates multiple UserView instances with unique generated values.
func (r UserViewRecipe) Many(n int, s specta.Source) []example.UserView {
	return spec.NewUserViewFactory(s).Many(n, r.opts...)
}

// AsEqualMatcher converts this Recipe into a Matcher that checks for equality on all set fields.
// Only fields that were explicitly set in the Recipe will be checked - unset fields are ignored.
// This enables partial matching where you only verify specific fields.
// For nested types set via FromRecipe, partial matching is applied recursively.
func (r UserViewRecipe) AsEqualMatcher() specta.Matcher[example.UserView] {
	// Apply opts to a spec to see what was set
	s := spec.NewUserViewSpec()
	for _, opt := range r.opts {
		opt(&s)
	}

	// Use a dummy Source to evaluate literal values
	// This works for SetLit values; SetWith/Provider values will be evaluated too
	p := specta.New()

	// Build matcher only for set fields
	m := UserViewMatches()
	if s.ID.IsSet() {
		m = m.ID(specta.DeepEqual(s.ID.Value(p)))
	}
	if s.Name.IsSet() {
		m = m.Name(specta.DeepEqual(s.Name.Value(p)))
	}
	if s.Active.IsSet() {
		m = m.Active(specta.DeepEqual(s.Active.Value(p)))
	}
	if s.Score.IsSet() {
		m = m.Score(specta.DeepEqual(s.Score.Value(p)))
	}

	return m.Matcher()
}
