// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package factory provides a fluent Recipe API for building test data and matchers.
//
// This file contains generated matchers for type-safe assertions.
//
// Example usage:
//
//	// Create a matcher for specific fields
//	matcher := factory.UserViewMatches().
//	    ID(specta.Equal("expected")).
//	    Matcher()
//	specta.AssertThat(t, actual, matcher)
//
//	// For partial matching, use Recipe.AsEqualMatcher():
//	partial := factory.UserView().ID("expected").AsEqualMatcher()
//	specta.AssertThat(t, actual, partial)
package factory

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/example"
)

// UserViewMatcher provides a fluent API for matching UserView instances.
type UserViewMatcher struct {
	iDMatcher     specta.Matcher[string]
	nameMatcher   specta.Matcher[string]
	activeMatcher specta.Matcher[bool]
	scoreMatcher  specta.Matcher[int]
}

// UserViewMatches creates a new UserViewMatcher for matching UserView instances.
//
// This matcher provides methods for the following fields:
//   - ID (string)
//   - Name (string)
//   - Active (bool)
//   - Score (int)
//
// Example:
//
//	matcher := factory.UserViewMatches().
//	    ID(specta.Equal("expected_value")).
//	    Name(specta.Contains("substring")).
//	    Matcher()
//
//	specta.AssertThat(t, actualUserView, matcher)
func UserViewMatches() UserViewMatcher {
	return UserViewMatcher{}
}

// ID adds a matcher for the ID field.
func (m UserViewMatcher) ID(matcher specta.Matcher[string]) UserViewMatcher {
	m.iDMatcher = matcher
	return m
}

// Name adds a matcher for the Name field.
func (m UserViewMatcher) Name(matcher specta.Matcher[string]) UserViewMatcher {
	m.nameMatcher = matcher
	return m
}

// Active adds a matcher for the Active field.
func (m UserViewMatcher) Active(matcher specta.Matcher[bool]) UserViewMatcher {
	m.activeMatcher = matcher
	return m
}

// Score adds a matcher for the Score field.
func (m UserViewMatcher) Score(matcher specta.Matcher[int]) UserViewMatcher {
	m.scoreMatcher = matcher
	return m
}

// Matcher returns the composed matcher for UserView.
func (m UserViewMatcher) Matcher() specta.Matcher[example.UserView] {
	return specta.MatcherFunc[example.UserView](func(actual example.UserView) specta.MatchResult {
		// Extract all field values upfront (call each getter exactly once)
		iDValue := actual.ID
		nameValue := actual.Name
		activeValue := actual.Active
		scoreValue := actual.Score

		// Build fieldValues map for structured diff
		fieldValues := map[string]any{
			"ID":     iDValue,
			"Name":   nameValue,
			"Active": activeValue,
			"Score":  scoreValue,
		}

		// Check matchers using cached values and store results
		fieldResults := make(map[string]*specta.MatchResult)
		hasFailures := false

		if m.iDMatcher != nil {
			result := m.iDMatcher.Matches(iDValue)
			fieldResults["ID"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.nameMatcher != nil {
			result := m.nameMatcher.Matches(nameValue)
			fieldResults["Name"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.activeMatcher != nil {
			result := m.activeMatcher.Matches(activeValue)
			fieldResults["Active"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.scoreMatcher != nil {
			result := m.scoreMatcher.Matches(scoreValue)
			fieldResults["Score"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if hasFailures {
			// Use structured diff for struct types
			structDiff := specta.BuildMatcherStructDiff("UserView", fieldValues, fieldResults)
			return specta.MatchResult{
				Matched: false,
				Message: structDiff,
			}
		}
		return specta.MatchResult{Matched: true}
	})
}
