// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// This file contains the recipe (test data builder) for UserView.
//
// Use UserView() to build instances with custom fields, or Many() for multiple unique instances.
package factory

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/example"
	"github.com/james-w/specta/example/factory/spec"
)

// UserViewRecipe provides a fluent API for building UserView instances.
type UserViewRecipe struct {
	opts []specta.Opt[spec.UserViewSpec]
}

// UserView creates a new UserViewRecipe for building UserView instances.
//
// This is a struct-based type with the following fields:
//   - ID (string)
//   - Name (string)
//   - Active (bool)
//   - Score (int)
//
// Example:
//
//	p := specta.New()
//	userView := factory.UserView().
//	    ID("custom_value").
//	    Name("another").
//	    Build(p)
func UserView() UserViewRecipe { return UserViewRecipe{} }

// ID sets the ID field.
func (r UserViewRecipe) ID(v string) UserViewRecipe {
	r.opts = append(r.opts, spec.WithUserViewID(v))
	return r
}

// IDFromGenerator sets the ID field using a Generator.
func (r UserViewRecipe) IDFromGenerator(gen specta.Generator[string]) UserViewRecipe {
	r.opts = append(r.opts, spec.WithUserViewIDFromGenerator(gen))
	return r
}

// Name sets the Name field.
func (r UserViewRecipe) Name(v string) UserViewRecipe {
	r.opts = append(r.opts, spec.WithUserViewName(v))
	return r
}

// NameFromGenerator sets the Name field using a Generator.
func (r UserViewRecipe) NameFromGenerator(gen specta.Generator[string]) UserViewRecipe {
	r.opts = append(r.opts, spec.WithUserViewNameFromGenerator(gen))
	return r
}

// Active sets the Active field.
func (r UserViewRecipe) Active(v bool) UserViewRecipe {
	r.opts = append(r.opts, spec.WithUserViewActive(v))
	return r
}

// ActiveFromGenerator sets the Active field using a Generator.
func (r UserViewRecipe) ActiveFromGenerator(gen specta.Generator[bool]) UserViewRecipe {
	r.opts = append(r.opts, spec.WithUserViewActiveFromGenerator(gen))
	return r
}

// Score sets the Score field.
func (r UserViewRecipe) Score(v int) UserViewRecipe {
	r.opts = append(r.opts, spec.WithUserViewScore(v))
	return r
}

// ScoreFromGenerator sets the Score field using a Generator.
func (r UserViewRecipe) ScoreFromGenerator(gen specta.Generator[int]) UserViewRecipe {
	r.opts = append(r.opts, spec.WithUserViewScoreFromGenerator(gen))
	return r
}

// Gen returns a Gen[T] for use in nested custom types.
func (r UserViewRecipe) Gen() specta.Gen[example.UserView] {
	return specta.FromSpecGen(spec.BuildUserView, spec.NewUserViewSpec, r.opts...)
}

// Build creates a single UserView instance.
func (r UserViewRecipe) Build(s specta.Source) example.UserView {
	return spec.NewUserViewFactory(s).Make(r.opts...)
}

// Many creates multiple UserView instances with unique generated values.
func (r UserViewRecipe) Many(n int, s specta.Source) []example.UserView {
	return spec.NewUserViewFactory(s).Many(n, r.opts...)
}

// AsEqualMatcher converts this Recipe into a Matcher that checks for equality on all set fields.
// Only fields that were explicitly set in the Recipe will be checked - unset fields are ignored.
// This enables partial matching where you only verify specific fields.
// For nested types set via FromRecipe, partial matching is applied recursively.
func (r UserViewRecipe) AsEqualMatcher() specta.Matcher[example.UserView] {
	// Apply opts to a spec to see what was set
	s := spec.NewUserViewSpec()
	for _, opt := range r.opts {
		opt(&s)
	}

	// Use a dummy Source to evaluate literal values
	// This works for SetLit values; SetWith/Provider values will be evaluated too
	p := specta.New()

	// Build matcher only for set fields
	m := UserViewMatches()
	if s.ID.IsSet() {
		m = m.ID(specta.DeepEqual(s.ID.GetValue(p, "ID")))
	}
	if s.Name.IsSet() {
		m = m.Name(specta.DeepEqual(s.Name.GetValue(p, "Name")))
	}
	if s.Active.IsSet() {
		m = m.Active(specta.DeepEqual(s.Active.GetValue(p, "Active")))
	}
	if s.Score.IsSet() {
		m = m.Score(specta.DeepEqual(s.Score.GetValue(p, "Score")))
	}

	return m
}
