// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewParentSpec()
//	opts := []specta.Opt[ParentSpec]{
//
//
//		WithParentChild(value),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildParent(specta.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewParentFactory(specta.New())
//
//
//	result := factory.Make(WithParentChild(value))
package spec

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/example"
)

// ParentSpec is the low-level specification for building Parent instances.
// Most users should use ParentRecipe from the parent factory package instead.
type ParentSpec struct {
	Child specta.Maybe[example.UserView]
}

// NewParentSpec creates a new ParentSpec with all fields unset.
func NewParentSpec() ParentSpec { return ParentSpec{} }

// NewParentFactory creates a new SpecFactory for Parent.
func NewParentFactory(p specta.Primitives) *specta.SpecFactory[example.Parent, ParentSpec] {
	return specta.NewSpecFactory(p, NewParentSpec, BuildParent)
}

// Default field providers.
var (
	ParentDefaultChild = specta.FromSpec(BuildUserView, NewUserViewSpec)
)

// BuildParent constructs a Parent from a ParentSpec.
func BuildParent(p specta.Primitives, s ParentSpec) example.Parent {
	child := s.Child.Get(p, ParentDefaultChild)
	return example.Parent{
		Child: child,
	}
}

// WithParentChild sets the Child field to a literal value.
func WithParentChild(v example.UserView) specta.Opt[ParentSpec] {
	return specta.SetLit(func(s *ParentSpec, m specta.Maybe[example.UserView]) { s.Child = m }, v)
}

// WithParentChildFromProvider sets the Child field using a Provider (evaluated lazily).
func WithParentChildFromProvider(prov specta.Provider[example.UserView]) specta.Opt[ParentSpec] {
	return specta.SetWith(
		func(s *ParentSpec, m specta.Maybe[example.UserView]) { s.Child = m },
		prov,
	)
}
