// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewUserViewSpec()
//	opts := []specta.Opt[UserViewSpec]{
//
//
//		WithUserViewID("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildUserView(specta.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewUserViewFactory(specta.New())
//
//
//	result := factory.Make(WithUserViewID("example"))
package spec

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/example"
)

// UserViewSpec is the low-level specification for building UserView instances.
// Most users should use UserViewRecipe from the parent factory package instead.
type UserViewSpec struct {
	ID     specta.Maybe[string]
	Name   specta.Maybe[string]
	Active specta.Maybe[bool]
	Score  specta.Maybe[int]
}

// NewUserViewSpec creates a new UserViewSpec with all fields unset.
func NewUserViewSpec() UserViewSpec { return UserViewSpec{} }

// NewUserViewFactory creates a new SpecFactory for UserView.
func NewUserViewFactory(s specta.Source) *specta.SpecFactory[example.UserView, UserViewSpec] {
	return specta.NewSpecFactory(s, NewUserViewSpec, BuildUserView)
}

// Default field generators.
var (
	UserViewIDGenerator     specta.Generator[string] = specta.String().ExampleHint("id_").NonEmpty()
	UserViewNameGenerator   specta.Generator[string] = specta.String().ExampleHint("name_").NonEmpty()
	UserViewActiveGenerator specta.Generator[bool]   = specta.Bool()
	UserViewScoreGenerator  specta.Generator[int]    = specta.Map(specta.Int(), func(v int64) int { return int(v) })
)

// BuildUserView constructs a UserView from a UserViewSpec.
func BuildUserView(s specta.Source, spec UserViewSpec) example.UserView {
	iD := spec.ID.GetWithGenerator(s, "ID", UserViewIDGenerator)
	name := spec.Name.GetWithGenerator(s, "Name", UserViewNameGenerator)
	active := spec.Active.GetWithGenerator(s, "Active", UserViewActiveGenerator)
	score := spec.Score.GetWithGenerator(s, "Score", UserViewScoreGenerator)
	return example.UserView{
		ID:     iD,
		Name:   name,
		Active: active,
		Score:  score,
	}
}

// WithUserViewID sets the ID field to a literal value.
func WithUserViewID(v string) specta.Opt[UserViewSpec] {
	return specta.SetLit(func(s *UserViewSpec, m specta.Maybe[string]) { s.ID = m }, v)
}

// WithUserViewIDFromGenerator sets the ID field using a Generator.
func WithUserViewIDFromGenerator(gen specta.Generator[string]) specta.Opt[UserViewSpec] {
	return func(s *UserViewSpec) {
		s.ID = specta.Some(gen)
	}
}

// WithUserViewName sets the Name field to a literal value.
func WithUserViewName(v string) specta.Opt[UserViewSpec] {
	return specta.SetLit(func(s *UserViewSpec, m specta.Maybe[string]) { s.Name = m }, v)
}

// WithUserViewNameFromGenerator sets the Name field using a Generator.
func WithUserViewNameFromGenerator(gen specta.Generator[string]) specta.Opt[UserViewSpec] {
	return func(s *UserViewSpec) {
		s.Name = specta.Some(gen)
	}
}

// WithUserViewActive sets the Active field to a literal value.
func WithUserViewActive(v bool) specta.Opt[UserViewSpec] {
	return specta.SetLit(func(s *UserViewSpec, m specta.Maybe[bool]) { s.Active = m }, v)
}

// WithUserViewActiveFromGenerator sets the Active field using a Generator.
func WithUserViewActiveFromGenerator(gen specta.Generator[bool]) specta.Opt[UserViewSpec] {
	return func(s *UserViewSpec) {
		s.Active = specta.Some(gen)
	}
}

// WithUserViewScore sets the Score field to a literal value.
func WithUserViewScore(v int) specta.Opt[UserViewSpec] {
	return specta.SetLit(func(s *UserViewSpec, m specta.Maybe[int]) { s.Score = m }, v)
}

// WithUserViewScoreFromGenerator sets the Score field using a Generator.
func WithUserViewScoreFromGenerator(gen specta.Generator[int]) specta.Opt[UserViewSpec] {
	return func(s *UserViewSpec) {
		s.Score = specta.Some(gen)
	}
}
