// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package spec provides low-level specifications for building test data.
//
// Most users should use the high-level Recipe API from the parent factory package instead.
//
// Example usage:
//
//	// Create a spec and set fields explicitly
//	spec := NewUserViewSpec()
//	opts := []specta.Opt[UserViewSpec]{
//
//
//		WithUserViewID("example"),
//
//
//	}
//	for _, opt := range opts {
//		opt(&spec)
//	}
//	result := BuildUserView(specta.New(), spec)
//
//	// Or use a factory for convenience
//	factory := NewUserViewFactory(specta.New())
//
//
//	result := factory.Make(WithUserViewID("example"))
package spec

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/example"
)

// UserViewSpec is the low-level specification for building UserView instances.
// Most users should use UserViewRecipe from the parent factory package instead.
type UserViewSpec struct {
	ID     specta.Maybe[string]
	Name   specta.Maybe[string]
	Active specta.Maybe[bool]
	Score  specta.Maybe[int]
}

// NewUserViewSpec creates a new UserViewSpec with all fields unset.
func NewUserViewSpec() UserViewSpec { return UserViewSpec{} }

// NewUserViewFactory creates a new SpecFactory for UserView.
func NewUserViewFactory(s specta.Source) *specta.SpecFactory[example.UserView, UserViewSpec] {
	return specta.NewSpecFactory(s, NewUserViewSpec, BuildUserView)
}

// Default field providers.
var (
	UserViewDefaultID     = func(s specta.Source) string { return specta.String().ExampleHint("id_").Draw(s, "ID") }
	UserViewDefaultName   = func(s specta.Source) string { return specta.String().ExampleHint("name_").Draw(s, "Name") }
	UserViewDefaultActive = func(s specta.Source) bool { return specta.Bool().Draw(s, "Active") }
	UserViewDefaultScore  = func(s specta.Source) int { return int(specta.Int().Draw(s, "Score")) }
)

// BuildUserView constructs a UserView from a UserViewSpec.
func BuildUserView(s specta.Source, spec UserViewSpec) example.UserView {
	iD := spec.ID.Get(s, UserViewDefaultID)
	name := spec.Name.Get(s, UserViewDefaultName)
	active := spec.Active.Get(s, UserViewDefaultActive)
	score := spec.Score.Get(s, UserViewDefaultScore)
	return example.UserView{
		ID:     iD,
		Name:   name,
		Active: active,
		Score:  score,
	}
}

// WithUserViewID sets the ID field to a literal value.
func WithUserViewID(v string) specta.Opt[UserViewSpec] {
	return specta.SetLit(func(s *UserViewSpec, m specta.Maybe[string]) { s.ID = m }, v)
}

// WithUserViewName sets the Name field to a literal value.
func WithUserViewName(v string) specta.Opt[UserViewSpec] {
	return specta.SetLit(func(s *UserViewSpec, m specta.Maybe[string]) { s.Name = m }, v)
}

// WithUserViewActive sets the Active field to a literal value.
func WithUserViewActive(v bool) specta.Opt[UserViewSpec] {
	return specta.SetLit(func(s *UserViewSpec, m specta.Maybe[bool]) { s.Active = m }, v)
}

// WithUserViewScore sets the Score field to a literal value.
func WithUserViewScore(v int) specta.Opt[UserViewSpec] {
	return specta.SetLit(func(s *UserViewSpec, m specta.Maybe[int]) { s.Score = m }, v)
}
