// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	testgen "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// AccountMatcher provides a fluent API for matching Account instances.
type AccountMatcher struct {
	userMatcher   testgen.Matcher[showcase.User]
	statusMatcher testgen.Matcher[string]
}

// AccountMatches creates a new AccountMatcher for matching Account instances.
//
// This matcher provides methods for properties accessed via getters:
//   - User: matches GetUser() → showcase.User
//   - Status: matches GetStatus() → string
//
// Example:
//
//	matcher := factory.AccountMatches().
//	    User(testgen.Equal(expectedValue)).
//	    Status(testgen.Contains("substring")).
//	    Matcher()
//
//	testgen.AssertThat(t, actualAccount, matcher)
func AccountMatches() AccountMatcher {
	return AccountMatcher{}
}

// User adds a matcher for the User property.
// This property is accessed via the GetUser() method.
func (m AccountMatcher) User(matcher testgen.Matcher[showcase.User]) AccountMatcher {
	m.userMatcher = matcher
	return m
}

// Status adds a matcher for the Status property.
// This property is accessed via the GetStatus() method.
func (m AccountMatcher) Status(matcher testgen.Matcher[string]) AccountMatcher {
	m.statusMatcher = matcher
	return m
}

// Matcher returns the composed matcher for Account.
func (m AccountMatcher) Matcher() testgen.Matcher[showcase.Account] {
	return testgen.MatcherFunc[showcase.Account](func(actual showcase.Account) testgen.MatchResult {
		// Extract all field values upfront (call each getter exactly once)
		userValue := actual.GetUser()
		statusValue := actual.GetStatus()

		// Build fieldValues map for structured diff
		fieldValues := map[string]any{
			"User":   userValue,
			"Status": statusValue,
		}

		// Check matchers using cached values and store results
		fieldResults := make(map[string]*testgen.MatchResult)
		hasFailures := false

		if m.userMatcher != nil {
			result := m.userMatcher.Matches(userValue)
			fieldResults["User"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.statusMatcher != nil {
			result := m.statusMatcher.Matches(statusValue)
			fieldResults["Status"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if hasFailures {
			// Use structured diff for struct types
			structDiff := testgen.BuildMatcherStructDiff("Account", fieldValues, fieldResults)
			return testgen.MatchResult{
				Matched: false,
				Message: structDiff,
			}
		}
		return testgen.MatchResult{Matched: true}
	})
}
