// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// This file contains the recipe (test data builder) for Account.
//
// Use Account() to build instances with custom fields, or Many() for multiple unique instances.

package factory

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
	"github.com/james-w/specta/showcase/factory/spec"
)

// AccountRecipe provides a fluent API for building Account instances.
type AccountRecipe struct {
	opts       []specta.Opt[spec.AccountSpec]
	userRecipe *UserRecipe
}

// Account creates a new AccountRecipe for building Account instances.
//
// The underlying constructor is NewAccount(user showcase.User, status string).
//
// Example:
//
//	p := specta.New()
//	account := factory.Account().
//	    User(value).
//	    Status("another").
//	    Build(p)
func Account() AccountRecipe { return AccountRecipe{} }

// User sets the user parameter of NewAccount.
func (r AccountRecipe) User(v showcase.User) AccountRecipe {
	r.opts = append(r.opts, spec.WithAccountUser(v))
	r.userRecipe = nil
	return r
}

// UserFromRecipe sets the User parameter using another Recipe (creates unique instances).
// The recipe is captured at call time (value semantics) - subsequent changes to v won't affect this recipe.
// The nested recipe is used for partial matching in AsEqualMatcher.
func (r AccountRecipe) UserFromRecipe(v UserRecipe) AccountRecipe {
	r.opts = append(r.opts, spec.WithAccountUserFromProvider(v.Provider()))
	r.userRecipe = &v
	return r
}

// Status sets the status parameter of NewAccount.
func (r AccountRecipe) Status(v string) AccountRecipe {
	r.opts = append(r.opts, spec.WithAccountStatus(v))
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r AccountRecipe) Provider() specta.Provider[showcase.Account] {
	return specta.FromSpec(spec.BuildAccount, spec.NewAccountSpec, r.opts...)
}

// Build creates a single Account instance.
func (r AccountRecipe) Build(p specta.Primitives) showcase.Account {
	return spec.NewAccountFactory(p).Make(r.opts...)
}

// Many creates multiple Account instances with unique generated values.
func (r AccountRecipe) Many(n int, p specta.Primitives) []showcase.Account {
	return spec.NewAccountFactory(p).Many(n, r.opts...)
}

// AsEqualMatcher converts this Recipe into a Matcher that checks for equality on all set fields.
// Only fields that were explicitly set in the Recipe will be checked - unset fields are ignored.
// This enables partial matching where you only verify specific fields.
// For nested types set via FromRecipe, partial matching is applied recursively.
func (r AccountRecipe) AsEqualMatcher() specta.Matcher[showcase.Account] {
	// Constructor-based type with matchers configured: use matcher builder for partial matching
	s := spec.NewAccountSpec()
	for _, opt := range r.opts {
		opt(&s)
	}
	p := specta.New()

	m := AccountMatches()
	if s.User.IsSet() {
		// Use nested recipe for partial matching if available
		if r.userRecipe != nil {
			m = m.User(r.userRecipe.AsEqualMatcher())
		} else {
			m = m.User(specta.Equal(s.User.Value(p)))
		}
	}
	if s.Status.IsSet() {
		m = m.Status(specta.Equal(s.Status.Value(p)))
	}
	return m.Matcher()
}
