// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// This file contains the recipe (test data builder) for Address.
//
// Use Address() to build instances with custom fields, or Many() for multiple unique instances.
package factory

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
	"github.com/james-w/specta/showcase/factory/spec"
)

// AddressRecipe provides a fluent API for building Address instances.
type AddressRecipe struct {
	opts []specta.Opt[spec.AddressSpec]
}

// Address creates a new AddressRecipe for building Address instances.
//
// This is a struct-based type with the following fields:
//   - Street (string)
//   - City (string)
//   - State (string)
//   - ZipCode (string)
//   - Country (string)
//
// Example:
//
//	p := specta.New()
//	address := factory.Address().
//	    Street("custom_value").
//	    City("another").
//	    Build(p)
func Address() AddressRecipe { return AddressRecipe{} }

// Street sets the Street field.
func (r AddressRecipe) Street(v string) AddressRecipe {
	r.opts = append(r.opts, spec.WithAddressStreet(v))
	return r
}

// City sets the City field.
func (r AddressRecipe) City(v string) AddressRecipe {
	r.opts = append(r.opts, spec.WithAddressCity(v))
	return r
}

// State sets the State field.
func (r AddressRecipe) State(v string) AddressRecipe {
	r.opts = append(r.opts, spec.WithAddressState(v))
	return r
}

// ZipCode sets the ZipCode field.
func (r AddressRecipe) ZipCode(v string) AddressRecipe {
	r.opts = append(r.opts, spec.WithAddressZipCode(v))
	return r
}

// Country sets the Country field.
func (r AddressRecipe) Country(v string) AddressRecipe {
	r.opts = append(r.opts, spec.WithAddressCountry(v))
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r AddressRecipe) Provider() specta.Provider[showcase.Address] {
	return specta.FromSpec(spec.BuildAddress, spec.NewAddressSpec, r.opts...)
}

// Build creates a single Address instance.
func (r AddressRecipe) Build(s specta.Source) showcase.Address {
	return spec.NewAddressFactory(s).Make(r.opts...)
}

// Many creates multiple Address instances with unique generated values.
func (r AddressRecipe) Many(n int, s specta.Source) []showcase.Address {
	return spec.NewAddressFactory(s).Many(n, r.opts...)
}

// AsEqualMatcher converts this Recipe into a Matcher that checks for equality on all set fields.
// Only fields that were explicitly set in the Recipe will be checked - unset fields are ignored.
// This enables partial matching where you only verify specific fields.
// For nested types set via FromRecipe, partial matching is applied recursively.
func (r AddressRecipe) AsEqualMatcher() specta.Matcher[showcase.Address] {
	// Apply opts to a spec to see what was set
	s := spec.NewAddressSpec()
	for _, opt := range r.opts {
		opt(&s)
	}

	// Use a dummy Source to evaluate literal values
	// This works for SetLit values; SetWith/Provider values will be evaluated too
	p := specta.New()

	// Build matcher only for set fields
	m := AddressMatches()
	if s.Street.IsSet() {
		m = m.Street(specta.DeepEqual(s.Street.Value(p)))
	}
	if s.City.IsSet() {
		m = m.City(specta.DeepEqual(s.City.Value(p)))
	}
	if s.State.IsSet() {
		m = m.State(specta.DeepEqual(s.State.Value(p)))
	}
	if s.ZipCode.IsSet() {
		m = m.ZipCode(specta.DeepEqual(s.ZipCode.Value(p)))
	}
	if s.Country.IsSet() {
		m = m.Country(specta.DeepEqual(s.Country.Value(p)))
	}

	return m.Matcher()
}
