// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	"fmt"
	testgen "github.com/james-w/gomatchers"
	"github.com/james-w/gomatchers/showcase"
)

// AddressMatcher provides a fluent API for matching Address instances.
type AddressMatcher struct {
	streetMatcher  testgen.Matcher[string]
	cityMatcher    testgen.Matcher[string]
	stateMatcher   testgen.Matcher[string]
	zipCodeMatcher testgen.Matcher[string]
	countryMatcher testgen.Matcher[string]
}

// AddressMatches creates a new AddressMatcher for matching Address instances.
func AddressMatches() AddressMatcher {
	return AddressMatcher{}
}

// Street adds a matcher for the Street field.
func (m AddressMatcher) Street(matcher testgen.Matcher[string]) AddressMatcher {
	m.streetMatcher = matcher
	return m
}

// City adds a matcher for the City field.
func (m AddressMatcher) City(matcher testgen.Matcher[string]) AddressMatcher {
	m.cityMatcher = matcher
	return m
}

// State adds a matcher for the State field.
func (m AddressMatcher) State(matcher testgen.Matcher[string]) AddressMatcher {
	m.stateMatcher = matcher
	return m
}

// ZipCode adds a matcher for the ZipCode field.
func (m AddressMatcher) ZipCode(matcher testgen.Matcher[string]) AddressMatcher {
	m.zipCodeMatcher = matcher
	return m
}

// Country adds a matcher for the Country field.
func (m AddressMatcher) Country(matcher testgen.Matcher[string]) AddressMatcher {
	m.countryMatcher = matcher
	return m
}

// Matcher returns the composed matcher for Address.
func (m AddressMatcher) Matcher() testgen.Matcher[showcase.Address] {
	return testgen.MatcherFunc[showcase.Address](func(actual showcase.Address) testgen.MatchResult {
		var failures []string
		if m.streetMatcher != nil {
			result := m.streetMatcher.Matches(actual.Street)
			if !result.Matched {
				// Add path context if not already present
				path := "Address.Street"
				if result.Path != "" {
					path = "Address." + result.Path
				}
				msg := result.Message
				if result.Expected != nil && result.Actual != nil {
					msg = fmt.Sprintf("%s (at %s)", result.Message, path)
				}
				failures = append(failures, "Street: "+msg)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.cityMatcher != nil {
			result := m.cityMatcher.Matches(actual.City)
			if !result.Matched {
				// Add path context if not already present
				path := "Address.City"
				if result.Path != "" {
					path = "Address." + result.Path
				}
				msg := result.Message
				if result.Expected != nil && result.Actual != nil {
					msg = fmt.Sprintf("%s (at %s)", result.Message, path)
				}
				failures = append(failures, "City: "+msg)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.stateMatcher != nil {
			result := m.stateMatcher.Matches(actual.State)
			if !result.Matched {
				// Add path context if not already present
				path := "Address.State"
				if result.Path != "" {
					path = "Address." + result.Path
				}
				msg := result.Message
				if result.Expected != nil && result.Actual != nil {
					msg = fmt.Sprintf("%s (at %s)", result.Message, path)
				}
				failures = append(failures, "State: "+msg)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.zipCodeMatcher != nil {
			result := m.zipCodeMatcher.Matches(actual.ZipCode)
			if !result.Matched {
				// Add path context if not already present
				path := "Address.ZipCode"
				if result.Path != "" {
					path = "Address." + result.Path
				}
				msg := result.Message
				if result.Expected != nil && result.Actual != nil {
					msg = fmt.Sprintf("%s (at %s)", result.Message, path)
				}
				failures = append(failures, "ZipCode: "+msg)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.countryMatcher != nil {
			result := m.countryMatcher.Matches(actual.Country)
			if !result.Matched {
				// Add path context if not already present
				path := "Address.Country"
				if result.Path != "" {
					path = "Address." + result.Path
				}
				msg := result.Message
				if result.Expected != nil && result.Actual != nil {
					msg = fmt.Sprintf("%s (at %s)", result.Message, path)
				}
				failures = append(failures, "Country: "+msg)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}

		if len(failures) > 0 {
			return testgen.MatchResult{
				Matched: false,
				Message: "Address did not match",
				Details: failures,
			}
		}
		return testgen.MatchResult{Matched: true}
	})
}
