// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	testgen "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// AddressMatcher provides a fluent API for matching Address instances.
type AddressMatcher struct {
	streetMatcher  testgen.Matcher[string]
	cityMatcher    testgen.Matcher[string]
	stateMatcher   testgen.Matcher[string]
	zipCodeMatcher testgen.Matcher[string]
	countryMatcher testgen.Matcher[string]
}

// AddressMatches creates a new AddressMatcher for matching Address instances.
//
// This matcher provides methods for the following fields:
//   - Street (string)
//   - City (string)
//   - State (string)
//   - ZipCode (string)
//   - Country (string)
//
// Example:
//
//	matcher := factory.AddressMatches().
//	    Street(testgen.Equal("expected_value")).
//	    City(testgen.Contains("substring")).
//	    Matcher()
//
//	testgen.AssertThat(t, actualAddress, matcher)
func AddressMatches() AddressMatcher {
	return AddressMatcher{}
}

// Street adds a matcher for the Street field.
func (m AddressMatcher) Street(matcher testgen.Matcher[string]) AddressMatcher {
	m.streetMatcher = matcher
	return m
}

// City adds a matcher for the City field.
func (m AddressMatcher) City(matcher testgen.Matcher[string]) AddressMatcher {
	m.cityMatcher = matcher
	return m
}

// State adds a matcher for the State field.
func (m AddressMatcher) State(matcher testgen.Matcher[string]) AddressMatcher {
	m.stateMatcher = matcher
	return m
}

// ZipCode adds a matcher for the ZipCode field.
func (m AddressMatcher) ZipCode(matcher testgen.Matcher[string]) AddressMatcher {
	m.zipCodeMatcher = matcher
	return m
}

// Country adds a matcher for the Country field.
func (m AddressMatcher) Country(matcher testgen.Matcher[string]) AddressMatcher {
	m.countryMatcher = matcher
	return m
}

// Matcher returns the composed matcher for Address.
func (m AddressMatcher) Matcher() testgen.Matcher[showcase.Address] {
	return testgen.MatcherFunc[showcase.Address](func(actual showcase.Address) testgen.MatchResult {
		// Extract all field values upfront (call each getter exactly once)
		streetValue := actual.Street
		cityValue := actual.City
		stateValue := actual.State
		zipCodeValue := actual.ZipCode
		countryValue := actual.Country

		// Build fieldValues map for structured diff
		fieldValues := map[string]any{
			"Street":  streetValue,
			"City":    cityValue,
			"State":   stateValue,
			"ZipCode": zipCodeValue,
			"Country": countryValue,
		}

		// Check matchers using cached values and store results
		fieldResults := make(map[string]*testgen.MatchResult)
		hasFailures := false

		if m.streetMatcher != nil {
			result := m.streetMatcher.Matches(streetValue)
			fieldResults["Street"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.cityMatcher != nil {
			result := m.cityMatcher.Matches(cityValue)
			fieldResults["City"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.stateMatcher != nil {
			result := m.stateMatcher.Matches(stateValue)
			fieldResults["State"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.zipCodeMatcher != nil {
			result := m.zipCodeMatcher.Matches(zipCodeValue)
			fieldResults["ZipCode"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.countryMatcher != nil {
			result := m.countryMatcher.Matches(countryValue)
			fieldResults["Country"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if hasFailures {
			// Use structured diff for struct types
			structDiff := testgen.BuildMatcherStructDiff("Address", fieldValues, fieldResults)
			return testgen.MatchResult{
				Matched: false,
				Message: structDiff,
			}
		}
		return testgen.MatchResult{Matched: true}
	})
}
