// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	testgen "github.com/james-w/gomatchers"
	"github.com/james-w/gomatchers/showcase"
	"github.com/james-w/gomatchers/showcase/factory/spec"
)

// AddressRecipe provides a fluent API for building Address instances.
type AddressRecipe struct {
	opts []testgen.Opt[spec.AddressSpec]
}

// Address creates a new AddressRecipe for building Address instances.
func Address() AddressRecipe { return AddressRecipe{} }

// Street sets the Street field.
func (r AddressRecipe) Street(v string) AddressRecipe {
	r.opts = append(r.opts, spec.WithAddressStreet(v))
	return r
}

// City sets the City field.
func (r AddressRecipe) City(v string) AddressRecipe {
	r.opts = append(r.opts, spec.WithAddressCity(v))
	return r
}

// State sets the State field.
func (r AddressRecipe) State(v string) AddressRecipe {
	r.opts = append(r.opts, spec.WithAddressState(v))
	return r
}

// ZipCode sets the ZipCode field.
func (r AddressRecipe) ZipCode(v string) AddressRecipe {
	r.opts = append(r.opts, spec.WithAddressZipCode(v))
	return r
}

// Country sets the Country field.
func (r AddressRecipe) Country(v string) AddressRecipe {
	r.opts = append(r.opts, spec.WithAddressCountry(v))
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r AddressRecipe) Provider() testgen.Provider[showcase.Address] {
	return testgen.FromSpec(spec.BuildAddress, spec.NewAddressSpec, r.opts...)
}

// Build creates a single Address instance.
func (r AddressRecipe) Build(p testgen.Primitives) showcase.Address {
	return spec.NewAddressFactory(p).Make(r.opts...)
}

// Many creates multiple Address instances with unique generated values.
func (r AddressRecipe) Many(n int, p testgen.Primitives) []showcase.Address {
	return spec.NewAddressFactory(p).Many(n, r.opts...)
}
