// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package factory provides a fluent Recipe API for building test data and matchers.
//
// This file contains generated matchers for type-safe assertions.
//
// Example usage:
//
//	// Create a matcher for specific fields
//	matcher := factory.AddressMatches().
//	    Street(specta.Equal("expected")).
//	    Matcher()
//	specta.AssertThat(t, actual, matcher)
//
//	// For partial matching, use Recipe.AsEqualMatcher():
//	partial := factory.Address().Street("expected").AsEqualMatcher()
//	specta.AssertThat(t, actual, partial)
package factory

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// AddressMatcher provides a fluent API for matching Address instances.
type AddressMatcher struct {
	streetMatcher  specta.Matcher[string]
	cityMatcher    specta.Matcher[string]
	stateMatcher   specta.Matcher[string]
	zipCodeMatcher specta.Matcher[string]
	countryMatcher specta.Matcher[string]
}

// AddressMatches creates a new AddressMatcher for matching Address instances.
//
// This matcher provides methods for the following fields:
//   - Street (string)
//   - City (string)
//   - State (string)
//   - ZipCode (string)
//   - Country (string)
//
// Example:
//
//	matcher := factory.AddressMatches().
//	    Street(specta.Equal("expected_value")).
//	    City(specta.Contains("substring")).
//	    Matcher()
//
//	specta.AssertThat(t, actualAddress, matcher)
func AddressMatches() AddressMatcher {
	return AddressMatcher{}
}

// Street adds a matcher for the Street field.
func (m AddressMatcher) Street(matcher specta.Matcher[string]) AddressMatcher {
	m.streetMatcher = matcher
	return m
}

// City adds a matcher for the City field.
func (m AddressMatcher) City(matcher specta.Matcher[string]) AddressMatcher {
	m.cityMatcher = matcher
	return m
}

// State adds a matcher for the State field.
func (m AddressMatcher) State(matcher specta.Matcher[string]) AddressMatcher {
	m.stateMatcher = matcher
	return m
}

// ZipCode adds a matcher for the ZipCode field.
func (m AddressMatcher) ZipCode(matcher specta.Matcher[string]) AddressMatcher {
	m.zipCodeMatcher = matcher
	return m
}

// Country adds a matcher for the Country field.
func (m AddressMatcher) Country(matcher specta.Matcher[string]) AddressMatcher {
	m.countryMatcher = matcher
	return m
}

// Matcher returns the composed matcher for Address.
func (m AddressMatcher) Matcher() specta.Matcher[showcase.Address] {
	return specta.MatcherFunc[showcase.Address](func(actual showcase.Address) specta.MatchResult {
		// Extract all field values upfront (call each getter exactly once)
		streetValue := actual.Street
		cityValue := actual.City
		stateValue := actual.State
		zipCodeValue := actual.ZipCode
		countryValue := actual.Country

		// Build fieldValues map for structured diff
		fieldValues := map[string]any{
			"Street":  streetValue,
			"City":    cityValue,
			"State":   stateValue,
			"ZipCode": zipCodeValue,
			"Country": countryValue,
		}

		// Check matchers using cached values and store results
		fieldResults := make(map[string]*specta.MatchResult)
		hasFailures := false

		if m.streetMatcher != nil {
			result := m.streetMatcher.Matches(streetValue)
			fieldResults["Street"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.cityMatcher != nil {
			result := m.cityMatcher.Matches(cityValue)
			fieldResults["City"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.stateMatcher != nil {
			result := m.stateMatcher.Matches(stateValue)
			fieldResults["State"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.zipCodeMatcher != nil {
			result := m.zipCodeMatcher.Matches(zipCodeValue)
			fieldResults["ZipCode"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.countryMatcher != nil {
			result := m.countryMatcher.Matches(countryValue)
			fieldResults["Country"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if hasFailures {
			// Use structured diff for struct types
			structDiff := specta.BuildMatcherStructDiff("Address", fieldValues, fieldResults)
			return specta.MatchResult{
				Matched: false,
				Message: structDiff,
			}
		}
		return specta.MatchResult{Matched: true}
	})
}
