// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// This file contains the recipe (test data builder) for BankAccount.
//
// Use BankAccount() to build instances with custom fields, or Many() for multiple unique instances.

package factory

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
	"github.com/james-w/specta/showcase/factory/spec"
)

// BankAccountRecipe provides a fluent API for building BankAccount instances.
type BankAccountRecipe struct {
	opts []specta.Opt[spec.BankAccountSpec]
}

// BankAccount creates a new BankAccountRecipe for building BankAccount instances.
//
// The underlying constructor is NewBankAccount(name string, balance int).
//
// Example:
//
//	p := specta.New()
//	bankAccount := factory.BankAccount().
//	    Name("custom_value").
//	    Balance(200).
//	    Build(p)
func BankAccount() BankAccountRecipe { return BankAccountRecipe{} }

// Name sets the name parameter of NewBankAccount.
func (r BankAccountRecipe) Name(v string) BankAccountRecipe {
	r.opts = append(r.opts, spec.WithBankAccountName(v))
	return r
}

// Balance sets the balance parameter of NewBankAccount.
func (r BankAccountRecipe) Balance(v int) BankAccountRecipe {
	r.opts = append(r.opts, spec.WithBankAccountBalance(v))
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r BankAccountRecipe) Provider() specta.Provider[showcase.BankAccount] {
	return specta.FromSpec(spec.BuildBankAccount, spec.NewBankAccountSpec, r.opts...)
}

// Build creates a single BankAccount instance.
func (r BankAccountRecipe) Build(p specta.Primitives) showcase.BankAccount {
	return spec.NewBankAccountFactory(p).Make(r.opts...)
}

// Many creates multiple BankAccount instances with unique generated values.
func (r BankAccountRecipe) Many(n int, p specta.Primitives) []showcase.BankAccount {
	return spec.NewBankAccountFactory(p).Many(n, r.opts...)
}

// AsEqualMatcher converts this Recipe into a Matcher that checks for equality on all set fields.
// Only fields that were explicitly set in the Recipe will be checked - unset fields are ignored.
// This enables partial matching where you only verify specific fields.
// For nested types set via FromRecipe, partial matching is applied recursively.
func (r BankAccountRecipe) AsEqualMatcher() specta.Matcher[showcase.BankAccount] {
	// Constructor-based type with matchers configured: use matcher builder for partial matching
	s := spec.NewBankAccountSpec()
	for _, opt := range r.opts {
		opt(&s)
	}
	p := specta.New()

	m := BankAccountMatches()
	if s.Name.IsSet() {
		m = m.Name(specta.Equal(s.Name.Value(p)))
	}
	if s.Balance.IsSet() {
		m = m.Balance(specta.Equal(s.Balance.Value(p)))
	}
	return m.Matcher()
}
