// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// BankAccountMatcher provides a fluent API for matching BankAccount instances.
type BankAccountMatcher struct {
	nameMatcher    specta.Matcher[string]
	balanceMatcher specta.Matcher[int]
}

// BankAccountMatches creates a new BankAccountMatcher for matching BankAccount instances.
func BankAccountMatches() BankAccountMatcher {
	return BankAccountMatcher{}
}

// Name adds a matcher for the Name property (via GetName).
func (m BankAccountMatcher) Name(matcher specta.Matcher[string]) BankAccountMatcher {
	m.nameMatcher = matcher
	return m
}

// Balance adds a matcher for the Balance property (via GetBalance).
func (m BankAccountMatcher) Balance(matcher specta.Matcher[int]) BankAccountMatcher {
	m.balanceMatcher = matcher
	return m
}

// Matcher returns the composed matcher for BankAccount.
func (m BankAccountMatcher) Matcher() specta.Matcher[showcase.BankAccount] {
	return specta.MatcherFunc[showcase.BankAccount](func(actual showcase.BankAccount) specta.MatchResult {
		// Extract all field values upfront (call each getter exactly once)
		nameValue := actual.GetName()
		balanceValue := actual.GetBalance()

		// Build fieldValues map for structured diff
		fieldValues := map[string]any{
			"Name":    nameValue,
			"Balance": balanceValue,
		}

		// Check matchers using cached values and store results
		fieldResults := make(map[string]*specta.MatchResult)
		hasFailures := false

		if m.nameMatcher != nil {
			result := m.nameMatcher.Matches(nameValue)
			fieldResults["Name"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.balanceMatcher != nil {
			result := m.balanceMatcher.Matches(balanceValue)
			fieldResults["Balance"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if hasFailures {
			// Use structured diff for struct types
			structDiff := specta.BuildMatcherStructDiff("BankAccount", fieldValues, fieldResults)
			return specta.MatchResult{
				Matched: false,
				Message: structDiff,
			}
		}
		return specta.MatchResult{Matched: true}
	})
}
