// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	testgen "github.com/james-w/gomatchers"
	"github.com/james-w/gomatchers/showcase"
)

// BankAccountMatcher provides a fluent API for matching BankAccount instances.
type BankAccountMatcher struct {
}

// BankAccountMatches creates a new BankAccountMatcher for matching BankAccount instances.
func BankAccountMatches() BankAccountMatcher {
	return BankAccountMatcher{}
}

// Matcher returns the composed matcher for BankAccount.
func (m BankAccountMatcher) Matcher() testgen.Matcher[showcase.BankAccount] {
	return testgen.MatcherFunc[showcase.BankAccount](func(actual showcase.BankAccount) testgen.MatchResult {
		var failures []string

		if len(failures) > 0 {
			return testgen.MatchResult{
				Matched: false,
				Message: "BankAccount did not match",
				Details: failures,
			}
		}
		return testgen.MatchResult{Matched: true}
	})
}
