// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	"time"

	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// BlogPostMatcher provides a fluent API for matching BlogPost instances.
type BlogPostMatcher struct {
	iDMatcher          specta.Matcher[string]
	titleMatcher       specta.Matcher[string]
	contentMatcher     specta.Matcher[string]
	authorMatcher      specta.Matcher[showcase.User]
	publishedMatcher   specta.Matcher[bool]
	publishedAtMatcher specta.Matcher[time.Time]
	createdAtMatcher   specta.Matcher[time.Time]
	updatedAtMatcher   specta.Matcher[time.Time]
}

// BlogPostMatches creates a new BlogPostMatcher for matching BlogPost instances.
func BlogPostMatches() BlogPostMatcher {
	return BlogPostMatcher{}
}

// ID adds a matcher for the ID field.
func (m BlogPostMatcher) ID(matcher specta.Matcher[string]) BlogPostMatcher {
	m.iDMatcher = matcher
	return m
}

// Title adds a matcher for the Title field.
func (m BlogPostMatcher) Title(matcher specta.Matcher[string]) BlogPostMatcher {
	m.titleMatcher = matcher
	return m
}

// Content adds a matcher for the Content field.
func (m BlogPostMatcher) Content(matcher specta.Matcher[string]) BlogPostMatcher {
	m.contentMatcher = matcher
	return m
}

// Author adds a matcher for the Author field.
func (m BlogPostMatcher) Author(matcher specta.Matcher[showcase.User]) BlogPostMatcher {
	m.authorMatcher = matcher
	return m
}

// AuthorMatches is a convenience method that accepts a UserMatcher.
func (m BlogPostMatcher) AuthorMatches(matcher UserMatcher) BlogPostMatcher {
	m.authorMatcher = matcher.Matcher()
	return m
}

// Published adds a matcher for the Published field.
func (m BlogPostMatcher) Published(matcher specta.Matcher[bool]) BlogPostMatcher {
	m.publishedMatcher = matcher
	return m
}

// PublishedAt adds a matcher for the PublishedAt field.
func (m BlogPostMatcher) PublishedAt(matcher specta.Matcher[time.Time]) BlogPostMatcher {
	m.publishedAtMatcher = matcher
	return m
}

// CreatedAt adds a matcher for the CreatedAt field.
func (m BlogPostMatcher) CreatedAt(matcher specta.Matcher[time.Time]) BlogPostMatcher {
	m.createdAtMatcher = matcher
	return m
}

// UpdatedAt adds a matcher for the UpdatedAt field.
func (m BlogPostMatcher) UpdatedAt(matcher specta.Matcher[time.Time]) BlogPostMatcher {
	m.updatedAtMatcher = matcher
	return m
}

// Matcher returns the composed matcher for BlogPost.
func (m BlogPostMatcher) Matcher() specta.Matcher[showcase.BlogPost] {
	return specta.MatcherFunc[showcase.BlogPost](func(actual showcase.BlogPost) specta.MatchResult {
		// Extract all field values upfront (call each getter exactly once)
		iDValue := actual.ID
		titleValue := actual.Title
		contentValue := actual.Content
		authorValue := actual.Author
		publishedValue := actual.Published
		publishedAtValue := actual.PublishedAt
		createdAtValue := actual.CreatedAt
		updatedAtValue := actual.UpdatedAt

		// Build fieldValues map for structured diff
		fieldValues := map[string]any{
			"ID":          iDValue,
			"Title":       titleValue,
			"Content":     contentValue,
			"Author":      authorValue,
			"Published":   publishedValue,
			"PublishedAt": publishedAtValue,
			"CreatedAt":   createdAtValue,
			"UpdatedAt":   updatedAtValue,
		}

		// Check matchers using cached values and store results
		fieldResults := make(map[string]*specta.MatchResult)
		hasFailures := false

		if m.iDMatcher != nil {
			result := m.iDMatcher.Matches(iDValue)
			fieldResults["ID"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.titleMatcher != nil {
			result := m.titleMatcher.Matches(titleValue)
			fieldResults["Title"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.contentMatcher != nil {
			result := m.contentMatcher.Matches(contentValue)
			fieldResults["Content"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.authorMatcher != nil {
			result := m.authorMatcher.Matches(authorValue)
			fieldResults["Author"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.publishedMatcher != nil {
			result := m.publishedMatcher.Matches(publishedValue)
			fieldResults["Published"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.publishedAtMatcher != nil {
			result := m.publishedAtMatcher.Matches(publishedAtValue)
			fieldResults["PublishedAt"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.createdAtMatcher != nil {
			result := m.createdAtMatcher.Matches(createdAtValue)
			fieldResults["CreatedAt"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.updatedAtMatcher != nil {
			result := m.updatedAtMatcher.Matches(updatedAtValue)
			fieldResults["UpdatedAt"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if hasFailures {
			// Use structured diff for struct types
			structDiff := specta.BuildMatcherStructDiff("BlogPost", fieldValues, fieldResults)
			return specta.MatchResult{
				Matched: false,
				Message: structDiff,
			}
		}
		return specta.MatchResult{Matched: true}
	})
}
