// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	"time"

	testgen "github.com/james-w/gomatchers"
	"github.com/james-w/gomatchers/showcase"
	"github.com/james-w/gomatchers/showcase/factory/spec"
)

// BlogPostRecipe provides a fluent API for building BlogPost instances.
type BlogPostRecipe struct {
	opts []testgen.Opt[spec.BlogPostSpec]
}

// BlogPost creates a new BlogPostRecipe for building BlogPost instances.
func BlogPost() BlogPostRecipe { return BlogPostRecipe{} }

// ID sets the ID field.
func (r BlogPostRecipe) ID(v string) BlogPostRecipe {
	r.opts = append(r.opts, spec.WithBlogPostID(v))
	return r
}

// Title sets the Title field.
func (r BlogPostRecipe) Title(v string) BlogPostRecipe {
	r.opts = append(r.opts, spec.WithBlogPostTitle(v))
	return r
}

// Content sets the Content field.
func (r BlogPostRecipe) Content(v string) BlogPostRecipe {
	r.opts = append(r.opts, spec.WithBlogPostContent(v))
	return r
}

// Author sets the Author field.
func (r BlogPostRecipe) Author(v showcase.User) BlogPostRecipe {
	r.opts = append(r.opts, spec.WithBlogPostAuthor(v))
	return r
}

// AuthorFromRecipe sets the Author field using another Recipe (creates unique instances).
func (r BlogPostRecipe) AuthorFromRecipe(v UserRecipe) BlogPostRecipe {
	r.opts = append(r.opts, spec.WithBlogPostAuthorFromProvider(v.Provider()))
	return r
}

// Published sets the Published field.
func (r BlogPostRecipe) Published(v bool) BlogPostRecipe {
	r.opts = append(r.opts, spec.WithBlogPostPublished(v))
	return r
}

// PublishedAt sets the PublishedAt field.
func (r BlogPostRecipe) PublishedAt(v time.Time) BlogPostRecipe {
	r.opts = append(r.opts, spec.WithBlogPostPublishedAt(v))
	return r
}

// CreatedAt sets the CreatedAt field.
func (r BlogPostRecipe) CreatedAt(v time.Time) BlogPostRecipe {
	r.opts = append(r.opts, spec.WithBlogPostCreatedAt(v))
	return r
}

// UpdatedAt sets the UpdatedAt field.
func (r BlogPostRecipe) UpdatedAt(v time.Time) BlogPostRecipe {
	r.opts = append(r.opts, spec.WithBlogPostUpdatedAt(v))
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r BlogPostRecipe) Provider() testgen.Provider[showcase.BlogPost] {
	return testgen.FromSpec(spec.BuildBlogPost, spec.NewBlogPostSpec, r.opts...)
}

// Build creates a single BlogPost instance.
func (r BlogPostRecipe) Build(p testgen.Primitives) showcase.BlogPost {
	return spec.NewBlogPostFactory(p).Make(r.opts...)
}

// Many creates multiple BlogPost instances with unique generated values.
func (r BlogPostRecipe) Many(n int, p testgen.Primitives) []showcase.BlogPost {
	return spec.NewBlogPostFactory(p).Many(n, r.opts...)
}
