// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	"time"

	testgen "github.com/james-w/gomatchers"
	"github.com/james-w/gomatchers/showcase"
)

// BlogPostMatcher provides a fluent API for matching BlogPost instances.
type BlogPostMatcher struct {
	iDMatcher          testgen.Matcher[string]
	titleMatcher       testgen.Matcher[string]
	contentMatcher     testgen.Matcher[string]
	authorMatcher      testgen.Matcher[showcase.User]
	publishedMatcher   testgen.Matcher[bool]
	publishedAtMatcher testgen.Matcher[time.Time]
	createdAtMatcher   testgen.Matcher[time.Time]
	updatedAtMatcher   testgen.Matcher[time.Time]
}

// BlogPostMatches creates a new BlogPostMatcher for matching BlogPost instances.
func BlogPostMatches() BlogPostMatcher {
	return BlogPostMatcher{}
}

// ID adds a matcher for the ID field.
func (m BlogPostMatcher) ID(matcher testgen.Matcher[string]) BlogPostMatcher {
	m.iDMatcher = matcher
	return m
}

// Title adds a matcher for the Title field.
func (m BlogPostMatcher) Title(matcher testgen.Matcher[string]) BlogPostMatcher {
	m.titleMatcher = matcher
	return m
}

// Content adds a matcher for the Content field.
func (m BlogPostMatcher) Content(matcher testgen.Matcher[string]) BlogPostMatcher {
	m.contentMatcher = matcher
	return m
}

// Author adds a matcher for the Author field.
func (m BlogPostMatcher) Author(matcher testgen.Matcher[showcase.User]) BlogPostMatcher {
	m.authorMatcher = matcher
	return m
}

// AuthorMatches is a convenience method that accepts a UserMatcher.
func (m BlogPostMatcher) AuthorMatches(matcher UserMatcher) BlogPostMatcher {
	m.authorMatcher = matcher.Matcher()
	return m
}

// Published adds a matcher for the Published field.
func (m BlogPostMatcher) Published(matcher testgen.Matcher[bool]) BlogPostMatcher {
	m.publishedMatcher = matcher
	return m
}

// PublishedAt adds a matcher for the PublishedAt field.
func (m BlogPostMatcher) PublishedAt(matcher testgen.Matcher[time.Time]) BlogPostMatcher {
	m.publishedAtMatcher = matcher
	return m
}

// CreatedAt adds a matcher for the CreatedAt field.
func (m BlogPostMatcher) CreatedAt(matcher testgen.Matcher[time.Time]) BlogPostMatcher {
	m.createdAtMatcher = matcher
	return m
}

// UpdatedAt adds a matcher for the UpdatedAt field.
func (m BlogPostMatcher) UpdatedAt(matcher testgen.Matcher[time.Time]) BlogPostMatcher {
	m.updatedAtMatcher = matcher
	return m
}

// Matcher returns the composed matcher for BlogPost.
func (m BlogPostMatcher) Matcher() testgen.Matcher[showcase.BlogPost] {
	return testgen.MatcherFunc[showcase.BlogPost](func(actual showcase.BlogPost) testgen.MatchResult {
		var failures []string
		if m.iDMatcher != nil {
			result := m.iDMatcher.Matches(actual.ID)
			if !result.Matched {
				failures = append(failures, "ID: "+result.Message)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.titleMatcher != nil {
			result := m.titleMatcher.Matches(actual.Title)
			if !result.Matched {
				failures = append(failures, "Title: "+result.Message)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.contentMatcher != nil {
			result := m.contentMatcher.Matches(actual.Content)
			if !result.Matched {
				failures = append(failures, "Content: "+result.Message)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.authorMatcher != nil {
			result := m.authorMatcher.Matches(actual.Author)
			if !result.Matched {
				failures = append(failures, "Author: "+result.Message)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.publishedMatcher != nil {
			result := m.publishedMatcher.Matches(actual.Published)
			if !result.Matched {
				failures = append(failures, "Published: "+result.Message)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.publishedAtMatcher != nil {
			result := m.publishedAtMatcher.Matches(actual.PublishedAt)
			if !result.Matched {
				failures = append(failures, "PublishedAt: "+result.Message)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.createdAtMatcher != nil {
			result := m.createdAtMatcher.Matches(actual.CreatedAt)
			if !result.Matched {
				failures = append(failures, "CreatedAt: "+result.Message)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.updatedAtMatcher != nil {
			result := m.updatedAtMatcher.Matches(actual.UpdatedAt)
			if !result.Matched {
				failures = append(failures, "UpdatedAt: "+result.Message)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}

		if len(failures) > 0 {
			return testgen.MatchResult{
				Matched: false,
				Message: "BlogPost did not match",
				Details: failures,
			}
		}
		return testgen.MatchResult{Matched: true}
	})
}
