// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package factory provides a fluent Recipe API for building test data and matchers.
//
// Example usage:
//
//	// Build a single instance with custom fields
//
//
//	result := Comment().ID("example").Build(specta.New())
//
//
//
//	// Build many instances with unique values
//	results := Comment().Many(5, specta.New())
//
//	// Build a matcher to verify specific fields
//
//
//	matcher := CommentMatches().ID(specta.DeepEqual("expected"))
//
//
//	specta.AssertThat(t, actual, matcher.Matcher())
//
//	// Convert a recipe to a matcher for partial matching
//
//
//	partialMatcher := Comment().ID("expected").AsEqualMatcher()
//
//
//	specta.AssertThat(t, actual, partialMatcher)
package factory

import (
	"time"

	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
	"github.com/james-w/specta/showcase/factory/spec"
)

// CommentRecipe provides a fluent API for building Comment instances.
type CommentRecipe struct {
	opts         []specta.Opt[spec.CommentSpec]
	postRecipe   *BlogPostRecipe
	authorRecipe *UserRecipe
}

// Comment creates a new CommentRecipe for building Comment instances.
//
// This is a struct-based type with the following fields:
//   - ID (string)
//   - Post (showcase.BlogPost)
//   - Author (showcase.User)
//   - Content (string)
//   - CreatedAt (time.Time)
//
// Example:
//
//	p := specta.New()
//	comment := factory.Comment().
//	    ID("custom_value").
//	    Post(value).
//	    Build(p)
func Comment() CommentRecipe { return CommentRecipe{} }

// ID sets the ID field.
func (r CommentRecipe) ID(v string) CommentRecipe {
	r.opts = append(r.opts, spec.WithCommentID(v))
	return r
}

// Post sets the Post field.
func (r CommentRecipe) Post(v showcase.BlogPost) CommentRecipe {
	r.opts = append(r.opts, spec.WithCommentPost(v))
	r.postRecipe = nil
	return r
}

// PostFromRecipe sets the Post field using another Recipe (creates unique instances).
// The recipe is captured at call time (value semantics) - subsequent changes to v won't affect this recipe.
// The nested recipe is used for partial matching in AsEqualMatcher.
func (r CommentRecipe) PostFromRecipe(v BlogPostRecipe) CommentRecipe {
	r.opts = append(r.opts, spec.WithCommentPostFromProvider(v.Provider()))
	r.postRecipe = &v
	return r
}

// Author sets the Author field.
func (r CommentRecipe) Author(v showcase.User) CommentRecipe {
	r.opts = append(r.opts, spec.WithCommentAuthor(v))
	r.authorRecipe = nil
	return r
}

// AuthorFromRecipe sets the Author field using another Recipe (creates unique instances).
// The recipe is captured at call time (value semantics) - subsequent changes to v won't affect this recipe.
// The nested recipe is used for partial matching in AsEqualMatcher.
func (r CommentRecipe) AuthorFromRecipe(v UserRecipe) CommentRecipe {
	r.opts = append(r.opts, spec.WithCommentAuthorFromProvider(v.Provider()))
	r.authorRecipe = &v
	return r
}

// Content sets the Content field.
func (r CommentRecipe) Content(v string) CommentRecipe {
	r.opts = append(r.opts, spec.WithCommentContent(v))
	return r
}

// CreatedAt sets the CreatedAt field.
func (r CommentRecipe) CreatedAt(v time.Time) CommentRecipe {
	r.opts = append(r.opts, spec.WithCommentCreatedAt(v))
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r CommentRecipe) Provider() specta.Provider[showcase.Comment] {
	return specta.FromSpec(spec.BuildComment, spec.NewCommentSpec, r.opts...)
}

// Build creates a single Comment instance.
func (r CommentRecipe) Build(s specta.Source) showcase.Comment {
	return spec.NewCommentFactory(s).Make(r.opts...)
}

// Many creates multiple Comment instances with unique generated values.
func (r CommentRecipe) Many(n int, s specta.Source) []showcase.Comment {
	return spec.NewCommentFactory(s).Many(n, r.opts...)
}

// AsEqualMatcher converts this Recipe into a Matcher that checks for equality on all set fields.
// Only fields that were explicitly set in the Recipe will be checked - unset fields are ignored.
// This enables partial matching where you only verify specific fields.
// For nested types set via FromRecipe, partial matching is applied recursively.
func (r CommentRecipe) AsEqualMatcher() specta.Matcher[showcase.Comment] {
	// Apply opts to a spec to see what was set
	s := spec.NewCommentSpec()
	for _, opt := range r.opts {
		opt(&s)
	}

	// Use a dummy Source to evaluate literal values
	// This works for SetLit values; SetWith/Provider values will be evaluated too
	p := specta.New()

	// Build matcher only for set fields
	m := CommentMatches()
	if s.ID.IsSet() {
		m = m.ID(specta.DeepEqual(s.ID.Value(p)))
	}
	if s.Post.IsSet() {
		// Check if we have a nested recipe for partial matching
		if r.postRecipe != nil {
			m = m.Post(r.postRecipe.AsEqualMatcher())
		} else {
			m = m.Post(specta.DeepEqual(s.Post.Value(p)))
		}
	}
	if s.Author.IsSet() {
		// Check if we have a nested recipe for partial matching
		if r.authorRecipe != nil {
			m = m.Author(r.authorRecipe.AsEqualMatcher())
		} else {
			m = m.Author(specta.DeepEqual(s.Author.Value(p)))
		}
	}
	if s.Content.IsSet() {
		m = m.Content(specta.DeepEqual(s.Content.Value(p)))
	}
	if s.CreatedAt.IsSet() {
		m = m.CreatedAt(specta.DeepEqual(s.CreatedAt.Value(p)))
	}

	return m.Matcher()
}
