// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// This file contains generated matchers for Comment.
//
// Use CommentMatches() to build type-safe matchers for assertions,
// or use Comment().AsEqualMatcher() for partial matching based on recipes.

package factory

import (
	"time"

	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// CommentMatcher provides a fluent API for matching Comment instances.
type CommentMatcher struct {
	iDMatcher        specta.Matcher[string]
	postMatcher      specta.Matcher[showcase.BlogPost]
	authorMatcher    specta.Matcher[showcase.User]
	contentMatcher   specta.Matcher[string]
	createdAtMatcher specta.Matcher[time.Time]
}

// CommentMatches creates a new CommentMatcher for matching Comment instances.
//
// This matcher provides methods for the following fields:
//   - ID (string)
//   - Post (showcase.BlogPost)
//   - Author (showcase.User)
//   - Content (string)
//   - CreatedAt (time.Time)
//
// Example:
//
//	matcher := factory.CommentMatches().
//	    ID(specta.Equal("expected_value")).
//	    Post(specta.Equal(expectedValue))
//
//	specta.AssertThat(t, actualComment, matcher)
func CommentMatches() CommentMatcher {
	return CommentMatcher{}
}

// ID adds a matcher for the ID field.
func (m CommentMatcher) ID(matcher specta.Matcher[string]) CommentMatcher {
	m.iDMatcher = matcher
	return m
}

// Post adds a matcher for the Post field.
func (m CommentMatcher) Post(matcher specta.Matcher[showcase.BlogPost]) CommentMatcher {
	m.postMatcher = matcher
	return m
}

// Author adds a matcher for the Author field.
func (m CommentMatcher) Author(matcher specta.Matcher[showcase.User]) CommentMatcher {
	m.authorMatcher = matcher
	return m
}

// Content adds a matcher for the Content field.
func (m CommentMatcher) Content(matcher specta.Matcher[string]) CommentMatcher {
	m.contentMatcher = matcher
	return m
}

// CreatedAt adds a matcher for the CreatedAt field.
func (m CommentMatcher) CreatedAt(matcher specta.Matcher[time.Time]) CommentMatcher {
	m.createdAtMatcher = matcher
	return m
}

// Matches implements the Matcher[Comment] interface.
func (m CommentMatcher) Matches(actual showcase.Comment) specta.MatchResult {
	// Extract all field values upfront (call each getter exactly once)
	iDValue := actual.ID
	postValue := actual.Post
	authorValue := actual.Author
	contentValue := actual.Content
	createdAtValue := actual.CreatedAt

	// Build fieldValues map for structured diff
	fieldValues := map[string]any{
		"ID":        iDValue,
		"Post":      postValue,
		"Author":    authorValue,
		"Content":   contentValue,
		"CreatedAt": createdAtValue,
	}

	// Check matchers using cached values and store results
	fieldResults := make(map[string]*specta.MatchResult)
	hasFailures := false

	if m.iDMatcher != nil {
		result := m.iDMatcher.Matches(iDValue)
		fieldResults["ID"] = &result
		if !result.Matched {
			hasFailures = true
		}
	}

	if m.postMatcher != nil {
		result := m.postMatcher.Matches(postValue)
		fieldResults["Post"] = &result
		if !result.Matched {
			hasFailures = true
		}
	}

	if m.authorMatcher != nil {
		result := m.authorMatcher.Matches(authorValue)
		fieldResults["Author"] = &result
		if !result.Matched {
			hasFailures = true
		}
	}

	if m.contentMatcher != nil {
		result := m.contentMatcher.Matches(contentValue)
		fieldResults["Content"] = &result
		if !result.Matched {
			hasFailures = true
		}
	}

	if m.createdAtMatcher != nil {
		result := m.createdAtMatcher.Matches(createdAtValue)
		fieldResults["CreatedAt"] = &result
		if !result.Matched {
			hasFailures = true
		}
	}

	if hasFailures {
		// Use structured diff for struct types
		structDiff := specta.BuildMatcherStructDiff("Comment", fieldValues, fieldResults)
		return specta.MatchResult{
			Matched: false,
			Message: structDiff,
		}
	}
	return specta.MatchResult{Matched: true}
}
