// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	"time"

	testgen "github.com/james-w/gomatchers"
	"github.com/james-w/gomatchers/showcase"
	"github.com/james-w/gomatchers/showcase/factory/spec"
)

// CommentRecipe provides a fluent API for building Comment instances.
type CommentRecipe struct {
	opts []testgen.Opt[spec.CommentSpec]
}

// Comment creates a new CommentRecipe for building Comment instances.
func Comment() CommentRecipe { return CommentRecipe{} }

// ID sets the ID field.
func (r CommentRecipe) ID(v string) CommentRecipe {
	r.opts = append(r.opts, spec.WithCommentID(v))
	return r
}

// Post sets the Post field.
func (r CommentRecipe) Post(v showcase.BlogPost) CommentRecipe {
	r.opts = append(r.opts, spec.WithCommentPost(v))
	return r
}

// PostFromRecipe sets the Post field using another Recipe (creates unique instances).
func (r CommentRecipe) PostFromRecipe(v BlogPostRecipe) CommentRecipe {
	r.opts = append(r.opts, spec.WithCommentPostFromProvider(v.Provider()))
	return r
}

// Author sets the Author field.
func (r CommentRecipe) Author(v showcase.User) CommentRecipe {
	r.opts = append(r.opts, spec.WithCommentAuthor(v))
	return r
}

// AuthorFromRecipe sets the Author field using another Recipe (creates unique instances).
func (r CommentRecipe) AuthorFromRecipe(v UserRecipe) CommentRecipe {
	r.opts = append(r.opts, spec.WithCommentAuthorFromProvider(v.Provider()))
	return r
}

// Content sets the Content field.
func (r CommentRecipe) Content(v string) CommentRecipe {
	r.opts = append(r.opts, spec.WithCommentContent(v))
	return r
}

// CreatedAt sets the CreatedAt field.
func (r CommentRecipe) CreatedAt(v time.Time) CommentRecipe {
	r.opts = append(r.opts, spec.WithCommentCreatedAt(v))
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r CommentRecipe) Provider() testgen.Provider[showcase.Comment] {
	return testgen.FromSpec(spec.BuildComment, spec.NewCommentSpec, r.opts...)
}

// Build creates a single Comment instance.
func (r CommentRecipe) Build(p testgen.Primitives) showcase.Comment {
	return spec.NewCommentFactory(p).Make(r.opts...)
}

// Many creates multiple Comment instances with unique generated values.
func (r CommentRecipe) Many(n int, p testgen.Primitives) []showcase.Comment {
	return spec.NewCommentFactory(p).Many(n, r.opts...)
}
