// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	"time"

	testgen "github.com/james-w/gomatchers"
	"github.com/james-w/gomatchers/showcase"
)

// CommentMatcher provides a fluent API for matching Comment instances.
type CommentMatcher struct {
	iDMatcher        testgen.Matcher[string]
	postMatcher      testgen.Matcher[showcase.BlogPost]
	authorMatcher    testgen.Matcher[showcase.User]
	contentMatcher   testgen.Matcher[string]
	createdAtMatcher testgen.Matcher[time.Time]
}

// CommentMatches creates a new CommentMatcher for matching Comment instances.
func CommentMatches() CommentMatcher {
	return CommentMatcher{}
}

// ID adds a matcher for the ID field.
func (m CommentMatcher) ID(matcher testgen.Matcher[string]) CommentMatcher {
	m.iDMatcher = matcher
	return m
}

// Post adds a matcher for the Post field.
func (m CommentMatcher) Post(matcher testgen.Matcher[showcase.BlogPost]) CommentMatcher {
	m.postMatcher = matcher
	return m
}

// PostMatches is a convenience method that accepts a BlogPostMatcher.
func (m CommentMatcher) PostMatches(matcher BlogPostMatcher) CommentMatcher {
	m.postMatcher = matcher.Matcher()
	return m
}

// Author adds a matcher for the Author field.
func (m CommentMatcher) Author(matcher testgen.Matcher[showcase.User]) CommentMatcher {
	m.authorMatcher = matcher
	return m
}

// AuthorMatches is a convenience method that accepts a UserMatcher.
func (m CommentMatcher) AuthorMatches(matcher UserMatcher) CommentMatcher {
	m.authorMatcher = matcher.Matcher()
	return m
}

// Content adds a matcher for the Content field.
func (m CommentMatcher) Content(matcher testgen.Matcher[string]) CommentMatcher {
	m.contentMatcher = matcher
	return m
}

// CreatedAt adds a matcher for the CreatedAt field.
func (m CommentMatcher) CreatedAt(matcher testgen.Matcher[time.Time]) CommentMatcher {
	m.createdAtMatcher = matcher
	return m
}

// Matcher returns the composed matcher for Comment.
func (m CommentMatcher) Matcher() testgen.Matcher[showcase.Comment] {
	return testgen.MatcherFunc[showcase.Comment](func(actual showcase.Comment) testgen.MatchResult {
		var failures []string
		if m.iDMatcher != nil {
			result := m.iDMatcher.Matches(actual.ID)
			if !result.Matched {
				failures = append(failures, "ID: "+result.Message)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.postMatcher != nil {
			result := m.postMatcher.Matches(actual.Post)
			if !result.Matched {
				failures = append(failures, "Post: "+result.Message)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.authorMatcher != nil {
			result := m.authorMatcher.Matches(actual.Author)
			if !result.Matched {
				failures = append(failures, "Author: "+result.Message)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.contentMatcher != nil {
			result := m.contentMatcher.Matches(actual.Content)
			if !result.Matched {
				failures = append(failures, "Content: "+result.Message)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.createdAtMatcher != nil {
			result := m.createdAtMatcher.Matches(actual.CreatedAt)
			if !result.Matched {
				failures = append(failures, "CreatedAt: "+result.Message)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}

		if len(failures) > 0 {
			return testgen.MatchResult{
				Matched: false,
				Message: "Comment did not match",
				Details: failures,
			}
		}
		return testgen.MatchResult{Matched: true}
	})
}
