// Package factory provides test data factories and type-safe matchers.
//
// # Overview
//
// This package is generated by specta and provides two main APIs:
//
//  1. Recipes - Fluent builders for creating test data with sensible defaults
//  2. Matchers - Type-safe assertions for validating test results
//
// # Quick Start
//
// Build test data with recipes:
//
//	p := specta.New()
//	user := User().Email("test@example.com").Active(true).Build(p)
//	users := User().Many(10, p)  // Create 10 unique users
//
// Assert with matchers:
//
//	matcher := UserMatches().Email(specta.Contains("@example.com"))
//	specta.AssertThat(t, actualUser, matcher.Matcher())
//
// Combine both with partial matching:
//
//	partial := User().Email("expected@example.com").AsEqualMatcher()
//	specta.AssertThat(t, actualUser, partial)  // Only checks Email field
//
// # Key Concepts
//
// Recipes use value semantics and deterministic generation via specta.Primitives.
// Matchers provide structured diffs on failure. Partial matching only validates
// fields you explicitly set, making tests resilient to type changes.
//
// # Learn More
//
// See the specta package documentation for details on:
//   - Composition patterns for complex test data
//   - Matcher combinators (AllOf, AnyOf, Not)
//   - Custom matchers and recipe extensions
//   - Primitives for deterministic test data generation
package factory
