// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// This file contains generated matchers for Email.
//
// Use EmailMatches() to build type-safe matchers for assertions,
// or use Email().AsEqualMatcher() for partial matching based on recipes.

package factory

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// EmailMatcher provides a fluent API for matching Email instances.
type EmailMatcher struct {
	addressMatcher specta.Matcher[string]
}

// EmailMatches creates a new EmailMatcher for matching Email instances.
//
// This matcher provides methods for properties accessed via getters:
//   - Address: matches GetAddress() → string
//
// Example:
//
//	matcher := factory.EmailMatches().
//	    Address(specta.Equal("expected_value")).
//
//	specta.AssertThat(t, actualEmail, matcher)
func EmailMatches() EmailMatcher {
	return EmailMatcher{}
}

// Address adds a matcher for the Address property.
// This property is accessed via the GetAddress() method.
func (m EmailMatcher) Address(matcher specta.Matcher[string]) EmailMatcher {
	m.addressMatcher = matcher
	return m
}

// Matches implements the Matcher[Email] interface.
func (m EmailMatcher) Matches(actual showcase.Email) specta.MatchResult {
	// Extract all field values upfront (call each getter exactly once)
	addressValue := actual.GetAddress()

	// Build fieldValues map for structured diff
	fieldValues := map[string]any{
		"Address": addressValue,
	}

	// Check matchers using cached values and store results
	fieldResults := make(map[string]*specta.MatchResult)
	hasFailures := false

	if m.addressMatcher != nil {
		result := m.addressMatcher.Matches(addressValue)
		fieldResults["Address"] = &result
		if !result.Matched {
			hasFailures = true
		}
	}

	if hasFailures {
		// Use structured diff for struct types
		structDiff := specta.BuildMatcherStructDiff("Email", fieldValues, fieldResults)
		return specta.MatchResult{
			Matched: false,
			Message: structDiff,
		}
	}
	return specta.MatchResult{Matched: true}
}
