// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package factory provides a fluent Recipe API for building test data and matchers.
//
// Example usage:
//
//	// Build a single instance with custom fields
//
//
//	result := Email().Address("example").Build(specta.New())
//
//
//
//	// Build many instances with unique values
//	results := Email().Many(5, specta.New())
//
//	// Build a matcher to verify specific fields
//
//
//	matcher := EmailMatches().Address(specta.DeepEqual("expected"))
//
//
//	specta.AssertThat(t, actual, matcher.Matcher())
//
//	// Convert a recipe to a matcher for partial matching
//
//
//	partialMatcher := Email().Address("expected").AsEqualMatcher()
//
//
//	specta.AssertThat(t, actual, partialMatcher)
package factory

import (
	"fmt"

	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
	"github.com/james-w/specta/showcase/factory/spec"
)

// EmailRecipe provides a fluent API for building Email instances.
type EmailRecipe struct {
	opts []specta.Opt[spec.EmailSpec]
}

// Email creates a new EmailRecipe for building Email instances.
//
// The underlying constructor is NewEmail(address string).
//
// Example:
//
//	p := specta.New()
//	email := factory.Email().
//	    Address("custom_value").
//	    Build(p)
func Email() EmailRecipe { return EmailRecipe{} }

// Address sets the address parameter of NewEmail.
func (r EmailRecipe) Address(v string) EmailRecipe {
	r.opts = append(r.opts, spec.WithEmailAddress(v))
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r EmailRecipe) Provider() specta.Provider[showcase.Email] {
	// Wrap error-returning constructor - panic on error for test factories
	return func(s specta.Source) showcase.Email {
		sp := spec.NewEmailSpec()
		for _, opt := range r.opts {
			opt(&sp)
		}
		result, err := spec.BuildEmail(s, sp)
		if err != nil {
			panic("Provider failed: " + err.Error())
		}
		return result
	}
}

// Build creates a single Email instance.
func (r EmailRecipe) Build(s specta.Source) (showcase.Email, error) {
	// Constructor returns multiple values - apply opts and call Build directly
	sp := spec.NewEmailSpec()
	for _, opt := range r.opts {
		opt(&sp)
	}
	return spec.BuildEmail(s, sp)
}

// Many creates multiple Email instances with unique generated values.
func (r EmailRecipe) Many(n int, s specta.Source) []showcase.Email {
	// Wrap error-returning constructor - panic on first error
	var results []showcase.Email
	for i := range n {
		item, err := r.Build(s)
		if err != nil {
			panic("Many() failed on item " + fmt.Sprint(i) + ": " + err.Error())
		}
		results = append(results, item)
	}
	return results
}

// AsEqualMatcher converts this Recipe into a Matcher that checks for equality on all set fields.
// Only fields that were explicitly set in the Recipe will be checked - unset fields are ignored.
// This enables partial matching where you only verify specific fields.
// For nested types set via FromRecipe, partial matching is applied recursively.
func (r EmailRecipe) AsEqualMatcher() specta.Matcher[showcase.Email] {
	// Constructor-based type with matchers configured: use matcher builder for partial matching
	s := spec.NewEmailSpec()
	for _, opt := range r.opts {
		opt(&s)
	}
	p := specta.New()

	m := EmailMatches()
	if s.Address.IsSet() {
		m = m.Address(specta.Equal(s.Address.Value(p)))
	}
	return m.Matcher()
}
