// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// This file contains the recipe (test data builder) for Member.
//
// Use Member() to build instances with custom fields, or Many() for multiple unique instances.
package factory

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
	"github.com/james-w/specta/showcase/factory/spec"
)

// MemberRecipe provides a fluent API for building Member instances.
type MemberRecipe struct {
	opts       []specta.Opt[spec.MemberSpec]
	teamRecipe *TeamRecipe
}

// Member creates a new MemberRecipe for building Member instances.
//
// This is a struct-based type with the following fields:
//   - ID (string)
//   - Name (string)
//   - TeamID (string)
//   - Team (*showcase.Team)
//
// Example:
//
//	p := specta.New()
//	member := factory.Member().
//	    ID("custom_value").
//	    Name("another").
//	    Build(p)
func Member() MemberRecipe { return MemberRecipe{} }

// ID sets the ID field.
func (r MemberRecipe) ID(v string) MemberRecipe {
	r.opts = append(r.opts, spec.WithMemberID(v))
	return r
}

// Name sets the Name field.
func (r MemberRecipe) Name(v string) MemberRecipe {
	r.opts = append(r.opts, spec.WithMemberName(v))
	return r
}

// TeamID sets the TeamID field.
func (r MemberRecipe) TeamID(v string) MemberRecipe {
	r.opts = append(r.opts, spec.WithMemberTeamID(v))
	return r
}

// Team sets the Team field.
func (r MemberRecipe) Team(v *showcase.Team) MemberRecipe {
	r.opts = append(r.opts, spec.WithMemberTeam(v))
	r.teamRecipe = nil
	return r
}

// TeamFromRecipe sets the Team field using another Recipe (creates unique instances).
// The recipe is captured at call time (value semantics) - subsequent changes to v won't affect this recipe.
// The nested recipe is used for partial matching in AsEqualMatcher.
func (r MemberRecipe) TeamFromRecipe(v TeamRecipe) MemberRecipe {
	r.opts = append(r.opts, spec.WithMemberTeamFromProvider(specta.PtrOf(v.Provider())))
	r.teamRecipe = &v
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r MemberRecipe) Provider() specta.Provider[showcase.Member] {
	return specta.FromSpec(spec.BuildMember, spec.NewMemberSpec, r.opts...)
}

// Build creates a single Member instance.
func (r MemberRecipe) Build(p specta.Primitives) showcase.Member {
	return spec.NewMemberFactory(p).Make(r.opts...)
}

// Many creates multiple Member instances with unique generated values.
func (r MemberRecipe) Many(n int, p specta.Primitives) []showcase.Member {
	return spec.NewMemberFactory(p).Many(n, r.opts...)
}

// AsEqualMatcher converts this Recipe into a Matcher that checks for equality on all set fields.
// Only fields that were explicitly set in the Recipe will be checked - unset fields are ignored.
// This enables partial matching where you only verify specific fields.
// For nested types set via FromRecipe, partial matching is applied recursively.
func (r MemberRecipe) AsEqualMatcher() specta.Matcher[showcase.Member] {
	// Apply opts to a spec to see what was set
	s := spec.NewMemberSpec()
	for _, opt := range r.opts {
		opt(&s)
	}

	// Use a dummy Primitives to evaluate literal values
	// This works for SetLit values; SetWith/Provider values will be evaluated too
	p := specta.New()

	// Build matcher only for set fields
	m := MemberMatches()
	if s.ID.IsSet() {
		m = m.ID(specta.DeepEqual(s.ID.Value(p)))
	}
	if s.Name.IsSet() {
		m = m.Name(specta.DeepEqual(s.Name.Value(p)))
	}
	if s.TeamID.IsSet() {
		m = m.TeamID(specta.DeepEqual(s.TeamID.Value(p)))
	}
	if s.Team.IsSet() {
		// Check if we have a nested recipe for partial matching
		if r.teamRecipe != nil {
			m = m.Team(specta.PointsTo(r.teamRecipe.AsEqualMatcher()))
		} else {
			m = m.Team(specta.DeepEqual(s.Team.Value(p)))
		}
	}

	return m.Matcher()
}
