// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// This file contains generated matchers for Member.
//
// Use MemberMatches() to build type-safe matchers for assertions,
// or use Member().AsEqualMatcher() for partial matching based on recipes.

package factory

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// MemberMatcher provides a fluent API for matching Member instances.
type MemberMatcher struct {
	iDMatcher     specta.Matcher[string]
	nameMatcher   specta.Matcher[string]
	teamIDMatcher specta.Matcher[string]
	teamMatcher   specta.Matcher[*showcase.Team]
}

// MemberMatches creates a new MemberMatcher for matching Member instances.
//
// This matcher provides methods for the following fields:
//   - ID (string)
//   - Name (string)
//   - TeamID (string)
//   - Team (*showcase.Team)
//
// Example:
//
//	matcher := factory.MemberMatches().
//	    ID(specta.Equal("expected_value")).
//	    Name(specta.Contains("substring"))
//
//	specta.AssertThat(t, actualMember, matcher)
func MemberMatches() MemberMatcher {
	return MemberMatcher{}
}

// ID adds a matcher for the ID field.
func (m MemberMatcher) ID(matcher specta.Matcher[string]) MemberMatcher {
	m.iDMatcher = matcher
	return m
}

// Name adds a matcher for the Name field.
func (m MemberMatcher) Name(matcher specta.Matcher[string]) MemberMatcher {
	m.nameMatcher = matcher
	return m
}

// TeamID adds a matcher for the TeamID field.
func (m MemberMatcher) TeamID(matcher specta.Matcher[string]) MemberMatcher {
	m.teamIDMatcher = matcher
	return m
}

// Team adds a matcher for the Team field.
func (m MemberMatcher) Team(matcher specta.Matcher[*showcase.Team]) MemberMatcher {
	m.teamMatcher = matcher
	return m
}

// Matches implements the Matcher[Member] interface.
func (m MemberMatcher) Matches(actual showcase.Member) specta.MatchResult {
	// Extract all field values upfront (call each getter exactly once)
	iDValue := actual.ID
	nameValue := actual.Name
	teamIDValue := actual.TeamID
	teamValue := actual.Team

	// Build fieldValues map for structured diff
	fieldValues := map[string]any{
		"ID":     iDValue,
		"Name":   nameValue,
		"TeamID": teamIDValue,
		"Team":   teamValue,
	}

	// Check matchers using cached values and store results
	fieldResults := make(map[string]*specta.MatchResult)
	hasFailures := false

	if m.iDMatcher != nil {
		result := m.iDMatcher.Matches(iDValue)
		fieldResults["ID"] = &result
		if !result.Matched {
			hasFailures = true
		}
	}

	if m.nameMatcher != nil {
		result := m.nameMatcher.Matches(nameValue)
		fieldResults["Name"] = &result
		if !result.Matched {
			hasFailures = true
		}
	}

	if m.teamIDMatcher != nil {
		result := m.teamIDMatcher.Matches(teamIDValue)
		fieldResults["TeamID"] = &result
		if !result.Matched {
			hasFailures = true
		}
	}

	if m.teamMatcher != nil {
		result := m.teamMatcher.Matches(teamValue)
		fieldResults["Team"] = &result
		if !result.Matched {
			hasFailures = true
		}
	}

	if hasFailures {
		// Use structured diff for struct types
		structDiff := specta.BuildMatcherStructDiff("Member", fieldValues, fieldResults)
		return specta.MatchResult{
			Matched: false,
			Message: structDiff,
		}
	}
	return specta.MatchResult{Matched: true}
}
