// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	"time"

	testgen "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// OrderMatcher provides a fluent API for matching Order instances.
type OrderMatcher struct {
	iDMatcher        testgen.Matcher[string]
	userMatcher      testgen.Matcher[showcase.User]
	itemsMatcher     testgen.Matcher[[]showcase.OrderItem]
	totalMatcher     testgen.Matcher[float64]
	statusMatcher    testgen.Matcher[string]
	createdAtMatcher testgen.Matcher[time.Time]
	updatedAtMatcher testgen.Matcher[time.Time]
}

// OrderMatches creates a new OrderMatcher for matching Order instances.
//
// This matcher provides methods for the following fields:
//   - ID (string)
//   - User (showcase.User)
//   - Items ([]showcase.OrderItem)
//   - Total (float64)
//   - Status (string)
//   - CreatedAt (time.Time)
//   - UpdatedAt (time.Time)
//
// Example:
//
//	matcher := factory.OrderMatches().
//	    ID(testgen.Equal("expected_value")).
//	    User(testgen.Equal(expectedValue)).
//	    Matcher()
//
//	testgen.AssertThat(t, actualOrder, matcher)
func OrderMatches() OrderMatcher {
	return OrderMatcher{}
}

// ID adds a matcher for the ID field.
func (m OrderMatcher) ID(matcher testgen.Matcher[string]) OrderMatcher {
	m.iDMatcher = matcher
	return m
}

// User adds a matcher for the User field.
func (m OrderMatcher) User(matcher testgen.Matcher[showcase.User]) OrderMatcher {
	m.userMatcher = matcher
	return m
}

// UserMatches is a convenience method that accepts a UserMatcher.
func (m OrderMatcher) UserMatches(matcher UserMatcher) OrderMatcher {
	m.userMatcher = matcher.Matcher()
	return m
}

// Items adds a matcher for the Items field.
func (m OrderMatcher) Items(matcher testgen.Matcher[[]showcase.OrderItem]) OrderMatcher {
	m.itemsMatcher = matcher
	return m
}

// Total adds a matcher for the Total field.
func (m OrderMatcher) Total(matcher testgen.Matcher[float64]) OrderMatcher {
	m.totalMatcher = matcher
	return m
}

// Status adds a matcher for the Status field.
func (m OrderMatcher) Status(matcher testgen.Matcher[string]) OrderMatcher {
	m.statusMatcher = matcher
	return m
}

// CreatedAt adds a matcher for the CreatedAt field.
func (m OrderMatcher) CreatedAt(matcher testgen.Matcher[time.Time]) OrderMatcher {
	m.createdAtMatcher = matcher
	return m
}

// UpdatedAt adds a matcher for the UpdatedAt field.
func (m OrderMatcher) UpdatedAt(matcher testgen.Matcher[time.Time]) OrderMatcher {
	m.updatedAtMatcher = matcher
	return m
}

// Matcher returns the composed matcher for Order.
func (m OrderMatcher) Matcher() testgen.Matcher[showcase.Order] {
	return testgen.MatcherFunc[showcase.Order](func(actual showcase.Order) testgen.MatchResult {
		// Extract all field values upfront (call each getter exactly once)
		iDValue := actual.ID
		userValue := actual.User
		itemsValue := actual.Items
		totalValue := actual.Total
		statusValue := actual.Status
		createdAtValue := actual.CreatedAt
		updatedAtValue := actual.UpdatedAt

		// Build fieldValues map for structured diff
		fieldValues := map[string]any{
			"ID":        iDValue,
			"User":      userValue,
			"Items":     itemsValue,
			"Total":     totalValue,
			"Status":    statusValue,
			"CreatedAt": createdAtValue,
			"UpdatedAt": updatedAtValue,
		}

		// Check matchers using cached values and store results
		fieldResults := make(map[string]*testgen.MatchResult)
		hasFailures := false

		if m.iDMatcher != nil {
			result := m.iDMatcher.Matches(iDValue)
			fieldResults["ID"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.userMatcher != nil {
			result := m.userMatcher.Matches(userValue)
			fieldResults["User"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.itemsMatcher != nil {
			result := m.itemsMatcher.Matches(itemsValue)
			fieldResults["Items"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.totalMatcher != nil {
			result := m.totalMatcher.Matches(totalValue)
			fieldResults["Total"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.statusMatcher != nil {
			result := m.statusMatcher.Matches(statusValue)
			fieldResults["Status"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.createdAtMatcher != nil {
			result := m.createdAtMatcher.Matches(createdAtValue)
			fieldResults["CreatedAt"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.updatedAtMatcher != nil {
			result := m.updatedAtMatcher.Matches(updatedAtValue)
			fieldResults["UpdatedAt"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if hasFailures {
			// Use structured diff for struct types
			structDiff := testgen.BuildMatcherStructDiff("Order", fieldValues, fieldResults)
			return testgen.MatchResult{
				Matched: false,
				Message: structDiff,
			}
		}
		return testgen.MatchResult{Matched: true}
	})
}
