// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package factory provides a fluent Recipe API for building test data and matchers.
//
// Example usage:
//
//	// Build a single instance with custom fields
//
//
//	result := OrderItem().Product(value).Build(testgen.New())
//
//
//
//	// Build many instances with unique values
//	results := OrderItem().Many(5, testgen.New())
//
//	// Build a matcher to verify specific fields
//
//
//	matcher := OrderItemMatches().Product(testgen.DeepEqual(expectedValue))
//
//
//	testgen.AssertThat(t, actual, matcher.Matcher())
//
//	// Convert a recipe to a matcher for partial matching
//
//
//	partialMatcher := OrderItem().Product(expected).AsEqualMatcher()
//
//
//	testgen.AssertThat(t, actual, partialMatcher)
package factory

import (
	testgen "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
	"github.com/james-w/specta/showcase/factory/spec"
)

// OrderItemRecipe provides a fluent API for building OrderItem instances.
type OrderItemRecipe struct {
	opts          []testgen.Opt[spec.OrderItemSpec]
	productRecipe *ProductRecipe
}

// OrderItem creates a new OrderItemRecipe for building OrderItem instances.
func OrderItem() OrderItemRecipe { return OrderItemRecipe{} }

// Product sets the Product field.
func (r OrderItemRecipe) Product(v showcase.Product) OrderItemRecipe {
	r.opts = append(r.opts, spec.WithOrderItemProduct(v))
	r.productRecipe = nil
	return r
}

// ProductFromRecipe sets the Product field using another Recipe (creates unique instances).
// The recipe is captured at call time (value semantics) - subsequent changes to v won't affect this recipe.
// The nested recipe is used for partial matching in AsEqualMatcher.
func (r OrderItemRecipe) ProductFromRecipe(v ProductRecipe) OrderItemRecipe {
	r.opts = append(r.opts, spec.WithOrderItemProductFromProvider(v.Provider()))
	r.productRecipe = &v
	return r
}

// Quantity sets the Quantity field.
func (r OrderItemRecipe) Quantity(v int) OrderItemRecipe {
	r.opts = append(r.opts, spec.WithOrderItemQuantity(v))
	return r
}

// Price sets the Price field.
func (r OrderItemRecipe) Price(v float64) OrderItemRecipe {
	r.opts = append(r.opts, spec.WithOrderItemPrice(v))
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r OrderItemRecipe) Provider() testgen.Provider[showcase.OrderItem] {
	return testgen.FromSpec(spec.BuildOrderItem, spec.NewOrderItemSpec, r.opts...)
}

// Build creates a single OrderItem instance.
func (r OrderItemRecipe) Build(p testgen.Primitives) showcase.OrderItem {
	return spec.NewOrderItemFactory(p).Make(r.opts...)
}

// Many creates multiple OrderItem instances with unique generated values.
func (r OrderItemRecipe) Many(n int, p testgen.Primitives) []showcase.OrderItem {
	return spec.NewOrderItemFactory(p).Many(n, r.opts...)
}

// AsEqualMatcher converts this Recipe into a Matcher that checks for equality on all set fields.
// Only fields that were explicitly set in the Recipe will be checked - unset fields are ignored.
// This enables partial matching where you only verify specific fields.
// For nested types set via FromRecipe, partial matching is applied recursively.
func (r OrderItemRecipe) AsEqualMatcher() testgen.Matcher[showcase.OrderItem] {
	// Apply opts to a spec to see what was set
	s := spec.NewOrderItemSpec()
	for _, opt := range r.opts {
		opt(&s)
	}

	// Use a dummy Primitives to evaluate literal values
	// This works for SetLit values; SetWith/Provider values will be evaluated too
	p := testgen.New()

	// Build matcher only for set fields
	m := OrderItemMatches()
	if s.Product.IsSet() {
		// Check if we have a nested recipe for partial matching
		if r.productRecipe != nil {
			m = m.Product(r.productRecipe.AsEqualMatcher())
		} else {
			m = m.Product(testgen.DeepEqual(s.Product.Value(p)))
		}
	}
	if s.Quantity.IsSet() {
		m = m.Quantity(testgen.DeepEqual(s.Quantity.Value(p)))
	}
	if s.Price.IsSet() {
		m = m.Price(testgen.DeepEqual(s.Price.Value(p)))
	}

	return m.Matcher()
}
