// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// This file contains the recipe (test data builder) for Order.
//
// Use Order() to build instances with custom fields, or Many() for multiple unique instances.
package factory

import (
	"time"

	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
	"github.com/james-w/specta/showcase/factory/spec"
)

// OrderRecipe provides a fluent API for building Order instances.
type OrderRecipe struct {
	opts       []specta.Opt[spec.OrderSpec]
	userRecipe *UserRecipe
}

// Order creates a new OrderRecipe for building Order instances.
//
// This is a struct-based type with the following fields:
//   - ID (string)
//   - User (showcase.User)
//   - Items ([]showcase.OrderItem)
//   - Total (float64)
//   - Status (string)
//   - CreatedAt (time.Time)
//   - UpdatedAt (time.Time)
//
// Example:
//
//	p := specta.New()
//	order := factory.Order().
//	    ID("custom_value").
//	    User(value).
//	    Build(p)
func Order() OrderRecipe { return OrderRecipe{} }

// ID sets the ID field.
func (r OrderRecipe) ID(v string) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderID(v))
	return r
}

// IDFromGenerator sets the ID field using a Generator.
func (r OrderRecipe) IDFromGenerator(gen specta.Generator[string]) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderIDFromGenerator(gen))
	return r
}

// User sets the User field.
func (r OrderRecipe) User(v showcase.User) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderUser(v))
	r.userRecipe = nil
	return r
}

// UserFromGenerator sets the User field using a Generator.
func (r OrderRecipe) UserFromGenerator(gen specta.Generator[showcase.User]) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderUserFromGenerator(gen))
	r.userRecipe = nil
	return r
}

// UserFromRecipe sets the User field using another Recipe (creates unique instances).
// The recipe is captured at call time (value semantics) - subsequent changes to v won't affect this recipe.
// The nested recipe is used for partial matching in AsEqualMatcher.
func (r OrderRecipe) UserFromRecipe(v UserRecipe) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderUserFromGenerator(v.Gen()))
	r.userRecipe = &v
	return r
}

// Items sets the Items field.
func (r OrderRecipe) Items(v []showcase.OrderItem) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderItems(v))
	return r
}

// ItemsFromGenerator sets the Items field using a Generator.
func (r OrderRecipe) ItemsFromGenerator(gen specta.Generator[[]showcase.OrderItem]) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderItemsFromGenerator(gen))
	return r
}

// Total sets the Total field.
func (r OrderRecipe) Total(v float64) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderTotal(v))
	return r
}

// TotalFromGenerator sets the Total field using a Generator.
func (r OrderRecipe) TotalFromGenerator(gen specta.Generator[float64]) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderTotalFromGenerator(gen))
	return r
}

// Status sets the Status field.
func (r OrderRecipe) Status(v string) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderStatus(v))
	return r
}

// StatusFromGenerator sets the Status field using a Generator.
func (r OrderRecipe) StatusFromGenerator(gen specta.Generator[string]) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderStatusFromGenerator(gen))
	return r
}

// CreatedAt sets the CreatedAt field.
func (r OrderRecipe) CreatedAt(v time.Time) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderCreatedAt(v))
	return r
}

// CreatedAtFromGenerator sets the CreatedAt field using a Generator.
func (r OrderRecipe) CreatedAtFromGenerator(gen specta.Generator[time.Time]) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderCreatedAtFromGenerator(gen))
	return r
}

// UpdatedAt sets the UpdatedAt field.
func (r OrderRecipe) UpdatedAt(v time.Time) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderUpdatedAt(v))
	return r
}

// UpdatedAtFromGenerator sets the UpdatedAt field using a Generator.
func (r OrderRecipe) UpdatedAtFromGenerator(gen specta.Generator[time.Time]) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderUpdatedAtFromGenerator(gen))
	return r
}

// Gen returns a Gen[T] for use in nested custom types.
func (r OrderRecipe) Gen() specta.Gen[showcase.Order] {
	return specta.FromSpecGen(spec.BuildOrder, spec.NewOrderSpec, r.opts...)
}

// Build creates a single Order instance.
func (r OrderRecipe) Build(s specta.Source) showcase.Order {
	return spec.NewOrderFactory(s).Make(r.opts...)
}

// Many creates multiple Order instances with unique generated values.
func (r OrderRecipe) Many(n int, s specta.Source) []showcase.Order {
	return spec.NewOrderFactory(s).Many(n, r.opts...)
}

// AsEqualMatcher converts this Recipe into a Matcher that checks for equality on all set fields.
// Only fields that were explicitly set in the Recipe will be checked - unset fields are ignored.
// This enables partial matching where you only verify specific fields.
// For nested types set via FromRecipe, partial matching is applied recursively.
func (r OrderRecipe) AsEqualMatcher() specta.Matcher[showcase.Order] {
	// Apply opts to a spec to see what was set
	s := spec.NewOrderSpec()
	for _, opt := range r.opts {
		opt(&s)
	}

	// Use a dummy Source to evaluate literal values
	// This works for SetLit values; SetWith/Provider values will be evaluated too
	p := specta.New()

	// Build matcher only for set fields
	m := OrderMatches()
	if s.ID.IsSet() {
		m = m.ID(specta.DeepEqual(s.ID.GetValue(p, "ID")))
	}
	if s.User.IsSet() {
		// Check if we have a nested recipe for partial matching
		if r.userRecipe != nil {
			m = m.User(r.userRecipe.AsEqualMatcher())
		} else {
			m = m.User(specta.DeepEqual(s.User.GetValue(p, "User")))
		}
	}
	if s.Items.IsSet() {
		m = m.Items(specta.DeepEqual(s.Items.GetValue(p, "Items")))
	}
	if s.Total.IsSet() {
		m = m.Total(specta.DeepEqual(s.Total.GetValue(p, "Total")))
	}
	if s.Status.IsSet() {
		m = m.Status(specta.DeepEqual(s.Status.GetValue(p, "Status")))
	}
	if s.CreatedAt.IsSet() {
		m = m.CreatedAt(specta.DeepEqual(s.CreatedAt.GetValue(p, "CreatedAt")))
	}
	if s.UpdatedAt.IsSet() {
		m = m.UpdatedAt(specta.DeepEqual(s.UpdatedAt.GetValue(p, "UpdatedAt")))
	}

	return m
}
