// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	testgen "github.com/james-w/gomatchers"
	"github.com/james-w/gomatchers/showcase"
	"github.com/james-w/gomatchers/showcase/factory/spec"
)

// OrderItemRecipe provides a fluent API for building OrderItem instances.
type OrderItemRecipe struct {
	opts []testgen.Opt[spec.OrderItemSpec]
}

// OrderItem creates a new OrderItemRecipe for building OrderItem instances.
func OrderItem() OrderItemRecipe { return OrderItemRecipe{} }

// Product sets the Product field.
func (r OrderItemRecipe) Product(v showcase.Product) OrderItemRecipe {
	r.opts = append(r.opts, spec.WithOrderItemProduct(v))
	return r
}

// ProductFromRecipe sets the Product field using another Recipe (creates unique instances).
func (r OrderItemRecipe) ProductFromRecipe(v ProductRecipe) OrderItemRecipe {
	r.opts = append(r.opts, spec.WithOrderItemProductFromProvider(v.Provider()))
	return r
}

// Quantity sets the Quantity field.
func (r OrderItemRecipe) Quantity(v int) OrderItemRecipe {
	r.opts = append(r.opts, spec.WithOrderItemQuantity(v))
	return r
}

// Price sets the Price field.
func (r OrderItemRecipe) Price(v float64) OrderItemRecipe {
	r.opts = append(r.opts, spec.WithOrderItemPrice(v))
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r OrderItemRecipe) Provider() testgen.Provider[showcase.OrderItem] {
	return testgen.FromSpec(spec.BuildOrderItem, spec.NewOrderItemSpec, r.opts...)
}

// Build creates a single OrderItem instance.
func (r OrderItemRecipe) Build(p testgen.Primitives) showcase.OrderItem {
	return spec.NewOrderItemFactory(p).Make(r.opts...)
}

// Many creates multiple OrderItem instances with unique generated values.
func (r OrderItemRecipe) Many(n int, p testgen.Primitives) []showcase.OrderItem {
	return spec.NewOrderItemFactory(p).Many(n, r.opts...)
}
