// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	"fmt"
	testgen "github.com/james-w/gomatchers"
	"github.com/james-w/gomatchers/showcase"
)

// OrderItemMatcher provides a fluent API for matching OrderItem instances.
type OrderItemMatcher struct {
	productMatcher  testgen.Matcher[showcase.Product]
	quantityMatcher testgen.Matcher[int]
	priceMatcher    testgen.Matcher[float64]
}

// OrderItemMatches creates a new OrderItemMatcher for matching OrderItem instances.
func OrderItemMatches() OrderItemMatcher {
	return OrderItemMatcher{}
}

// Product adds a matcher for the Product field.
func (m OrderItemMatcher) Product(matcher testgen.Matcher[showcase.Product]) OrderItemMatcher {
	m.productMatcher = matcher
	return m
}

// ProductMatches is a convenience method that accepts a ProductMatcher.
func (m OrderItemMatcher) ProductMatches(matcher ProductMatcher) OrderItemMatcher {
	m.productMatcher = matcher.Matcher()
	return m
}

// Quantity adds a matcher for the Quantity field.
func (m OrderItemMatcher) Quantity(matcher testgen.Matcher[int]) OrderItemMatcher {
	m.quantityMatcher = matcher
	return m
}

// Price adds a matcher for the Price field.
func (m OrderItemMatcher) Price(matcher testgen.Matcher[float64]) OrderItemMatcher {
	m.priceMatcher = matcher
	return m
}

// Matcher returns the composed matcher for OrderItem.
func (m OrderItemMatcher) Matcher() testgen.Matcher[showcase.OrderItem] {
	return testgen.MatcherFunc[showcase.OrderItem](func(actual showcase.OrderItem) testgen.MatchResult {
		var failures []string
		if m.productMatcher != nil {
			result := m.productMatcher.Matches(actual.Product)
			if !result.Matched {
				// Add path context if not already present
				path := "OrderItem.Product"
				if result.Path != "" {
					path = "OrderItem." + result.Path
				}
				msg := result.Message
				if result.Expected != nil && result.Actual != nil {
					msg = fmt.Sprintf("%s (at %s)", result.Message, path)
				}
				failures = append(failures, "Product: "+msg)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.quantityMatcher != nil {
			result := m.quantityMatcher.Matches(actual.Quantity)
			if !result.Matched {
				// Add path context if not already present
				path := "OrderItem.Quantity"
				if result.Path != "" {
					path = "OrderItem." + result.Path
				}
				msg := result.Message
				if result.Expected != nil && result.Actual != nil {
					msg = fmt.Sprintf("%s (at %s)", result.Message, path)
				}
				failures = append(failures, "Quantity: "+msg)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.priceMatcher != nil {
			result := m.priceMatcher.Matches(actual.Price)
			if !result.Matched {
				// Add path context if not already present
				path := "OrderItem.Price"
				if result.Path != "" {
					path = "OrderItem." + result.Path
				}
				msg := result.Message
				if result.Expected != nil && result.Actual != nil {
					msg = fmt.Sprintf("%s (at %s)", result.Message, path)
				}
				failures = append(failures, "Price: "+msg)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}

		if len(failures) > 0 {
			return testgen.MatchResult{
				Matched: false,
				Message: "OrderItem did not match",
				Details: failures,
			}
		}
		return testgen.MatchResult{Matched: true}
	})
}
