// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// This file contains the recipe (test data builder) for OrderItem.
//
// Use OrderItem() to build instances with custom fields, or Many() for multiple unique instances.
package factory

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
	"github.com/james-w/specta/showcase/factory/spec"
)

// OrderItemRecipe provides a fluent API for building OrderItem instances.
type OrderItemRecipe struct {
	opts          []specta.Opt[spec.OrderItemSpec]
	productRecipe *ProductRecipe
}

// OrderItem creates a new OrderItemRecipe for building OrderItem instances.
//
// This is a struct-based type with the following fields:
//   - Product (showcase.Product)
//   - Quantity (int)
//   - Price (float64)
//
// Example:
//
//	p := specta.New()
//	orderItem := factory.OrderItem().
//	    Product(value).
//	    Quantity(200).
//	    Build(p)
func OrderItem() OrderItemRecipe { return OrderItemRecipe{} }

// Product sets the Product field.
func (r OrderItemRecipe) Product(v showcase.Product) OrderItemRecipe {
	r.opts = append(r.opts, spec.WithOrderItemProduct(v))
	r.productRecipe = nil
	return r
}

// ProductFromRecipe sets the Product field using another Recipe (creates unique instances).
// The recipe is captured at call time (value semantics) - subsequent changes to v won't affect this recipe.
// The nested recipe is used for partial matching in AsEqualMatcher.
func (r OrderItemRecipe) ProductFromRecipe(v ProductRecipe) OrderItemRecipe {
	r.opts = append(r.opts, spec.WithOrderItemProductFromProvider(v.Provider()))
	r.productRecipe = &v
	return r
}

// Quantity sets the Quantity field.
func (r OrderItemRecipe) Quantity(v int) OrderItemRecipe {
	r.opts = append(r.opts, spec.WithOrderItemQuantity(v))
	return r
}

// Price sets the Price field.
func (r OrderItemRecipe) Price(v float64) OrderItemRecipe {
	r.opts = append(r.opts, spec.WithOrderItemPrice(v))
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r OrderItemRecipe) Provider() specta.Provider[showcase.OrderItem] {
	return specta.FromSpec(spec.BuildOrderItem, spec.NewOrderItemSpec, r.opts...)
}

// Build creates a single OrderItem instance.
func (r OrderItemRecipe) Build(s specta.Source) showcase.OrderItem {
	return spec.NewOrderItemFactory(s).Make(r.opts...)
}

// Many creates multiple OrderItem instances with unique generated values.
func (r OrderItemRecipe) Many(n int, s specta.Source) []showcase.OrderItem {
	return spec.NewOrderItemFactory(s).Many(n, r.opts...)
}

// AsEqualMatcher converts this Recipe into a Matcher that checks for equality on all set fields.
// Only fields that were explicitly set in the Recipe will be checked - unset fields are ignored.
// This enables partial matching where you only verify specific fields.
// For nested types set via FromRecipe, partial matching is applied recursively.
func (r OrderItemRecipe) AsEqualMatcher() specta.Matcher[showcase.OrderItem] {
	// Apply opts to a spec to see what was set
	s := spec.NewOrderItemSpec()
	for _, opt := range r.opts {
		opt(&s)
	}

	// Use a dummy Source to evaluate literal values
	// This works for SetLit values; SetWith/Provider values will be evaluated too
	p := specta.New()

	// Build matcher only for set fields
	m := OrderItemMatches()
	if s.Product.IsSet() {
		// Check if we have a nested recipe for partial matching
		if r.productRecipe != nil {
			m = m.Product(r.productRecipe.AsEqualMatcher())
		} else {
			m = m.Product(specta.DeepEqual(s.Product.Value(p)))
		}
	}
	if s.Quantity.IsSet() {
		m = m.Quantity(specta.DeepEqual(s.Quantity.Value(p)))
	}
	if s.Price.IsSet() {
		m = m.Price(specta.DeepEqual(s.Price.Value(p)))
	}

	return m.Matcher()
}
