// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	"time"

	testgen "github.com/james-w/gomatchers"
	"github.com/james-w/gomatchers/showcase"
)

// ============================================================================
// Low-level API: Spec, Build, and Options
// ============================================================================

type OrderSpec struct {
	ID        testgen.Maybe[string]
	User      testgen.Maybe[showcase.User]
	Items     testgen.Maybe[[]showcase.OrderItem]
	Total     testgen.Maybe[float64]
	Status    testgen.Maybe[string]
	CreatedAt testgen.Maybe[time.Time]
	UpdatedAt testgen.Maybe[time.Time]
}

func NewOrderSpec() OrderSpec { return OrderSpec{} }

func NewOrderFactory(p testgen.Primitives) *testgen.SpecFactory[showcase.Order, OrderSpec] {
	return testgen.NewSpecFactory(p, NewOrderSpec, BuildOrder)
}

// Defaults (simple heuristics).
var (
	OrderDefaultID        = func(p testgen.Primitives) string { return p.ID() }
	OrderDefaultUser      = testgen.FromSpec(BuildUser, NewUserSpec)
	OrderDefaultItems     = func(p testgen.Primitives) []showcase.OrderItem { var zero []showcase.OrderItem; return zero }
	OrderDefaultTotal     = func(p testgen.Primitives) float64 { return p.Float64() }
	OrderDefaultStatus    = func(p testgen.Primitives) string { return p.StringWith("status_") }
	OrderDefaultCreatedAt = func(p testgen.Primitives) time.Time { return p.Time() }
	OrderDefaultUpdatedAt = func(p testgen.Primitives) time.Time { return p.Time() }
)

func BuildOrder(p testgen.Primitives, s OrderSpec) showcase.Order {
	iD := s.ID.Get(p, OrderDefaultID)
	user := s.User.Get(p, OrderDefaultUser)
	items := s.Items.Get(p, OrderDefaultItems)
	total := s.Total.Get(p, OrderDefaultTotal)
	status := s.Status.Get(p, OrderDefaultStatus)
	createdAt := s.CreatedAt.Get(p, OrderDefaultCreatedAt)
	updatedAt := s.UpdatedAt.Get(p, OrderDefaultUpdatedAt)
	return showcase.Order{
		ID:        iD,
		User:      user,
		Items:     items,
		Total:     total,
		Status:    status,
		CreatedAt: createdAt,
		UpdatedAt: updatedAt,
	}
}

func WithOrderID(v string) testgen.Opt[OrderSpec] {
	return testgen.SetLit(func(s *OrderSpec, m testgen.Maybe[string]) { s.ID = m }, v)
}

func WithOrderUser(v showcase.User) testgen.Opt[OrderSpec] {
	return testgen.SetLit(func(s *OrderSpec, m testgen.Maybe[showcase.User]) { s.User = m }, v)
}

func WithOrderUserFromRecipe(rec UserRecipe) testgen.Opt[OrderSpec] {
	return testgen.SetWith(
		func(s *OrderSpec, m testgen.Maybe[showcase.User]) { s.User = m },
		rec.Provider(),
	)
}

func WithOrderItems(v []showcase.OrderItem) testgen.Opt[OrderSpec] {
	return testgen.SetLit(func(s *OrderSpec, m testgen.Maybe[[]showcase.OrderItem]) { s.Items = m }, v)
}

func WithOrderTotal(v float64) testgen.Opt[OrderSpec] {
	return testgen.SetLit(func(s *OrderSpec, m testgen.Maybe[float64]) { s.Total = m }, v)
}

func WithOrderStatus(v string) testgen.Opt[OrderSpec] {
	return testgen.SetLit(func(s *OrderSpec, m testgen.Maybe[string]) { s.Status = m }, v)
}

func WithOrderCreatedAt(v time.Time) testgen.Opt[OrderSpec] {
	return testgen.SetLit(func(s *OrderSpec, m testgen.Maybe[time.Time]) { s.CreatedAt = m }, v)
}

func WithOrderUpdatedAt(v time.Time) testgen.Opt[OrderSpec] {
	return testgen.SetLit(func(s *OrderSpec, m testgen.Maybe[time.Time]) { s.UpdatedAt = m }, v)
}

// ============================================================================
// High-level Recipe API
// ============================================================================

type OrderRecipe struct{ opts []testgen.Opt[OrderSpec] }

func Order() OrderRecipe { return OrderRecipe{} }

func (r OrderRecipe) ID(v string) OrderRecipe {
	r.opts = append(r.opts, WithOrderID(v))
	return r
}

func (r OrderRecipe) User(v showcase.User) OrderRecipe {
	r.opts = append(r.opts, WithOrderUser(v))
	return r
}

func (r OrderRecipe) UserFromRecipe(v UserRecipe) OrderRecipe {
	r.opts = append(r.opts, WithOrderUserFromRecipe(v))
	return r
}

func (r OrderRecipe) Items(v []showcase.OrderItem) OrderRecipe {
	r.opts = append(r.opts, WithOrderItems(v))
	return r
}

func (r OrderRecipe) Total(v float64) OrderRecipe {
	r.opts = append(r.opts, WithOrderTotal(v))
	return r
}

func (r OrderRecipe) Status(v string) OrderRecipe {
	r.opts = append(r.opts, WithOrderStatus(v))
	return r
}

func (r OrderRecipe) CreatedAt(v time.Time) OrderRecipe {
	r.opts = append(r.opts, WithOrderCreatedAt(v))
	return r
}

func (r OrderRecipe) UpdatedAt(v time.Time) OrderRecipe {
	r.opts = append(r.opts, WithOrderUpdatedAt(v))
	return r
}

// Provider for nesting into parents (defers evaluation; consumes Primitives later)
func (r OrderRecipe) Provider() testgen.Provider[showcase.Order] {
	return testgen.FromSpec(BuildOrder, NewOrderSpec, r.opts...)
}

// Build now if you need a concrete value (rare in composing tests)
func (r OrderRecipe) Build(p testgen.Primitives) showcase.Order {
	return NewOrderFactory(p).Make(r.opts...)
}

func (r OrderRecipe) Many(n int, p testgen.Primitives) []showcase.Order {
	return NewOrderFactory(p).Many(n, r.opts...)
}
