// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	"time"

	testgen "github.com/james-w/gomatchers"
	"github.com/james-w/gomatchers/showcase"
	"github.com/james-w/gomatchers/showcase/factory/spec"
)

// OrderRecipe provides a fluent API for building Order instances.
type OrderRecipe struct{ opts []testgen.Opt[spec.OrderSpec] }

// Order creates a new OrderRecipe for building Order instances.
func Order() OrderRecipe { return OrderRecipe{} }

// ID sets the ID field.
func (r OrderRecipe) ID(v string) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderID(v))
	return r
}

// User sets the User field.
func (r OrderRecipe) User(v showcase.User) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderUser(v))
	return r
}

// UserFromRecipe sets the User field using another Recipe (creates unique instances).
func (r OrderRecipe) UserFromRecipe(v UserRecipe) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderUserFromProvider(v.Provider()))
	return r
}

// Items sets the Items field.
func (r OrderRecipe) Items(v []showcase.OrderItem) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderItems(v))
	return r
}

// Total sets the Total field.
func (r OrderRecipe) Total(v float64) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderTotal(v))
	return r
}

// Status sets the Status field.
func (r OrderRecipe) Status(v string) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderStatus(v))
	return r
}

// CreatedAt sets the CreatedAt field.
func (r OrderRecipe) CreatedAt(v time.Time) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderCreatedAt(v))
	return r
}

// UpdatedAt sets the UpdatedAt field.
func (r OrderRecipe) UpdatedAt(v time.Time) OrderRecipe {
	r.opts = append(r.opts, spec.WithOrderUpdatedAt(v))
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r OrderRecipe) Provider() testgen.Provider[showcase.Order] {
	return testgen.FromSpec(spec.BuildOrder, spec.NewOrderSpec, r.opts...)
}

// Build creates a single Order instance.
func (r OrderRecipe) Build(p testgen.Primitives) showcase.Order {
	return spec.NewOrderFactory(p).Make(r.opts...)
}

// Many creates multiple Order instances with unique generated values.
func (r OrderRecipe) Many(n int, p testgen.Primitives) []showcase.Order {
	return spec.NewOrderFactory(p).Many(n, r.opts...)
}
