// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// This file contains generated matchers for Organization.
//
// Use OrganizationMatches() to build type-safe matchers for assertions,
// or use Organization().AsEqualMatcher() for partial matching based on recipes.

package factory

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// OrganizationMatcher provides a fluent API for matching Organization instances.
type OrganizationMatcher struct {
	iDMatcher       specta.Matcher[string]
	nameMatcher     specta.Matcher[string]
	cEOMatcher      specta.Matcher[*showcase.User]
	teamsMatcher    specta.Matcher[[]showcase.Team]
	membersMatcher  specta.Matcher[[]showcase.Member]
	metadataMatcher specta.Matcher[map[string]string]
}

// OrganizationMatches creates a new OrganizationMatcher for matching Organization instances.
//
// This matcher provides methods for the following fields:
//   - ID (string)
//   - Name (string)
//   - CEO (*showcase.User)
//   - Teams ([]showcase.Team)
//   - Members ([]showcase.Member)
//   - Metadata (map[string]string)
//
// Example:
//
//	matcher := factory.OrganizationMatches().
//	    ID(specta.Equal("expected_value")).
//	    Name(specta.Contains("substring"))
//
//	specta.AssertThat(t, actualOrganization, matcher)
func OrganizationMatches() OrganizationMatcher {
	return OrganizationMatcher{}
}

// ID adds a matcher for the ID field.
func (m OrganizationMatcher) ID(matcher specta.Matcher[string]) OrganizationMatcher {
	m.iDMatcher = matcher
	return m
}

// Name adds a matcher for the Name field.
func (m OrganizationMatcher) Name(matcher specta.Matcher[string]) OrganizationMatcher {
	m.nameMatcher = matcher
	return m
}

// CEO adds a matcher for the CEO field.
func (m OrganizationMatcher) CEO(matcher specta.Matcher[*showcase.User]) OrganizationMatcher {
	m.cEOMatcher = matcher
	return m
}

// Teams adds a matcher for the Teams field.
func (m OrganizationMatcher) Teams(matcher specta.Matcher[[]showcase.Team]) OrganizationMatcher {
	m.teamsMatcher = matcher
	return m
}

// Members adds a matcher for the Members field.
func (m OrganizationMatcher) Members(matcher specta.Matcher[[]showcase.Member]) OrganizationMatcher {
	m.membersMatcher = matcher
	return m
}

// Metadata adds a matcher for the Metadata field.
func (m OrganizationMatcher) Metadata(matcher specta.Matcher[map[string]string]) OrganizationMatcher {
	m.metadataMatcher = matcher
	return m
}

// Matches implements the Matcher[Organization] interface.
func (m OrganizationMatcher) Matches(actual showcase.Organization) specta.MatchResult {
	// Extract all field values upfront (call each getter exactly once)
	iDValue := actual.ID
	nameValue := actual.Name
	cEOValue := actual.CEO
	teamsValue := actual.Teams
	membersValue := actual.Members
	metadataValue := actual.Metadata

	// Build fieldValues map for structured diff
	fieldValues := map[string]any{
		"ID":       iDValue,
		"Name":     nameValue,
		"CEO":      cEOValue,
		"Teams":    teamsValue,
		"Members":  membersValue,
		"Metadata": metadataValue,
	}

	// Check matchers using cached values and store results
	fieldResults := make(map[string]*specta.MatchResult)
	hasFailures := false

	if m.iDMatcher != nil {
		result := m.iDMatcher.Matches(iDValue)
		fieldResults["ID"] = &result
		if !result.Matched {
			hasFailures = true
		}
	}

	if m.nameMatcher != nil {
		result := m.nameMatcher.Matches(nameValue)
		fieldResults["Name"] = &result
		if !result.Matched {
			hasFailures = true
		}
	}

	if m.cEOMatcher != nil {
		result := m.cEOMatcher.Matches(cEOValue)
		fieldResults["CEO"] = &result
		if !result.Matched {
			hasFailures = true
		}
	}

	if m.teamsMatcher != nil {
		result := m.teamsMatcher.Matches(teamsValue)
		fieldResults["Teams"] = &result
		if !result.Matched {
			hasFailures = true
		}
	}

	if m.membersMatcher != nil {
		result := m.membersMatcher.Matches(membersValue)
		fieldResults["Members"] = &result
		if !result.Matched {
			hasFailures = true
		}
	}

	if m.metadataMatcher != nil {
		result := m.metadataMatcher.Matches(metadataValue)
		fieldResults["Metadata"] = &result
		if !result.Matched {
			hasFailures = true
		}
	}

	if hasFailures {
		// Use structured diff for struct types
		structDiff := specta.BuildMatcherStructDiff("Organization", fieldValues, fieldResults)
		return specta.MatchResult{
			Matched: false,
			Message: structDiff,
		}
	}
	return specta.MatchResult{Matched: true}
}
