// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// This file contains the recipe (test data builder) for Organization.
//
// Use Organization() to build instances with custom fields, or Many() for multiple unique instances.
package factory

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
	"github.com/james-w/specta/showcase/factory/spec"
)

// OrganizationRecipe provides a fluent API for building Organization instances.
type OrganizationRecipe struct {
	opts      []specta.Opt[spec.OrganizationSpec]
	cEORecipe *UserRecipe
}

// Organization creates a new OrganizationRecipe for building Organization instances.
//
// This is a struct-based type with the following fields:
//   - ID (string)
//   - Name (string)
//   - CEO (*showcase.User)
//   - Teams ([]showcase.Team)
//   - Members ([]showcase.Member)
//   - Metadata (map[string]string)
//
// Example:
//
//	p := specta.New()
//	organization := factory.Organization().
//	    ID("custom_value").
//	    Name("another").
//	    Build(p)
func Organization() OrganizationRecipe { return OrganizationRecipe{} }

// ID sets the ID field.
func (r OrganizationRecipe) ID(v string) OrganizationRecipe {
	r.opts = append(r.opts, spec.WithOrganizationID(v))
	return r
}

// Name sets the Name field.
func (r OrganizationRecipe) Name(v string) OrganizationRecipe {
	r.opts = append(r.opts, spec.WithOrganizationName(v))
	return r
}

// CEO sets the CEO field.
func (r OrganizationRecipe) CEO(v *showcase.User) OrganizationRecipe {
	r.opts = append(r.opts, spec.WithOrganizationCEO(v))
	r.cEORecipe = nil
	return r
}

// CEOFromRecipe sets the CEO field using another Recipe (creates unique instances).
// The recipe is captured at call time (value semantics) - subsequent changes to v won't affect this recipe.
// The nested recipe is used for partial matching in AsEqualMatcher.
func (r OrganizationRecipe) CEOFromRecipe(v UserRecipe) OrganizationRecipe {
	r.opts = append(r.opts, spec.WithOrganizationCEOFromProvider(specta.PtrOf(v.Provider())))
	r.cEORecipe = &v
	return r
}

// Teams sets the Teams field.
func (r OrganizationRecipe) Teams(v []showcase.Team) OrganizationRecipe {
	r.opts = append(r.opts, spec.WithOrganizationTeams(v))
	return r
}

// Members sets the Members field.
func (r OrganizationRecipe) Members(v []showcase.Member) OrganizationRecipe {
	r.opts = append(r.opts, spec.WithOrganizationMembers(v))
	return r
}

// Metadata sets the Metadata field.
func (r OrganizationRecipe) Metadata(v map[string]string) OrganizationRecipe {
	r.opts = append(r.opts, spec.WithOrganizationMetadata(v))
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r OrganizationRecipe) Provider() specta.Provider[showcase.Organization] {
	return specta.FromSpec(spec.BuildOrganization, spec.NewOrganizationSpec, r.opts...)
}

// Build creates a single Organization instance.
func (r OrganizationRecipe) Build(p specta.Primitives) showcase.Organization {
	return spec.NewOrganizationFactory(p).Make(r.opts...)
}

// Many creates multiple Organization instances with unique generated values.
func (r OrganizationRecipe) Many(n int, p specta.Primitives) []showcase.Organization {
	return spec.NewOrganizationFactory(p).Many(n, r.opts...)
}

// AsEqualMatcher converts this Recipe into a Matcher that checks for equality on all set fields.
// Only fields that were explicitly set in the Recipe will be checked - unset fields are ignored.
// This enables partial matching where you only verify specific fields.
// For nested types set via FromRecipe, partial matching is applied recursively.
func (r OrganizationRecipe) AsEqualMatcher() specta.Matcher[showcase.Organization] {
	// Apply opts to a spec to see what was set
	s := spec.NewOrganizationSpec()
	for _, opt := range r.opts {
		opt(&s)
	}

	// Use a dummy Primitives to evaluate literal values
	// This works for SetLit values; SetWith/Provider values will be evaluated too
	p := specta.New()

	// Build matcher only for set fields
	m := OrganizationMatches()
	if s.ID.IsSet() {
		m = m.ID(specta.DeepEqual(s.ID.Value(p)))
	}
	if s.Name.IsSet() {
		m = m.Name(specta.DeepEqual(s.Name.Value(p)))
	}
	if s.CEO.IsSet() {
		// Check if we have a nested recipe for partial matching
		if r.cEORecipe != nil {
			m = m.CEO(specta.PointsTo(r.cEORecipe.AsEqualMatcher()))
		} else {
			m = m.CEO(specta.DeepEqual(s.CEO.Value(p)))
		}
	}
	if s.Teams.IsSet() {
		m = m.Teams(specta.DeepEqual(s.Teams.Value(p)))
	}
	if s.Members.IsSet() {
		m = m.Members(specta.DeepEqual(s.Members.Value(p)))
	}
	if s.Metadata.IsSet() {
		m = m.Metadata(specta.DeepEqual(s.Metadata.Value(p)))
	}

	return m.Matcher()
}
