// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	testgen "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// OrganizationMatcher provides a fluent API for matching Organization instances.
type OrganizationMatcher struct {
	iDMatcher       testgen.Matcher[string]
	nameMatcher     testgen.Matcher[string]
	cEOMatcher      testgen.Matcher[*showcase.User]
	teamsMatcher    testgen.Matcher[[]showcase.Team]
	membersMatcher  testgen.Matcher[[]showcase.Member]
	metadataMatcher testgen.Matcher[map[string]string]
}

// OrganizationMatches creates a new OrganizationMatcher for matching Organization instances.
//
// This matcher provides methods for the following fields:
//   - ID (string)
//   - Name (string)
//   - CEO (*showcase.User)
//   - Teams ([]showcase.Team)
//   - Members ([]showcase.Member)
//   - Metadata (map[string]string)
//
// Example:
//
//	matcher := factory.OrganizationMatches().
//	    ID(testgen.Equal("expected_value")).
//	    Name(testgen.Contains("substring")).
//	    Matcher()
//
//	testgen.AssertThat(t, actualOrganization, matcher)
func OrganizationMatches() OrganizationMatcher {
	return OrganizationMatcher{}
}

// ID adds a matcher for the ID field.
func (m OrganizationMatcher) ID(matcher testgen.Matcher[string]) OrganizationMatcher {
	m.iDMatcher = matcher
	return m
}

// Name adds a matcher for the Name field.
func (m OrganizationMatcher) Name(matcher testgen.Matcher[string]) OrganizationMatcher {
	m.nameMatcher = matcher
	return m
}

// CEO adds a matcher for the CEO field.
func (m OrganizationMatcher) CEO(matcher testgen.Matcher[*showcase.User]) OrganizationMatcher {
	m.cEOMatcher = matcher
	return m
}

// Teams adds a matcher for the Teams field.
func (m OrganizationMatcher) Teams(matcher testgen.Matcher[[]showcase.Team]) OrganizationMatcher {
	m.teamsMatcher = matcher
	return m
}

// Members adds a matcher for the Members field.
func (m OrganizationMatcher) Members(matcher testgen.Matcher[[]showcase.Member]) OrganizationMatcher {
	m.membersMatcher = matcher
	return m
}

// Metadata adds a matcher for the Metadata field.
func (m OrganizationMatcher) Metadata(matcher testgen.Matcher[map[string]string]) OrganizationMatcher {
	m.metadataMatcher = matcher
	return m
}

// Matcher returns the composed matcher for Organization.
func (m OrganizationMatcher) Matcher() testgen.Matcher[showcase.Organization] {
	return testgen.MatcherFunc[showcase.Organization](func(actual showcase.Organization) testgen.MatchResult {
		// Extract all field values upfront (call each getter exactly once)
		iDValue := actual.ID
		nameValue := actual.Name
		cEOValue := actual.CEO
		teamsValue := actual.Teams
		membersValue := actual.Members
		metadataValue := actual.Metadata

		// Build fieldValues map for structured diff
		fieldValues := map[string]any{
			"ID":       iDValue,
			"Name":     nameValue,
			"CEO":      cEOValue,
			"Teams":    teamsValue,
			"Members":  membersValue,
			"Metadata": metadataValue,
		}

		// Check matchers using cached values and store results
		fieldResults := make(map[string]*testgen.MatchResult)
		hasFailures := false

		if m.iDMatcher != nil {
			result := m.iDMatcher.Matches(iDValue)
			fieldResults["ID"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.nameMatcher != nil {
			result := m.nameMatcher.Matches(nameValue)
			fieldResults["Name"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.cEOMatcher != nil {
			result := m.cEOMatcher.Matches(cEOValue)
			fieldResults["CEO"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.teamsMatcher != nil {
			result := m.teamsMatcher.Matches(teamsValue)
			fieldResults["Teams"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.membersMatcher != nil {
			result := m.membersMatcher.Matches(membersValue)
			fieldResults["Members"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.metadataMatcher != nil {
			result := m.metadataMatcher.Matches(metadataValue)
			fieldResults["Metadata"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if hasFailures {
			// Use structured diff for struct types
			structDiff := testgen.BuildMatcherStructDiff("Organization", fieldValues, fieldResults)
			return testgen.MatchResult{
				Matched: false,
				Message: structDiff,
			}
		}
		return testgen.MatchResult{Matched: true}
	})
}
