// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	"time"

	testgen "github.com/james-w/gomatchers"
	"github.com/james-w/gomatchers/showcase"
	"github.com/james-w/gomatchers/showcase/factory/spec"
)

// ProductRecipe provides a fluent API for building Product instances.
type ProductRecipe struct {
	opts []testgen.Opt[spec.ProductSpec]
}

// Product creates a new ProductRecipe for building Product instances.
func Product() ProductRecipe { return ProductRecipe{} }

// ID sets the ID field.
func (r ProductRecipe) ID(v string) ProductRecipe {
	r.opts = append(r.opts, spec.WithProductID(v))
	return r
}

// Name sets the Name field.
func (r ProductRecipe) Name(v string) ProductRecipe {
	r.opts = append(r.opts, spec.WithProductName(v))
	return r
}

// Description sets the Description field.
func (r ProductRecipe) Description(v string) ProductRecipe {
	r.opts = append(r.opts, spec.WithProductDescription(v))
	return r
}

// Price sets the Price field.
func (r ProductRecipe) Price(v float64) ProductRecipe {
	r.opts = append(r.opts, spec.WithProductPrice(v))
	return r
}

// InStock sets the InStock field.
func (r ProductRecipe) InStock(v bool) ProductRecipe {
	r.opts = append(r.opts, spec.WithProductInStock(v))
	return r
}

// CreatedAt sets the CreatedAt field.
func (r ProductRecipe) CreatedAt(v time.Time) ProductRecipe {
	r.opts = append(r.opts, spec.WithProductCreatedAt(v))
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r ProductRecipe) Provider() testgen.Provider[showcase.Product] {
	return testgen.FromSpec(spec.BuildProduct, spec.NewProductSpec, r.opts...)
}

// Build creates a single Product instance.
func (r ProductRecipe) Build(p testgen.Primitives) showcase.Product {
	return spec.NewProductFactory(p).Make(r.opts...)
}

// Many creates multiple Product instances with unique generated values.
func (r ProductRecipe) Many(n int, p testgen.Primitives) []showcase.Product {
	return spec.NewProductFactory(p).Many(n, r.opts...)
}
