// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package factory provides a fluent Recipe API for building test data and matchers.
//
// Example usage:
//
//	// Build a single instance with custom fields
//
//
//	result := Product().ID("example").Build(testgen.New())
//
//
//
//	// Build many instances with unique values
//	results := Product().Many(5, testgen.New())
//
//	// Build a matcher to verify specific fields
//
//
//	matcher := ProductMatches().ID(testgen.DeepEqual("expected"))
//
//
//	testgen.AssertThat(t, actual, matcher.Matcher())
//
//	// Convert a recipe to a matcher for partial matching
//
//
//	partialMatcher := Product().ID("expected").AsEqualMatcher()
//
//
//	testgen.AssertThat(t, actual, partialMatcher)
package factory

import (
	"time"

	testgen "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
	"github.com/james-w/specta/showcase/factory/spec"
)

// ProductRecipe provides a fluent API for building Product instances.
type ProductRecipe struct {
	opts []testgen.Opt[spec.ProductSpec]
}

// Product creates a new ProductRecipe for building Product instances.
//
// This is a struct-based type with the following fields:
//   - ID (string)
//   - Name (string)
//   - Description (string)
//   - Price (float64)
//   - InStock (bool)
//   - CreatedAt (time.Time)
//
// Example:
//
//	p := testgen.New()
//	product := factory.Product().
//	    ID("custom_value").
//	    Name("another").
//	    Build(p)
func Product() ProductRecipe { return ProductRecipe{} }

// ID sets the ID field.
func (r ProductRecipe) ID(v string) ProductRecipe {
	r.opts = append(r.opts, spec.WithProductID(v))
	return r
}

// Name sets the Name field.
func (r ProductRecipe) Name(v string) ProductRecipe {
	r.opts = append(r.opts, spec.WithProductName(v))
	return r
}

// Description sets the Description field.
func (r ProductRecipe) Description(v string) ProductRecipe {
	r.opts = append(r.opts, spec.WithProductDescription(v))
	return r
}

// Price sets the Price field.
func (r ProductRecipe) Price(v float64) ProductRecipe {
	r.opts = append(r.opts, spec.WithProductPrice(v))
	return r
}

// InStock sets the InStock field.
func (r ProductRecipe) InStock(v bool) ProductRecipe {
	r.opts = append(r.opts, spec.WithProductInStock(v))
	return r
}

// CreatedAt sets the CreatedAt field.
func (r ProductRecipe) CreatedAt(v time.Time) ProductRecipe {
	r.opts = append(r.opts, spec.WithProductCreatedAt(v))
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r ProductRecipe) Provider() testgen.Provider[showcase.Product] {
	return testgen.FromSpec(spec.BuildProduct, spec.NewProductSpec, r.opts...)
}

// Build creates a single Product instance.
func (r ProductRecipe) Build(p testgen.Primitives) showcase.Product {
	return spec.NewProductFactory(p).Make(r.opts...)
}

// Many creates multiple Product instances with unique generated values.
func (r ProductRecipe) Many(n int, p testgen.Primitives) []showcase.Product {
	return spec.NewProductFactory(p).Many(n, r.opts...)
}

// AsEqualMatcher converts this Recipe into a Matcher that checks for equality on all set fields.
// Only fields that were explicitly set in the Recipe will be checked - unset fields are ignored.
// This enables partial matching where you only verify specific fields.
// For nested types set via FromRecipe, partial matching is applied recursively.
func (r ProductRecipe) AsEqualMatcher() testgen.Matcher[showcase.Product] {
	// Apply opts to a spec to see what was set
	s := spec.NewProductSpec()
	for _, opt := range r.opts {
		opt(&s)
	}

	// Use a dummy Primitives to evaluate literal values
	// This works for SetLit values; SetWith/Provider values will be evaluated too
	p := testgen.New()

	// Build matcher only for set fields
	m := ProductMatches()
	if s.ID.IsSet() {
		m = m.ID(testgen.DeepEqual(s.ID.Value(p)))
	}
	if s.Name.IsSet() {
		m = m.Name(testgen.DeepEqual(s.Name.Value(p)))
	}
	if s.Description.IsSet() {
		m = m.Description(testgen.DeepEqual(s.Description.Value(p)))
	}
	if s.Price.IsSet() {
		m = m.Price(testgen.DeepEqual(s.Price.Value(p)))
	}
	if s.InStock.IsSet() {
		m = m.InStock(testgen.DeepEqual(s.InStock.Value(p)))
	}
	if s.CreatedAt.IsSet() {
		m = m.CreatedAt(testgen.DeepEqual(s.CreatedAt.Value(p)))
	}

	return m.Matcher()
}
