// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	"time"

	testgen "github.com/james-w/gomatchers"
	"github.com/james-w/gomatchers/showcase"
)

// ProductMatcher provides a fluent API for matching Product instances.
type ProductMatcher struct {
	iDMatcher          testgen.Matcher[string]
	nameMatcher        testgen.Matcher[string]
	descriptionMatcher testgen.Matcher[string]
	priceMatcher       testgen.Matcher[float64]
	inStockMatcher     testgen.Matcher[bool]
	createdAtMatcher   testgen.Matcher[time.Time]
}

// ProductMatches creates a new ProductMatcher for matching Product instances.
func ProductMatches() ProductMatcher {
	return ProductMatcher{}
}

// ID adds a matcher for the ID field.
func (m ProductMatcher) ID(matcher testgen.Matcher[string]) ProductMatcher {
	m.iDMatcher = matcher
	return m
}

// Name adds a matcher for the Name field.
func (m ProductMatcher) Name(matcher testgen.Matcher[string]) ProductMatcher {
	m.nameMatcher = matcher
	return m
}

// Description adds a matcher for the Description field.
func (m ProductMatcher) Description(matcher testgen.Matcher[string]) ProductMatcher {
	m.descriptionMatcher = matcher
	return m
}

// Price adds a matcher for the Price field.
func (m ProductMatcher) Price(matcher testgen.Matcher[float64]) ProductMatcher {
	m.priceMatcher = matcher
	return m
}

// InStock adds a matcher for the InStock field.
func (m ProductMatcher) InStock(matcher testgen.Matcher[bool]) ProductMatcher {
	m.inStockMatcher = matcher
	return m
}

// CreatedAt adds a matcher for the CreatedAt field.
func (m ProductMatcher) CreatedAt(matcher testgen.Matcher[time.Time]) ProductMatcher {
	m.createdAtMatcher = matcher
	return m
}

// Matcher returns the composed matcher for Product.
func (m ProductMatcher) Matcher() testgen.Matcher[showcase.Product] {
	return testgen.MatcherFunc[showcase.Product](func(actual showcase.Product) testgen.MatchResult {
		var failures []string
		if m.iDMatcher != nil {
			result := m.iDMatcher.Matches(actual.ID)
			if !result.Matched {
				failures = append(failures, "ID: "+result.Message)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.nameMatcher != nil {
			result := m.nameMatcher.Matches(actual.Name)
			if !result.Matched {
				failures = append(failures, "Name: "+result.Message)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.descriptionMatcher != nil {
			result := m.descriptionMatcher.Matches(actual.Description)
			if !result.Matched {
				failures = append(failures, "Description: "+result.Message)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.priceMatcher != nil {
			result := m.priceMatcher.Matches(actual.Price)
			if !result.Matched {
				failures = append(failures, "Price: "+result.Message)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.inStockMatcher != nil {
			result := m.inStockMatcher.Matches(actual.InStock)
			if !result.Matched {
				failures = append(failures, "InStock: "+result.Message)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}
		if m.createdAtMatcher != nil {
			result := m.createdAtMatcher.Matches(actual.CreatedAt)
			if !result.Matched {
				failures = append(failures, "CreatedAt: "+result.Message)
				for _, detail := range result.Details {
					failures = append(failures, "  "+detail)
				}
			}
		}

		if len(failures) > 0 {
			return testgen.MatchResult{
				Matched: false,
				Message: "Product did not match",
				Details: failures,
			}
		}
		return testgen.MatchResult{Matched: true}
	})
}
