// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package factory provides a fluent Recipe API for building test data and matchers.
//
// Example usage:
//
//	// Build a single instance with custom fields
//
//
//	result := Profile().ID("example").Build(specta.New())
//
//
//
//	// Build many instances with unique values
//	results := Profile().Many(5, specta.New())
//
//	// Build a matcher to verify specific fields
//
//
//	matcher := ProfileMatches().ID(specta.DeepEqual("expected"))
//
//
//	specta.AssertThat(t, actual, matcher.Matcher())
//
//	// Convert a recipe to a matcher for partial matching
//
//
//	partialMatcher := Profile().ID("expected").AsEqualMatcher()
//
//
//	specta.AssertThat(t, actual, partialMatcher)
package factory

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
	"github.com/james-w/specta/showcase/factory/spec"
)

// ProfileRecipe provides a fluent API for building Profile instances.
type ProfileRecipe struct {
	opts          []specta.Opt[spec.ProfileSpec]
	managerRecipe *UserRecipe
}

// Profile creates a new ProfileRecipe for building Profile instances.
//
// This is a struct-based type with the following fields:
//   - ID (string)
//   - Name (string)
//   - Description (string)
//   - Manager (*showcase.User)
//   - IsPublic (bool)
//
// Example:
//
//	p := specta.New()
//	profile := factory.Profile().
//	    ID("custom_value").
//	    Name("another").
//	    Build(p)
func Profile() ProfileRecipe { return ProfileRecipe{} }

// ID sets the ID field.
func (r ProfileRecipe) ID(v string) ProfileRecipe {
	r.opts = append(r.opts, spec.WithProfileID(v))
	return r
}

// Name sets the Name field.
func (r ProfileRecipe) Name(v string) ProfileRecipe {
	r.opts = append(r.opts, spec.WithProfileName(v))
	return r
}

// Description sets the Description field.
func (r ProfileRecipe) Description(v string) ProfileRecipe {
	r.opts = append(r.opts, spec.WithProfileDescription(v))
	return r
}

// Manager sets the Manager field.
func (r ProfileRecipe) Manager(v *showcase.User) ProfileRecipe {
	r.opts = append(r.opts, spec.WithProfileManager(v))
	r.managerRecipe = nil
	return r
}

// ManagerFromRecipe sets the Manager field using another Recipe (creates unique instances).
// The recipe is captured at call time (value semantics) - subsequent changes to v won't affect this recipe.
// The nested recipe is used for partial matching in AsEqualMatcher.
func (r ProfileRecipe) ManagerFromRecipe(v UserRecipe) ProfileRecipe {
	r.opts = append(r.opts, spec.WithProfileManagerFromProvider(specta.PtrOf(v.Provider())))
	r.managerRecipe = &v
	return r
}

// IsPublic sets the IsPublic field.
func (r ProfileRecipe) IsPublic(v bool) ProfileRecipe {
	r.opts = append(r.opts, spec.WithProfileIsPublic(v))
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r ProfileRecipe) Provider() specta.Provider[showcase.Profile] {
	return specta.FromSpec(spec.BuildProfile, spec.NewProfileSpec, r.opts...)
}

// Build creates a single Profile instance.
func (r ProfileRecipe) Build(p specta.Primitives) showcase.Profile {
	return spec.NewProfileFactory(p).Make(r.opts...)
}

// Many creates multiple Profile instances with unique generated values.
func (r ProfileRecipe) Many(n int, p specta.Primitives) []showcase.Profile {
	return spec.NewProfileFactory(p).Many(n, r.opts...)
}

// AsEqualMatcher converts this Recipe into a Matcher that checks for equality on all set fields.
// Only fields that were explicitly set in the Recipe will be checked - unset fields are ignored.
// This enables partial matching where you only verify specific fields.
// For nested types set via FromRecipe, partial matching is applied recursively.
func (r ProfileRecipe) AsEqualMatcher() specta.Matcher[showcase.Profile] {
	// Apply opts to a spec to see what was set
	s := spec.NewProfileSpec()
	for _, opt := range r.opts {
		opt(&s)
	}

	// Use a dummy Primitives to evaluate literal values
	// This works for SetLit values; SetWith/Provider values will be evaluated too
	p := specta.New()

	// Build matcher only for set fields
	m := ProfileMatches()
	if s.ID.IsSet() {
		m = m.ID(specta.DeepEqual(s.ID.Value(p)))
	}
	if s.Name.IsSet() {
		m = m.Name(specta.DeepEqual(s.Name.Value(p)))
	}
	if s.Description.IsSet() {
		m = m.Description(specta.DeepEqual(s.Description.Value(p)))
	}
	if s.Manager.IsSet() {
		// Check if we have a nested recipe for partial matching
		if r.managerRecipe != nil {
			m = m.Manager(specta.PointsTo(r.managerRecipe.AsEqualMatcher()))
		} else {
			m = m.Manager(specta.DeepEqual(s.Manager.Value(p)))
		}
	}
	if s.IsPublic.IsSet() {
		m = m.IsPublic(specta.DeepEqual(s.IsPublic.Value(p)))
	}

	return m.Matcher()
}
