// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	testgen "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// ProfileMatcher provides a fluent API for matching Profile instances.
type ProfileMatcher struct {
	iDMatcher          testgen.Matcher[string]
	nameMatcher        testgen.Matcher[string]
	descriptionMatcher testgen.Matcher[string]
	managerMatcher     testgen.Matcher[*showcase.User]
	isPublicMatcher    testgen.Matcher[bool]
}

// ProfileMatches creates a new ProfileMatcher for matching Profile instances.
func ProfileMatches() ProfileMatcher {
	return ProfileMatcher{}
}

// ID adds a matcher for the ID field.
func (m ProfileMatcher) ID(matcher testgen.Matcher[string]) ProfileMatcher {
	m.iDMatcher = matcher
	return m
}

// Name adds a matcher for the Name field.
func (m ProfileMatcher) Name(matcher testgen.Matcher[string]) ProfileMatcher {
	m.nameMatcher = matcher
	return m
}

// Description adds a matcher for the Description field.
func (m ProfileMatcher) Description(matcher testgen.Matcher[string]) ProfileMatcher {
	m.descriptionMatcher = matcher
	return m
}

// Manager adds a matcher for the Manager field.
func (m ProfileMatcher) Manager(matcher testgen.Matcher[*showcase.User]) ProfileMatcher {
	m.managerMatcher = matcher
	return m
}

// IsPublic adds a matcher for the IsPublic field.
func (m ProfileMatcher) IsPublic(matcher testgen.Matcher[bool]) ProfileMatcher {
	m.isPublicMatcher = matcher
	return m
}

// Matcher returns the composed matcher for Profile.
func (m ProfileMatcher) Matcher() testgen.Matcher[showcase.Profile] {
	return testgen.MatcherFunc[showcase.Profile](func(actual showcase.Profile) testgen.MatchResult {
		// Extract all field values upfront (call each getter exactly once)
		iDValue := actual.ID
		nameValue := actual.Name
		descriptionValue := actual.Description
		managerValue := actual.Manager
		isPublicValue := actual.IsPublic

		// Build fieldValues map for structured diff
		fieldValues := map[string]any{
			"ID":          iDValue,
			"Name":        nameValue,
			"Description": descriptionValue,
			"Manager":     managerValue,
			"IsPublic":    isPublicValue,
		}

		// Check matchers using cached values and store results
		fieldResults := make(map[string]*testgen.MatchResult)
		hasFailures := false

		if m.iDMatcher != nil {
			result := m.iDMatcher.Matches(iDValue)
			fieldResults["ID"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.nameMatcher != nil {
			result := m.nameMatcher.Matches(nameValue)
			fieldResults["Name"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.descriptionMatcher != nil {
			result := m.descriptionMatcher.Matches(descriptionValue)
			fieldResults["Description"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.managerMatcher != nil {
			result := m.managerMatcher.Matches(managerValue)
			fieldResults["Manager"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.isPublicMatcher != nil {
			result := m.isPublicMatcher.Matches(isPublicValue)
			fieldResults["IsPublic"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if hasFailures {
			// Use structured diff for struct types
			structDiff := testgen.BuildMatcherStructDiff("Profile", fieldValues, fieldResults)
			return testgen.MatchResult{
				Matched: false,
				Message: structDiff,
			}
		}
		return testgen.MatchResult{Matched: true}
	})
}
