// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package factory provides a fluent Recipe API for building test data and matchers.
//
// This file contains generated matchers for type-safe assertions.
//
// Example usage:
//
//	// Create a matcher for specific fields
//	matcher := factory.ProfileMatches().
//	    ID(specta.Equal("expected")).
//	    Matcher()
//	specta.AssertThat(t, actual, matcher)
//
//	// For partial matching, use Recipe.AsEqualMatcher():
//	partial := factory.Profile().ID("expected").AsEqualMatcher()
//	specta.AssertThat(t, actual, partial)
package factory

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// ProfileMatcher provides a fluent API for matching Profile instances.
type ProfileMatcher struct {
	iDMatcher          specta.Matcher[string]
	nameMatcher        specta.Matcher[string]
	descriptionMatcher specta.Matcher[string]
	managerMatcher     specta.Matcher[*showcase.User]
	isPublicMatcher    specta.Matcher[bool]
}

// ProfileMatches creates a new ProfileMatcher for matching Profile instances.
//
// This matcher provides methods for the following fields:
//   - ID (string)
//   - Name (string)
//   - Description (string)
//   - Manager (*showcase.User)
//   - IsPublic (bool)
//
// Example:
//
//	matcher := factory.ProfileMatches().
//	    ID(specta.Equal("expected_value")).
//	    Name(specta.Contains("substring")).
//	    Matcher()
//
//	specta.AssertThat(t, actualProfile, matcher)
func ProfileMatches() ProfileMatcher {
	return ProfileMatcher{}
}

// ID adds a matcher for the ID field.
func (m ProfileMatcher) ID(matcher specta.Matcher[string]) ProfileMatcher {
	m.iDMatcher = matcher
	return m
}

// Name adds a matcher for the Name field.
func (m ProfileMatcher) Name(matcher specta.Matcher[string]) ProfileMatcher {
	m.nameMatcher = matcher
	return m
}

// Description adds a matcher for the Description field.
func (m ProfileMatcher) Description(matcher specta.Matcher[string]) ProfileMatcher {
	m.descriptionMatcher = matcher
	return m
}

// Manager adds a matcher for the Manager field.
func (m ProfileMatcher) Manager(matcher specta.Matcher[*showcase.User]) ProfileMatcher {
	m.managerMatcher = matcher
	return m
}

// IsPublic adds a matcher for the IsPublic field.
func (m ProfileMatcher) IsPublic(matcher specta.Matcher[bool]) ProfileMatcher {
	m.isPublicMatcher = matcher
	return m
}

// Matcher returns the composed matcher for Profile.
func (m ProfileMatcher) Matcher() specta.Matcher[showcase.Profile] {
	return specta.MatcherFunc[showcase.Profile](func(actual showcase.Profile) specta.MatchResult {
		// Extract all field values upfront (call each getter exactly once)
		iDValue := actual.ID
		nameValue := actual.Name
		descriptionValue := actual.Description
		managerValue := actual.Manager
		isPublicValue := actual.IsPublic

		// Build fieldValues map for structured diff
		fieldValues := map[string]any{
			"ID":          iDValue,
			"Name":        nameValue,
			"Description": descriptionValue,
			"Manager":     managerValue,
			"IsPublic":    isPublicValue,
		}

		// Check matchers using cached values and store results
		fieldResults := make(map[string]*specta.MatchResult)
		hasFailures := false

		if m.iDMatcher != nil {
			result := m.iDMatcher.Matches(iDValue)
			fieldResults["ID"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.nameMatcher != nil {
			result := m.nameMatcher.Matches(nameValue)
			fieldResults["Name"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.descriptionMatcher != nil {
			result := m.descriptionMatcher.Matches(descriptionValue)
			fieldResults["Description"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.managerMatcher != nil {
			result := m.managerMatcher.Matches(managerValue)
			fieldResults["Manager"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.isPublicMatcher != nil {
			result := m.isPublicMatcher.Matches(isPublicValue)
			fieldResults["IsPublic"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if hasFailures {
			// Use structured diff for struct types
			structDiff := specta.BuildMatcherStructDiff("Profile", fieldValues, fieldResults)
			return specta.MatchResult{
				Matched: false,
				Message: structDiff,
			}
		}
		return specta.MatchResult{Matched: true}
	})
}
