// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package factory provides a fluent Recipe API for building test data and matchers.
//
// This file contains generated matchers for type-safe assertions.
//
// Example usage:
//
//	// Create a matcher for specific fields
//	matcher := factory.TeamMatches().
//	    ID(specta.Equal("expected")).
//	    Matcher()
//	specta.AssertThat(t, actual, matcher)
//
//	// For partial matching, use Recipe.AsEqualMatcher():
//	partial := factory.Team().ID("expected").AsEqualMatcher()
//	specta.AssertThat(t, actual, partial)
package factory

import (
	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// TeamMatcher provides a fluent API for matching Team instances.
type TeamMatcher struct {
	iDMatcher      specta.Matcher[string]
	nameMatcher    specta.Matcher[string]
	membersMatcher specta.Matcher[[]showcase.Member]
}

// TeamMatches creates a new TeamMatcher for matching Team instances.
//
// This matcher provides methods for the following fields:
//   - ID (string)
//   - Name (string)
//   - Members ([]showcase.Member)
//
// Example:
//
//	matcher := factory.TeamMatches().
//	    ID(specta.Equal("expected_value")).
//	    Name(specta.Contains("substring")).
//	    Matcher()
//
//	specta.AssertThat(t, actualTeam, matcher)
func TeamMatches() TeamMatcher {
	return TeamMatcher{}
}

// ID adds a matcher for the ID field.
func (m TeamMatcher) ID(matcher specta.Matcher[string]) TeamMatcher {
	m.iDMatcher = matcher
	return m
}

// Name adds a matcher for the Name field.
func (m TeamMatcher) Name(matcher specta.Matcher[string]) TeamMatcher {
	m.nameMatcher = matcher
	return m
}

// Members adds a matcher for the Members field.
func (m TeamMatcher) Members(matcher specta.Matcher[[]showcase.Member]) TeamMatcher {
	m.membersMatcher = matcher
	return m
}

// Matcher returns the composed matcher for Team.
func (m TeamMatcher) Matcher() specta.Matcher[showcase.Team] {
	return specta.MatcherFunc[showcase.Team](func(actual showcase.Team) specta.MatchResult {
		// Extract all field values upfront (call each getter exactly once)
		iDValue := actual.ID
		nameValue := actual.Name
		membersValue := actual.Members

		// Build fieldValues map for structured diff
		fieldValues := map[string]any{
			"ID":      iDValue,
			"Name":    nameValue,
			"Members": membersValue,
		}

		// Check matchers using cached values and store results
		fieldResults := make(map[string]*specta.MatchResult)
		hasFailures := false

		if m.iDMatcher != nil {
			result := m.iDMatcher.Matches(iDValue)
			fieldResults["ID"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.nameMatcher != nil {
			result := m.nameMatcher.Matches(nameValue)
			fieldResults["Name"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.membersMatcher != nil {
			result := m.membersMatcher.Matches(membersValue)
			fieldResults["Members"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if hasFailures {
			// Use structured diff for struct types
			structDiff := specta.BuildMatcherStructDiff("Team", fieldValues, fieldResults)
			return specta.MatchResult{
				Matched: false,
				Message: structDiff,
			}
		}
		return specta.MatchResult{Matched: true}
	})
}
