// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package factory provides a fluent Recipe API for building test data and matchers.
//
// Example usage:
//
//	// Build a single instance with custom fields
//
//
//	result := Team().ID("example").Build(testgen.New())
//
//
//
//	// Build many instances with unique values
//	results := Team().Many(5, testgen.New())
//
//	// Build a matcher to verify specific fields
//
//
//	matcher := TeamMatches().ID(testgen.DeepEqual("expected"))
//
//
//	testgen.AssertThat(t, actual, matcher.Matcher())
//
//	// Convert a recipe to a matcher for partial matching
//
//
//	partialMatcher := Team().ID("expected").AsEqualMatcher()
//
//
//	testgen.AssertThat(t, actual, partialMatcher)
package factory

import (
	testgen "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
	"github.com/james-w/specta/showcase/factory/spec"
)

// TeamRecipe provides a fluent API for building Team instances.
type TeamRecipe struct {
	opts []testgen.Opt[spec.TeamSpec]
}

// Team creates a new TeamRecipe for building Team instances.
//
// This is a struct-based type with the following fields:
//   - ID (string)
//   - Name (string)
//   - Members ([]showcase.Member)
//
// Example:
//
//	p := testgen.New()
//	team := factory.Team().
//	    ID("custom_value").
//	    Name("another").
//	    Build(p)
func Team() TeamRecipe { return TeamRecipe{} }

// ID sets the ID field.
func (r TeamRecipe) ID(v string) TeamRecipe {
	r.opts = append(r.opts, spec.WithTeamID(v))
	return r
}

// Name sets the Name field.
func (r TeamRecipe) Name(v string) TeamRecipe {
	r.opts = append(r.opts, spec.WithTeamName(v))
	return r
}

// Members sets the Members field.
func (r TeamRecipe) Members(v []showcase.Member) TeamRecipe {
	r.opts = append(r.opts, spec.WithTeamMembers(v))
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r TeamRecipe) Provider() testgen.Provider[showcase.Team] {
	return testgen.FromSpec(spec.BuildTeam, spec.NewTeamSpec, r.opts...)
}

// Build creates a single Team instance.
func (r TeamRecipe) Build(p testgen.Primitives) showcase.Team {
	return spec.NewTeamFactory(p).Make(r.opts...)
}

// Many creates multiple Team instances with unique generated values.
func (r TeamRecipe) Many(n int, p testgen.Primitives) []showcase.Team {
	return spec.NewTeamFactory(p).Many(n, r.opts...)
}

// AsEqualMatcher converts this Recipe into a Matcher that checks for equality on all set fields.
// Only fields that were explicitly set in the Recipe will be checked - unset fields are ignored.
// This enables partial matching where you only verify specific fields.
// For nested types set via FromRecipe, partial matching is applied recursively.
func (r TeamRecipe) AsEqualMatcher() testgen.Matcher[showcase.Team] {
	// Apply opts to a spec to see what was set
	s := spec.NewTeamSpec()
	for _, opt := range r.opts {
		opt(&s)
	}

	// Use a dummy Primitives to evaluate literal values
	// This works for SetLit values; SetWith/Provider values will be evaluated too
	p := testgen.New()

	// Build matcher only for set fields
	m := TeamMatches()
	if s.ID.IsSet() {
		m = m.ID(testgen.DeepEqual(s.ID.Value(p)))
	}
	if s.Name.IsSet() {
		m = m.Name(testgen.DeepEqual(s.Name.Value(p)))
	}
	if s.Members.IsSet() {
		m = m.Members(testgen.DeepEqual(s.Members.Value(p)))
	}

	return m.Matcher()
}
