// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	testgen "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// TeamMatcher provides a fluent API for matching Team instances.
type TeamMatcher struct {
	iDMatcher      testgen.Matcher[string]
	nameMatcher    testgen.Matcher[string]
	membersMatcher testgen.Matcher[[]showcase.Member]
}

// TeamMatches creates a new TeamMatcher for matching Team instances.
func TeamMatches() TeamMatcher {
	return TeamMatcher{}
}

// ID adds a matcher for the ID field.
func (m TeamMatcher) ID(matcher testgen.Matcher[string]) TeamMatcher {
	m.iDMatcher = matcher
	return m
}

// Name adds a matcher for the Name field.
func (m TeamMatcher) Name(matcher testgen.Matcher[string]) TeamMatcher {
	m.nameMatcher = matcher
	return m
}

// Members adds a matcher for the Members field.
func (m TeamMatcher) Members(matcher testgen.Matcher[[]showcase.Member]) TeamMatcher {
	m.membersMatcher = matcher
	return m
}

// Matcher returns the composed matcher for Team.
func (m TeamMatcher) Matcher() testgen.Matcher[showcase.Team] {
	return testgen.MatcherFunc[showcase.Team](func(actual showcase.Team) testgen.MatchResult {
		// Extract all field values upfront (call each getter exactly once)
		iDValue := actual.ID
		nameValue := actual.Name
		membersValue := actual.Members

		// Build fieldValues map for structured diff
		fieldValues := map[string]any{
			"ID":      iDValue,
			"Name":    nameValue,
			"Members": membersValue,
		}

		// Check matchers using cached values and store results
		fieldResults := make(map[string]*testgen.MatchResult)
		hasFailures := false

		if m.iDMatcher != nil {
			result := m.iDMatcher.Matches(iDValue)
			fieldResults["ID"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.nameMatcher != nil {
			result := m.nameMatcher.Matches(nameValue)
			fieldResults["Name"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.membersMatcher != nil {
			result := m.membersMatcher.Matches(membersValue)
			fieldResults["Members"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if hasFailures {
			// Use structured diff for struct types
			structDiff := testgen.BuildMatcherStructDiff("Team", fieldValues, fieldResults)
			return testgen.MatchResult{
				Matched: false,
				Message: structDiff,
			}
		}
		return testgen.MatchResult{Matched: true}
	})
}
