// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// Package factory provides a fluent Recipe API for building test data and matchers.
//
// Example usage:
//
//	// Build a single instance with custom fields
//
//
//	result := User().ID("example").Build(testgen.New())
//
//
//
//	// Build many instances with unique values
//	results := User().Many(5, testgen.New())
//
//	// Build a matcher to verify specific fields
//
//
//	matcher := UserMatches().ID(testgen.DeepEqual("expected"))
//
//
//	testgen.AssertThat(t, actual, matcher.Matcher())
//
//	// Convert a recipe to a matcher for partial matching
//
//
//	partialMatcher := User().ID("expected").AsEqualMatcher()
//
//
//	testgen.AssertThat(t, actual, partialMatcher)
package factory

import (
	"time"

	testgen "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
	"github.com/james-w/specta/showcase/factory/spec"
)

// UserRecipe provides a fluent API for building User instances.
type UserRecipe struct {
	opts          []testgen.Opt[spec.UserSpec]
	addressRecipe *AddressRecipe
}

// User creates a new UserRecipe for building User instances.
//
// This is a struct-based type with the following fields:
//   - ID (string)
//   - Email (string)
//   - FirstName (string)
//   - LastName (string)
//   - Active (bool)
//   - Address (showcase.Address)
//   - CreatedAt (time.Time)
//   - UpdatedAt (time.Time)
//
// Example:
//
//	p := testgen.New()
//	user := factory.User().
//	    ID("custom_value").
//	    Email("another").
//	    Build(p)
func User() UserRecipe { return UserRecipe{} }

// ID sets the ID field.
func (r UserRecipe) ID(v string) UserRecipe {
	r.opts = append(r.opts, spec.WithUserID(v))
	return r
}

// Email sets the Email field.
func (r UserRecipe) Email(v string) UserRecipe {
	r.opts = append(r.opts, spec.WithUserEmail(v))
	return r
}

// FirstName sets the FirstName field.
func (r UserRecipe) FirstName(v string) UserRecipe {
	r.opts = append(r.opts, spec.WithUserFirstName(v))
	return r
}

// LastName sets the LastName field.
func (r UserRecipe) LastName(v string) UserRecipe {
	r.opts = append(r.opts, spec.WithUserLastName(v))
	return r
}

// Active sets the Active field.
func (r UserRecipe) Active(v bool) UserRecipe {
	r.opts = append(r.opts, spec.WithUserActive(v))
	return r
}

// Address sets the Address field.
func (r UserRecipe) Address(v showcase.Address) UserRecipe {
	r.opts = append(r.opts, spec.WithUserAddress(v))
	r.addressRecipe = nil
	return r
}

// AddressFromRecipe sets the Address field using another Recipe (creates unique instances).
// The recipe is captured at call time (value semantics) - subsequent changes to v won't affect this recipe.
// The nested recipe is used for partial matching in AsEqualMatcher.
func (r UserRecipe) AddressFromRecipe(v AddressRecipe) UserRecipe {
	r.opts = append(r.opts, spec.WithUserAddressFromProvider(v.Provider()))
	r.addressRecipe = &v
	return r
}

// CreatedAt sets the CreatedAt field.
func (r UserRecipe) CreatedAt(v time.Time) UserRecipe {
	r.opts = append(r.opts, spec.WithUserCreatedAt(v))
	return r
}

// UpdatedAt sets the UpdatedAt field.
func (r UserRecipe) UpdatedAt(v time.Time) UserRecipe {
	r.opts = append(r.opts, spec.WithUserUpdatedAt(v))
	return r
}

// Provider returns a Provider for lazy evaluation in parent factories.
func (r UserRecipe) Provider() testgen.Provider[showcase.User] {
	return testgen.FromSpec(spec.BuildUser, spec.NewUserSpec, r.opts...)
}

// Build creates a single User instance.
func (r UserRecipe) Build(p testgen.Primitives) showcase.User {
	return spec.NewUserFactory(p).Make(r.opts...)
}

// Many creates multiple User instances with unique generated values.
func (r UserRecipe) Many(n int, p testgen.Primitives) []showcase.User {
	return spec.NewUserFactory(p).Many(n, r.opts...)
}

// AsEqualMatcher converts this Recipe into a Matcher that checks for equality on all set fields.
// Only fields that were explicitly set in the Recipe will be checked - unset fields are ignored.
// This enables partial matching where you only verify specific fields.
// For nested types set via FromRecipe, partial matching is applied recursively.
func (r UserRecipe) AsEqualMatcher() testgen.Matcher[showcase.User] {
	// Apply opts to a spec to see what was set
	s := spec.NewUserSpec()
	for _, opt := range r.opts {
		opt(&s)
	}

	// Use a dummy Primitives to evaluate literal values
	// This works for SetLit values; SetWith/Provider values will be evaluated too
	p := testgen.New()

	// Build matcher only for set fields
	m := UserMatches()
	if s.ID.IsSet() {
		m = m.ID(testgen.DeepEqual(s.ID.Value(p)))
	}
	if s.Email.IsSet() {
		m = m.Email(testgen.DeepEqual(s.Email.Value(p)))
	}
	if s.FirstName.IsSet() {
		m = m.FirstName(testgen.DeepEqual(s.FirstName.Value(p)))
	}
	if s.LastName.IsSet() {
		m = m.LastName(testgen.DeepEqual(s.LastName.Value(p)))
	}
	if s.Active.IsSet() {
		m = m.Active(testgen.DeepEqual(s.Active.Value(p)))
	}
	if s.Address.IsSet() {
		// Check if we have a nested recipe for partial matching
		if r.addressRecipe != nil {
			m = m.Address(r.addressRecipe.AsEqualMatcher())
		} else {
			m = m.Address(testgen.DeepEqual(s.Address.Value(p)))
		}
	}
	if s.CreatedAt.IsSet() {
		m = m.CreatedAt(testgen.DeepEqual(s.CreatedAt.Value(p)))
	}
	if s.UpdatedAt.IsSet() {
		m = m.UpdatedAt(testgen.DeepEqual(s.UpdatedAt.Value(p)))
	}

	return m.Matcher()
}
