// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	"time"

	testgen "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// UserMatcher provides a fluent API for matching User instances.
type UserMatcher struct {
	iDMatcher        testgen.Matcher[string]
	emailMatcher     testgen.Matcher[string]
	firstNameMatcher testgen.Matcher[string]
	lastNameMatcher  testgen.Matcher[string]
	activeMatcher    testgen.Matcher[bool]
	addressMatcher   testgen.Matcher[showcase.Address]
	createdAtMatcher testgen.Matcher[time.Time]
	updatedAtMatcher testgen.Matcher[time.Time]
}

// UserMatches creates a new UserMatcher for matching User instances.
func UserMatches() UserMatcher {
	return UserMatcher{}
}

// ID adds a matcher for the ID field.
func (m UserMatcher) ID(matcher testgen.Matcher[string]) UserMatcher {
	m.iDMatcher = matcher
	return m
}

// Email adds a matcher for the Email field.
func (m UserMatcher) Email(matcher testgen.Matcher[string]) UserMatcher {
	m.emailMatcher = matcher
	return m
}

// FirstName adds a matcher for the FirstName field.
func (m UserMatcher) FirstName(matcher testgen.Matcher[string]) UserMatcher {
	m.firstNameMatcher = matcher
	return m
}

// LastName adds a matcher for the LastName field.
func (m UserMatcher) LastName(matcher testgen.Matcher[string]) UserMatcher {
	m.lastNameMatcher = matcher
	return m
}

// Active adds a matcher for the Active field.
func (m UserMatcher) Active(matcher testgen.Matcher[bool]) UserMatcher {
	m.activeMatcher = matcher
	return m
}

// Address adds a matcher for the Address field.
func (m UserMatcher) Address(matcher testgen.Matcher[showcase.Address]) UserMatcher {
	m.addressMatcher = matcher
	return m
}

// AddressMatches is a convenience method that accepts a AddressMatcher.
func (m UserMatcher) AddressMatches(matcher AddressMatcher) UserMatcher {
	m.addressMatcher = matcher.Matcher()
	return m
}

// CreatedAt adds a matcher for the CreatedAt field.
func (m UserMatcher) CreatedAt(matcher testgen.Matcher[time.Time]) UserMatcher {
	m.createdAtMatcher = matcher
	return m
}

// UpdatedAt adds a matcher for the UpdatedAt field.
func (m UserMatcher) UpdatedAt(matcher testgen.Matcher[time.Time]) UserMatcher {
	m.updatedAtMatcher = matcher
	return m
}

// Matcher returns the composed matcher for User.
func (m UserMatcher) Matcher() testgen.Matcher[showcase.User] {
	return testgen.MatcherFunc[showcase.User](func(actual showcase.User) testgen.MatchResult {
		// Extract all field values upfront (call each getter exactly once)
		iDValue := actual.ID
		emailValue := actual.Email
		firstNameValue := actual.FirstName
		lastNameValue := actual.LastName
		activeValue := actual.Active
		addressValue := actual.Address
		createdAtValue := actual.CreatedAt
		updatedAtValue := actual.UpdatedAt

		// Build fieldValues map for structured diff
		fieldValues := map[string]any{
			"ID":        iDValue,
			"Email":     emailValue,
			"FirstName": firstNameValue,
			"LastName":  lastNameValue,
			"Active":    activeValue,
			"Address":   addressValue,
			"CreatedAt": createdAtValue,
			"UpdatedAt": updatedAtValue,
		}

		// Check matchers using cached values and store results
		fieldResults := make(map[string]*testgen.MatchResult)
		hasFailures := false
		if m.iDMatcher != nil {
			result := m.iDMatcher.Matches(iDValue)
			fieldResults["ID"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}
		if m.emailMatcher != nil {
			result := m.emailMatcher.Matches(emailValue)
			fieldResults["Email"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}
		if m.firstNameMatcher != nil {
			result := m.firstNameMatcher.Matches(firstNameValue)
			fieldResults["FirstName"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}
		if m.lastNameMatcher != nil {
			result := m.lastNameMatcher.Matches(lastNameValue)
			fieldResults["LastName"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}
		if m.activeMatcher != nil {
			result := m.activeMatcher.Matches(activeValue)
			fieldResults["Active"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}
		if m.addressMatcher != nil {
			result := m.addressMatcher.Matches(addressValue)
			fieldResults["Address"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}
		if m.createdAtMatcher != nil {
			result := m.createdAtMatcher.Matches(createdAtValue)
			fieldResults["CreatedAt"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}
		if m.updatedAtMatcher != nil {
			result := m.updatedAtMatcher.Matches(updatedAtValue)
			fieldResults["UpdatedAt"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if hasFailures {
			// Use structured diff for struct types
			structDiff := testgen.BuildMatcherStructDiff("User", fieldValues, fieldResults)
			return testgen.MatchResult{
				Matched: false,
				Message: structDiff,
			}
		}
		return testgen.MatchResult{Matched: true}
	})
}
