// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	"time"

	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
)

// UserMatcher provides a fluent API for matching User instances.
type UserMatcher struct {
	iDMatcher        specta.Matcher[string]
	emailMatcher     specta.Matcher[string]
	firstNameMatcher specta.Matcher[string]
	lastNameMatcher  specta.Matcher[string]
	activeMatcher    specta.Matcher[bool]
	addressMatcher   specta.Matcher[showcase.Address]
	createdAtMatcher specta.Matcher[time.Time]
	updatedAtMatcher specta.Matcher[time.Time]
}

// UserMatches creates a new UserMatcher for matching User instances.
//
// This matcher provides methods for the following fields:
//   - ID (string)
//   - Email (string)
//   - FirstName (string)
//   - LastName (string)
//   - Active (bool)
//   - Address (showcase.Address)
//   - CreatedAt (time.Time)
//   - UpdatedAt (time.Time)
//
// Example:
//
//	matcher := factory.UserMatches().
//	    ID(specta.Equal("expected_value")).
//	    Email(specta.Contains("substring")).
//	    Matcher()
//
//	specta.AssertThat(t, actualUser, matcher)
func UserMatches() UserMatcher {
	return UserMatcher{}
}

// ID adds a matcher for the ID field.
func (m UserMatcher) ID(matcher specta.Matcher[string]) UserMatcher {
	m.iDMatcher = matcher
	return m
}

// Email adds a matcher for the Email field.
func (m UserMatcher) Email(matcher specta.Matcher[string]) UserMatcher {
	m.emailMatcher = matcher
	return m
}

// FirstName adds a matcher for the FirstName field.
func (m UserMatcher) FirstName(matcher specta.Matcher[string]) UserMatcher {
	m.firstNameMatcher = matcher
	return m
}

// LastName adds a matcher for the LastName field.
func (m UserMatcher) LastName(matcher specta.Matcher[string]) UserMatcher {
	m.lastNameMatcher = matcher
	return m
}

// Active adds a matcher for the Active field.
func (m UserMatcher) Active(matcher specta.Matcher[bool]) UserMatcher {
	m.activeMatcher = matcher
	return m
}

// Address adds a matcher for the Address field.
func (m UserMatcher) Address(matcher specta.Matcher[showcase.Address]) UserMatcher {
	m.addressMatcher = matcher
	return m
}

// AddressMatches is a convenience method that accepts a AddressMatcher.
func (m UserMatcher) AddressMatches(matcher AddressMatcher) UserMatcher {
	m.addressMatcher = matcher.Matcher()
	return m
}

// CreatedAt adds a matcher for the CreatedAt field.
func (m UserMatcher) CreatedAt(matcher specta.Matcher[time.Time]) UserMatcher {
	m.createdAtMatcher = matcher
	return m
}

// UpdatedAt adds a matcher for the UpdatedAt field.
func (m UserMatcher) UpdatedAt(matcher specta.Matcher[time.Time]) UserMatcher {
	m.updatedAtMatcher = matcher
	return m
}

// Matcher returns the composed matcher for User.
func (m UserMatcher) Matcher() specta.Matcher[showcase.User] {
	return specta.MatcherFunc[showcase.User](func(actual showcase.User) specta.MatchResult {
		// Extract all field values upfront (call each getter exactly once)
		iDValue := actual.ID
		emailValue := actual.Email
		firstNameValue := actual.FirstName
		lastNameValue := actual.LastName
		activeValue := actual.Active
		addressValue := actual.Address
		createdAtValue := actual.CreatedAt
		updatedAtValue := actual.UpdatedAt

		// Build fieldValues map for structured diff
		fieldValues := map[string]any{
			"ID":        iDValue,
			"Email":     emailValue,
			"FirstName": firstNameValue,
			"LastName":  lastNameValue,
			"Active":    activeValue,
			"Address":   addressValue,
			"CreatedAt": createdAtValue,
			"UpdatedAt": updatedAtValue,
		}

		// Check matchers using cached values and store results
		fieldResults := make(map[string]*specta.MatchResult)
		hasFailures := false

		if m.iDMatcher != nil {
			result := m.iDMatcher.Matches(iDValue)
			fieldResults["ID"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.emailMatcher != nil {
			result := m.emailMatcher.Matches(emailValue)
			fieldResults["Email"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.firstNameMatcher != nil {
			result := m.firstNameMatcher.Matches(firstNameValue)
			fieldResults["FirstName"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.lastNameMatcher != nil {
			result := m.lastNameMatcher.Matches(lastNameValue)
			fieldResults["LastName"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.activeMatcher != nil {
			result := m.activeMatcher.Matches(activeValue)
			fieldResults["Active"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.addressMatcher != nil {
			result := m.addressMatcher.Matches(addressValue)
			fieldResults["Address"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.createdAtMatcher != nil {
			result := m.createdAtMatcher.Matches(createdAtValue)
			fieldResults["CreatedAt"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if m.updatedAtMatcher != nil {
			result := m.updatedAtMatcher.Matches(updatedAtValue)
			fieldResults["UpdatedAt"] = &result
			if !result.Matched {
				hasFailures = true
			}
		}

		if hasFailures {
			// Use structured diff for struct types
			structDiff := specta.BuildMatcherStructDiff("User", fieldValues, fieldResults)
			return specta.MatchResult{
				Matched: false,
				Message: structDiff,
			}
		}
		return specta.MatchResult{Matched: true}
	})
}
