// Code generated by specta; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

// This file contains the recipe (test data builder) for User.
//
// Use User() to build instances with custom fields, or Many() for multiple unique instances.
package factory

import (
	"time"

	specta "github.com/james-w/specta"
	"github.com/james-w/specta/showcase"
	"github.com/james-w/specta/showcase/factory/spec"
)

// UserRecipe provides a fluent API for building User instances.
type UserRecipe struct {
	opts          []specta.Opt[spec.UserSpec]
	addressRecipe *AddressRecipe
}

// User creates a new UserRecipe for building User instances.
//
// This is a struct-based type with the following fields:
//   - ID (string)
//   - Email (string)
//   - FirstName (string)
//   - LastName (string)
//   - Active (bool)
//   - Address (showcase.Address)
//   - CreatedAt (time.Time)
//   - UpdatedAt (time.Time)
//
// Example:
//
//	p := specta.New()
//	user := factory.User().
//	    ID("custom_value").
//	    Email("another").
//	    Build(p)
func User() UserRecipe { return UserRecipe{} }

// ID sets the ID field.
func (r UserRecipe) ID(v string) UserRecipe {
	r.opts = append(r.opts, spec.WithUserID(v))
	return r
}

// IDFromGenerator sets the ID field using a Generator.
func (r UserRecipe) IDFromGenerator(gen specta.Generator[string]) UserRecipe {
	r.opts = append(r.opts, spec.WithUserIDFromGenerator(gen))
	return r
}

// Email sets the Email field.
func (r UserRecipe) Email(v string) UserRecipe {
	r.opts = append(r.opts, spec.WithUserEmail(v))
	return r
}

// EmailFromGenerator sets the Email field using a Generator.
func (r UserRecipe) EmailFromGenerator(gen specta.Generator[string]) UserRecipe {
	r.opts = append(r.opts, spec.WithUserEmailFromGenerator(gen))
	return r
}

// FirstName sets the FirstName field.
func (r UserRecipe) FirstName(v string) UserRecipe {
	r.opts = append(r.opts, spec.WithUserFirstName(v))
	return r
}

// FirstNameFromGenerator sets the FirstName field using a Generator.
func (r UserRecipe) FirstNameFromGenerator(gen specta.Generator[string]) UserRecipe {
	r.opts = append(r.opts, spec.WithUserFirstNameFromGenerator(gen))
	return r
}

// LastName sets the LastName field.
func (r UserRecipe) LastName(v string) UserRecipe {
	r.opts = append(r.opts, spec.WithUserLastName(v))
	return r
}

// LastNameFromGenerator sets the LastName field using a Generator.
func (r UserRecipe) LastNameFromGenerator(gen specta.Generator[string]) UserRecipe {
	r.opts = append(r.opts, spec.WithUserLastNameFromGenerator(gen))
	return r
}

// Active sets the Active field.
func (r UserRecipe) Active(v bool) UserRecipe {
	r.opts = append(r.opts, spec.WithUserActive(v))
	return r
}

// ActiveFromGenerator sets the Active field using a Generator.
func (r UserRecipe) ActiveFromGenerator(gen specta.Generator[bool]) UserRecipe {
	r.opts = append(r.opts, spec.WithUserActiveFromGenerator(gen))
	return r
}

// Address sets the Address field.
func (r UserRecipe) Address(v showcase.Address) UserRecipe {
	r.opts = append(r.opts, spec.WithUserAddress(v))
	r.addressRecipe = nil
	return r
}

// AddressFromGenerator sets the Address field using a Generator.
func (r UserRecipe) AddressFromGenerator(gen specta.Generator[showcase.Address]) UserRecipe {
	r.opts = append(r.opts, spec.WithUserAddressFromGenerator(gen))
	r.addressRecipe = nil
	return r
}

// AddressFromRecipe sets the Address field using another Recipe (creates unique instances).
// The recipe is captured at call time (value semantics) - subsequent changes to v won't affect this recipe.
// The nested recipe is used for partial matching in AsEqualMatcher.
func (r UserRecipe) AddressFromRecipe(v AddressRecipe) UserRecipe {
	r.opts = append(r.opts, spec.WithUserAddressFromGenerator(v.Gen()))
	r.addressRecipe = &v
	return r
}

// CreatedAt sets the CreatedAt field.
func (r UserRecipe) CreatedAt(v time.Time) UserRecipe {
	r.opts = append(r.opts, spec.WithUserCreatedAt(v))
	return r
}

// CreatedAtFromGenerator sets the CreatedAt field using a Generator.
func (r UserRecipe) CreatedAtFromGenerator(gen specta.Generator[time.Time]) UserRecipe {
	r.opts = append(r.opts, spec.WithUserCreatedAtFromGenerator(gen))
	return r
}

// UpdatedAt sets the UpdatedAt field.
func (r UserRecipe) UpdatedAt(v time.Time) UserRecipe {
	r.opts = append(r.opts, spec.WithUserUpdatedAt(v))
	return r
}

// UpdatedAtFromGenerator sets the UpdatedAt field using a Generator.
func (r UserRecipe) UpdatedAtFromGenerator(gen specta.Generator[time.Time]) UserRecipe {
	r.opts = append(r.opts, spec.WithUserUpdatedAtFromGenerator(gen))
	return r
}

// Gen returns a Gen[T] for use in nested custom types.
func (r UserRecipe) Gen() specta.Gen[showcase.User] {
	return specta.FromSpecGen(spec.BuildUser, spec.NewUserSpec, r.opts...)
}

// Build creates a single User instance.
func (r UserRecipe) Build(s specta.Source) showcase.User {
	return spec.NewUserFactory(s).Make(r.opts...)
}

// Many creates multiple User instances with unique generated values.
func (r UserRecipe) Many(n int, s specta.Source) []showcase.User {
	return spec.NewUserFactory(s).Many(n, r.opts...)
}

// AsEqualMatcher converts this Recipe into a Matcher that checks for equality on all set fields.
// Only fields that were explicitly set in the Recipe will be checked - unset fields are ignored.
// This enables partial matching where you only verify specific fields.
// For nested types set via FromRecipe, partial matching is applied recursively.
func (r UserRecipe) AsEqualMatcher() specta.Matcher[showcase.User] {
	// Apply opts to a spec to see what was set
	s := spec.NewUserSpec()
	for _, opt := range r.opts {
		opt(&s)
	}

	// Use a dummy Source to evaluate literal values
	// This works for SetLit values; SetWith/Provider values will be evaluated too
	p := specta.New()

	// Build matcher only for set fields
	m := UserMatches()
	if s.ID.IsSet() {
		m = m.ID(specta.DeepEqual(s.ID.GetValue(p, "ID")))
	}
	if s.Email.IsSet() {
		m = m.Email(specta.DeepEqual(s.Email.GetValue(p, "Email")))
	}
	if s.FirstName.IsSet() {
		m = m.FirstName(specta.DeepEqual(s.FirstName.GetValue(p, "FirstName")))
	}
	if s.LastName.IsSet() {
		m = m.LastName(specta.DeepEqual(s.LastName.GetValue(p, "LastName")))
	}
	if s.Active.IsSet() {
		m = m.Active(specta.DeepEqual(s.Active.GetValue(p, "Active")))
	}
	if s.Address.IsSet() {
		// Check if we have a nested recipe for partial matching
		if r.addressRecipe != nil {
			m = m.Address(r.addressRecipe.AsEqualMatcher())
		} else {
			m = m.Address(specta.DeepEqual(s.Address.GetValue(p, "Address")))
		}
	}
	if s.CreatedAt.IsSet() {
		m = m.CreatedAt(specta.DeepEqual(s.CreatedAt.GetValue(p, "CreatedAt")))
	}
	if s.UpdatedAt.IsSet() {
		m = m.UpdatedAt(specta.DeepEqual(s.UpdatedAt.GetValue(p, "UpdatedAt")))
	}

	return m.Matcher()
}
