// Code generated by testgen-gen; DO NOT EDIT.
//go:build !ignore_testgen
// +build !ignore_testgen

package factory

import (
	"time"

	testgen "github.com/james-w/gomatchers"
	"github.com/james-w/gomatchers/showcase"
)

// ============================================================================
// Low-level API: Spec, Build, and Options
// ============================================================================

type UserSpec struct {
	ID        testgen.Maybe[string]
	Email     testgen.Maybe[string]
	FirstName testgen.Maybe[string]
	LastName  testgen.Maybe[string]
	Active    testgen.Maybe[bool]
	Address   testgen.Maybe[showcase.Address]
	CreatedAt testgen.Maybe[time.Time]
	UpdatedAt testgen.Maybe[time.Time]
}

func NewUserSpec() UserSpec { return UserSpec{} }

func NewUserFactory(p testgen.Primitives) *testgen.SpecFactory[showcase.User, UserSpec] {
	return testgen.NewSpecFactory(p, NewUserSpec, BuildUser)
}

// Defaults (simple heuristics).
var (
	UserDefaultID        = func(p testgen.Primitives) string { return p.ID() }
	UserDefaultEmail     = func(p testgen.Primitives) string { return p.StringWith("email_") }
	UserDefaultFirstName = func(p testgen.Primitives) string { return p.StringWith("firstname_") }
	UserDefaultLastName  = func(p testgen.Primitives) string { return p.StringWith("lastname_") }
	UserDefaultActive    = func(p testgen.Primitives) bool { return p.Bool() }
	UserDefaultAddress   = testgen.FromSpec(BuildAddress, NewAddressSpec)
	UserDefaultCreatedAt = func(p testgen.Primitives) time.Time { return p.Time() }
	UserDefaultUpdatedAt = func(p testgen.Primitives) time.Time { return p.Time() }
)

func BuildUser(p testgen.Primitives, s UserSpec) showcase.User {
	iD := s.ID.Get(p, UserDefaultID)
	email := s.Email.Get(p, UserDefaultEmail)
	firstName := s.FirstName.Get(p, UserDefaultFirstName)
	lastName := s.LastName.Get(p, UserDefaultLastName)
	active := s.Active.Get(p, UserDefaultActive)
	address := s.Address.Get(p, UserDefaultAddress)
	createdAt := s.CreatedAt.Get(p, UserDefaultCreatedAt)
	updatedAt := s.UpdatedAt.Get(p, UserDefaultUpdatedAt)
	return showcase.User{
		ID:        iD,
		Email:     email,
		FirstName: firstName,
		LastName:  lastName,
		Active:    active,
		Address:   address,
		CreatedAt: createdAt,
		UpdatedAt: updatedAt,
	}
}

func WithUserID(v string) testgen.Opt[UserSpec] {
	return testgen.SetLit(func(s *UserSpec, m testgen.Maybe[string]) { s.ID = m }, v)
}

func WithUserEmail(v string) testgen.Opt[UserSpec] {
	return testgen.SetLit(func(s *UserSpec, m testgen.Maybe[string]) { s.Email = m }, v)
}

func WithUserFirstName(v string) testgen.Opt[UserSpec] {
	return testgen.SetLit(func(s *UserSpec, m testgen.Maybe[string]) { s.FirstName = m }, v)
}

func WithUserLastName(v string) testgen.Opt[UserSpec] {
	return testgen.SetLit(func(s *UserSpec, m testgen.Maybe[string]) { s.LastName = m }, v)
}

func WithUserActive(v bool) testgen.Opt[UserSpec] {
	return testgen.SetLit(func(s *UserSpec, m testgen.Maybe[bool]) { s.Active = m }, v)
}

func WithUserAddress(v showcase.Address) testgen.Opt[UserSpec] {
	return testgen.SetLit(func(s *UserSpec, m testgen.Maybe[showcase.Address]) { s.Address = m }, v)
}

func WithUserAddressFromRecipe(rec AddressRecipe) testgen.Opt[UserSpec] {
	return testgen.SetWith(
		func(s *UserSpec, m testgen.Maybe[showcase.Address]) { s.Address = m },
		rec.Provider(),
	)
}

func WithUserCreatedAt(v time.Time) testgen.Opt[UserSpec] {
	return testgen.SetLit(func(s *UserSpec, m testgen.Maybe[time.Time]) { s.CreatedAt = m }, v)
}

func WithUserUpdatedAt(v time.Time) testgen.Opt[UserSpec] {
	return testgen.SetLit(func(s *UserSpec, m testgen.Maybe[time.Time]) { s.UpdatedAt = m }, v)
}

// ============================================================================
// High-level Recipe API
// ============================================================================

type UserRecipe struct{ opts []testgen.Opt[UserSpec] }

func User() UserRecipe { return UserRecipe{} }

func (r UserRecipe) ID(v string) UserRecipe {
	r.opts = append(r.opts, WithUserID(v))
	return r
}

func (r UserRecipe) Email(v string) UserRecipe {
	r.opts = append(r.opts, WithUserEmail(v))
	return r
}

func (r UserRecipe) FirstName(v string) UserRecipe {
	r.opts = append(r.opts, WithUserFirstName(v))
	return r
}

func (r UserRecipe) LastName(v string) UserRecipe {
	r.opts = append(r.opts, WithUserLastName(v))
	return r
}

func (r UserRecipe) Active(v bool) UserRecipe {
	r.opts = append(r.opts, WithUserActive(v))
	return r
}

func (r UserRecipe) Address(v showcase.Address) UserRecipe {
	r.opts = append(r.opts, WithUserAddress(v))
	return r
}

func (r UserRecipe) AddressFromRecipe(v AddressRecipe) UserRecipe {
	r.opts = append(r.opts, WithUserAddressFromRecipe(v))
	return r
}

func (r UserRecipe) CreatedAt(v time.Time) UserRecipe {
	r.opts = append(r.opts, WithUserCreatedAt(v))
	return r
}

func (r UserRecipe) UpdatedAt(v time.Time) UserRecipe {
	r.opts = append(r.opts, WithUserUpdatedAt(v))
	return r
}

// Provider for nesting into parents (defers evaluation; consumes Primitives later)
func (r UserRecipe) Provider() testgen.Provider[showcase.User] {
	return testgen.FromSpec(BuildUser, NewUserSpec, r.opts...)
}

// Build now if you need a concrete value (rare in composing tests)
func (r UserRecipe) Build(p testgen.Primitives) showcase.User {
	return NewUserFactory(p).Make(r.opts...)
}

func (r UserRecipe) Many(n int, p testgen.Primitives) []showcase.User {
	return NewUserFactory(p).Many(n, r.opts...)
}
